// Code generated by ent, DO NOT EDIT.

package videomodel

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the videomodel type in the database.
	Label = "video_model"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldPublicModel holds the string denoting the public_model field in the database.
	FieldPublicModel = "public_model"
	// FieldDisplayName holds the string denoting the display_name field in the database.
	FieldDisplayName = "display_name"
	// FieldTemplateID holds the string denoting the template_id field in the database.
	FieldTemplateID = "template_id"
	// FieldUpstreamModelID holds the string denoting the upstream_model_id field in the database.
	FieldUpstreamModelID = "upstream_model_id"
	// FieldRequestShape holds the string denoting the request_shape field in the database.
	FieldRequestShape = "request_shape"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCapabilities holds the string denoting the capabilities field in the database.
	FieldCapabilities = "capabilities"
	// FieldDefaults holds the string denoting the defaults field in the database.
	FieldDefaults = "defaults"
	// FieldLimits holds the string denoting the limits field in the database.
	FieldLimits = "limits"
	// FieldSupportedOptions holds the string denoting the supported_options field in the database.
	FieldSupportedOptions = "supported_options"
	// FieldExtraBodyAllow holds the string denoting the extra_body_allow field in the database.
	FieldExtraBodyAllow = "extra_body_allow"
	// FieldSortOrder holds the string denoting the sort_order field in the database.
	FieldSortOrder = "sort_order"
	// EdgeTemplate holds the string denoting the template edge name in mutations.
	EdgeTemplate = "template"
	// EdgeTasks holds the string denoting the tasks edge name in mutations.
	EdgeTasks = "tasks"
	// Table holds the table name of the videomodel in the database.
	Table = "video_models"
	// TemplateTable is the table that holds the template relation/edge.
	TemplateTable = "video_models"
	// TemplateInverseTable is the table name for the VideoCallTemplate entity.
	// It exists in this package in order to avoid circular dependency with the "videocalltemplate" package.
	TemplateInverseTable = "video_call_templates"
	// TemplateColumn is the table column denoting the template relation/edge.
	TemplateColumn = "template_id"
	// TasksTable is the table that holds the tasks relation/edge.
	TasksTable = "video_generation_tasks"
	// TasksInverseTable is the table name for the VideoGenerationTask entity.
	// It exists in this package in order to avoid circular dependency with the "videogenerationtask" package.
	TasksInverseTable = "video_generation_tasks"
	// TasksColumn is the table column denoting the tasks relation/edge.
	TasksColumn = "video_model_id"
)

// Columns holds all SQL columns for videomodel fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldPublicModel,
	FieldDisplayName,
	FieldTemplateID,
	FieldUpstreamModelID,
	FieldRequestShape,
	FieldStatus,
	FieldCapabilities,
	FieldDefaults,
	FieldLimits,
	FieldSupportedOptions,
	FieldExtraBodyAllow,
	FieldSortOrder,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// PublicModelValidator is a validator for the "public_model" field. It is called by the builders before save.
	PublicModelValidator func(string) error
	// DisplayNameValidator is a validator for the "display_name" field. It is called by the builders before save.
	DisplayNameValidator func(string) error
	// UpstreamModelIDValidator is a validator for the "upstream_model_id" field. It is called by the builders before save.
	UpstreamModelIDValidator func(string) error
	// RequestShapeValidator is a validator for the "request_shape" field. It is called by the builders before save.
	RequestShapeValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultCapabilities holds the default value on creation for the "capabilities" field.
	DefaultCapabilities func() map[string]interface{}
	// DefaultDefaults holds the default value on creation for the "defaults" field.
	DefaultDefaults func() map[string]interface{}
	// DefaultLimits holds the default value on creation for the "limits" field.
	DefaultLimits func() map[string]interface{}
	// DefaultSupportedOptions holds the default value on creation for the "supported_options" field.
	DefaultSupportedOptions func() map[string]interface{}
	// DefaultExtraBodyAllow holds the default value on creation for the "extra_body_allow" field.
	DefaultExtraBodyAllow []string
	// DefaultSortOrder holds the default value on creation for the "sort_order" field.
	DefaultSortOrder int
)

// OrderOption defines the ordering options for the VideoModel queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByPublicModel orders the results by the public_model field.
func ByPublicModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublicModel, opts...).ToFunc()
}

// ByDisplayName orders the results by the display_name field.
func ByDisplayName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDisplayName, opts...).ToFunc()
}

// ByTemplateID orders the results by the template_id field.
func ByTemplateID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTemplateID, opts...).ToFunc()
}

// ByUpstreamModelID orders the results by the upstream_model_id field.
func ByUpstreamModelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamModelID, opts...).ToFunc()
}

// ByRequestShape orders the results by the request_shape field.
func ByRequestShape(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestShape, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// BySortOrder orders the results by the sort_order field.
func BySortOrder(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSortOrder, opts...).ToFunc()
}

// ByTemplateField orders the results by template field.
func ByTemplateField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTemplateStep(), sql.OrderByField(field, opts...))
	}
}

// ByTasksCount orders the results by tasks count.
func ByTasksCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTasksStep(), opts...)
	}
}

// ByTasks orders the results by tasks terms.
func ByTasks(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTasksStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newTemplateStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TemplateInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, TemplateTable, TemplateColumn),
	)
}
func newTasksStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TasksInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, TasksTable, TasksColumn),
	)
}
