// Code generated by ent, DO NOT EDIT.

package videomodel

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/ccapi/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldEQ(FieldUpdatedAt, v))
}

// PublicModel applies equality check predicate on the "public_model" field. It's identical to PublicModelEQ.
func PublicModel(v string) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldEQ(FieldPublicModel, v))
}

// DisplayName applies equality check predicate on the "display_name" field. It's identical to DisplayNameEQ.
func DisplayName(v string) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldEQ(FieldDisplayName, v))
}

// TemplateID applies equality check predicate on the "template_id" field. It's identical to TemplateIDEQ.
func TemplateID(v int64) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldEQ(FieldTemplateID, v))
}

// UpstreamModelID applies equality check predicate on the "upstream_model_id" field. It's identical to UpstreamModelIDEQ.
func UpstreamModelID(v string) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldEQ(FieldUpstreamModelID, v))
}

// RequestShape applies equality check predicate on the "request_shape" field. It's identical to RequestShapeEQ.
func RequestShape(v string) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldEQ(FieldRequestShape, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldEQ(FieldStatus, v))
}

// SortOrder applies equality check predicate on the "sort_order" field. It's identical to SortOrderEQ.
func SortOrder(v int) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldEQ(FieldSortOrder, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldLTE(FieldUpdatedAt, v))
}

// PublicModelEQ applies the EQ predicate on the "public_model" field.
func PublicModelEQ(v string) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldEQ(FieldPublicModel, v))
}

// PublicModelNEQ applies the NEQ predicate on the "public_model" field.
func PublicModelNEQ(v string) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldNEQ(FieldPublicModel, v))
}

// PublicModelIn applies the In predicate on the "public_model" field.
func PublicModelIn(vs ...string) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldIn(FieldPublicModel, vs...))
}

// PublicModelNotIn applies the NotIn predicate on the "public_model" field.
func PublicModelNotIn(vs ...string) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldNotIn(FieldPublicModel, vs...))
}

// PublicModelGT applies the GT predicate on the "public_model" field.
func PublicModelGT(v string) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldGT(FieldPublicModel, v))
}

// PublicModelGTE applies the GTE predicate on the "public_model" field.
func PublicModelGTE(v string) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldGTE(FieldPublicModel, v))
}

// PublicModelLT applies the LT predicate on the "public_model" field.
func PublicModelLT(v string) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldLT(FieldPublicModel, v))
}

// PublicModelLTE applies the LTE predicate on the "public_model" field.
func PublicModelLTE(v string) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldLTE(FieldPublicModel, v))
}

// PublicModelContains applies the Contains predicate on the "public_model" field.
func PublicModelContains(v string) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldContains(FieldPublicModel, v))
}

// PublicModelHasPrefix applies the HasPrefix predicate on the "public_model" field.
func PublicModelHasPrefix(v string) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldHasPrefix(FieldPublicModel, v))
}

// PublicModelHasSuffix applies the HasSuffix predicate on the "public_model" field.
func PublicModelHasSuffix(v string) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldHasSuffix(FieldPublicModel, v))
}

// PublicModelEqualFold applies the EqualFold predicate on the "public_model" field.
func PublicModelEqualFold(v string) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldEqualFold(FieldPublicModel, v))
}

// PublicModelContainsFold applies the ContainsFold predicate on the "public_model" field.
func PublicModelContainsFold(v string) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldContainsFold(FieldPublicModel, v))
}

// DisplayNameEQ applies the EQ predicate on the "display_name" field.
func DisplayNameEQ(v string) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldEQ(FieldDisplayName, v))
}

// DisplayNameNEQ applies the NEQ predicate on the "display_name" field.
func DisplayNameNEQ(v string) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldNEQ(FieldDisplayName, v))
}

// DisplayNameIn applies the In predicate on the "display_name" field.
func DisplayNameIn(vs ...string) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldIn(FieldDisplayName, vs...))
}

// DisplayNameNotIn applies the NotIn predicate on the "display_name" field.
func DisplayNameNotIn(vs ...string) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldNotIn(FieldDisplayName, vs...))
}

// DisplayNameGT applies the GT predicate on the "display_name" field.
func DisplayNameGT(v string) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldGT(FieldDisplayName, v))
}

// DisplayNameGTE applies the GTE predicate on the "display_name" field.
func DisplayNameGTE(v string) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldGTE(FieldDisplayName, v))
}

// DisplayNameLT applies the LT predicate on the "display_name" field.
func DisplayNameLT(v string) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldLT(FieldDisplayName, v))
}

// DisplayNameLTE applies the LTE predicate on the "display_name" field.
func DisplayNameLTE(v string) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldLTE(FieldDisplayName, v))
}

// DisplayNameContains applies the Contains predicate on the "display_name" field.
func DisplayNameContains(v string) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldContains(FieldDisplayName, v))
}

// DisplayNameHasPrefix applies the HasPrefix predicate on the "display_name" field.
func DisplayNameHasPrefix(v string) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldHasPrefix(FieldDisplayName, v))
}

// DisplayNameHasSuffix applies the HasSuffix predicate on the "display_name" field.
func DisplayNameHasSuffix(v string) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldHasSuffix(FieldDisplayName, v))
}

// DisplayNameIsNil applies the IsNil predicate on the "display_name" field.
func DisplayNameIsNil() predicate.VideoModel {
	return predicate.VideoModel(sql.FieldIsNull(FieldDisplayName))
}

// DisplayNameNotNil applies the NotNil predicate on the "display_name" field.
func DisplayNameNotNil() predicate.VideoModel {
	return predicate.VideoModel(sql.FieldNotNull(FieldDisplayName))
}

// DisplayNameEqualFold applies the EqualFold predicate on the "display_name" field.
func DisplayNameEqualFold(v string) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldEqualFold(FieldDisplayName, v))
}

// DisplayNameContainsFold applies the ContainsFold predicate on the "display_name" field.
func DisplayNameContainsFold(v string) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldContainsFold(FieldDisplayName, v))
}

// TemplateIDEQ applies the EQ predicate on the "template_id" field.
func TemplateIDEQ(v int64) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldEQ(FieldTemplateID, v))
}

// TemplateIDNEQ applies the NEQ predicate on the "template_id" field.
func TemplateIDNEQ(v int64) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldNEQ(FieldTemplateID, v))
}

// TemplateIDIn applies the In predicate on the "template_id" field.
func TemplateIDIn(vs ...int64) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldIn(FieldTemplateID, vs...))
}

// TemplateIDNotIn applies the NotIn predicate on the "template_id" field.
func TemplateIDNotIn(vs ...int64) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldNotIn(FieldTemplateID, vs...))
}

// UpstreamModelIDEQ applies the EQ predicate on the "upstream_model_id" field.
func UpstreamModelIDEQ(v string) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldEQ(FieldUpstreamModelID, v))
}

// UpstreamModelIDNEQ applies the NEQ predicate on the "upstream_model_id" field.
func UpstreamModelIDNEQ(v string) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldNEQ(FieldUpstreamModelID, v))
}

// UpstreamModelIDIn applies the In predicate on the "upstream_model_id" field.
func UpstreamModelIDIn(vs ...string) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldIn(FieldUpstreamModelID, vs...))
}

// UpstreamModelIDNotIn applies the NotIn predicate on the "upstream_model_id" field.
func UpstreamModelIDNotIn(vs ...string) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldNotIn(FieldUpstreamModelID, vs...))
}

// UpstreamModelIDGT applies the GT predicate on the "upstream_model_id" field.
func UpstreamModelIDGT(v string) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldGT(FieldUpstreamModelID, v))
}

// UpstreamModelIDGTE applies the GTE predicate on the "upstream_model_id" field.
func UpstreamModelIDGTE(v string) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldGTE(FieldUpstreamModelID, v))
}

// UpstreamModelIDLT applies the LT predicate on the "upstream_model_id" field.
func UpstreamModelIDLT(v string) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldLT(FieldUpstreamModelID, v))
}

// UpstreamModelIDLTE applies the LTE predicate on the "upstream_model_id" field.
func UpstreamModelIDLTE(v string) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldLTE(FieldUpstreamModelID, v))
}

// UpstreamModelIDContains applies the Contains predicate on the "upstream_model_id" field.
func UpstreamModelIDContains(v string) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldContains(FieldUpstreamModelID, v))
}

// UpstreamModelIDHasPrefix applies the HasPrefix predicate on the "upstream_model_id" field.
func UpstreamModelIDHasPrefix(v string) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldHasPrefix(FieldUpstreamModelID, v))
}

// UpstreamModelIDHasSuffix applies the HasSuffix predicate on the "upstream_model_id" field.
func UpstreamModelIDHasSuffix(v string) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldHasSuffix(FieldUpstreamModelID, v))
}

// UpstreamModelIDIsNil applies the IsNil predicate on the "upstream_model_id" field.
func UpstreamModelIDIsNil() predicate.VideoModel {
	return predicate.VideoModel(sql.FieldIsNull(FieldUpstreamModelID))
}

// UpstreamModelIDNotNil applies the NotNil predicate on the "upstream_model_id" field.
func UpstreamModelIDNotNil() predicate.VideoModel {
	return predicate.VideoModel(sql.FieldNotNull(FieldUpstreamModelID))
}

// UpstreamModelIDEqualFold applies the EqualFold predicate on the "upstream_model_id" field.
func UpstreamModelIDEqualFold(v string) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldEqualFold(FieldUpstreamModelID, v))
}

// UpstreamModelIDContainsFold applies the ContainsFold predicate on the "upstream_model_id" field.
func UpstreamModelIDContainsFold(v string) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldContainsFold(FieldUpstreamModelID, v))
}

// RequestShapeEQ applies the EQ predicate on the "request_shape" field.
func RequestShapeEQ(v string) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldEQ(FieldRequestShape, v))
}

// RequestShapeNEQ applies the NEQ predicate on the "request_shape" field.
func RequestShapeNEQ(v string) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldNEQ(FieldRequestShape, v))
}

// RequestShapeIn applies the In predicate on the "request_shape" field.
func RequestShapeIn(vs ...string) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldIn(FieldRequestShape, vs...))
}

// RequestShapeNotIn applies the NotIn predicate on the "request_shape" field.
func RequestShapeNotIn(vs ...string) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldNotIn(FieldRequestShape, vs...))
}

// RequestShapeGT applies the GT predicate on the "request_shape" field.
func RequestShapeGT(v string) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldGT(FieldRequestShape, v))
}

// RequestShapeGTE applies the GTE predicate on the "request_shape" field.
func RequestShapeGTE(v string) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldGTE(FieldRequestShape, v))
}

// RequestShapeLT applies the LT predicate on the "request_shape" field.
func RequestShapeLT(v string) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldLT(FieldRequestShape, v))
}

// RequestShapeLTE applies the LTE predicate on the "request_shape" field.
func RequestShapeLTE(v string) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldLTE(FieldRequestShape, v))
}

// RequestShapeContains applies the Contains predicate on the "request_shape" field.
func RequestShapeContains(v string) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldContains(FieldRequestShape, v))
}

// RequestShapeHasPrefix applies the HasPrefix predicate on the "request_shape" field.
func RequestShapeHasPrefix(v string) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldHasPrefix(FieldRequestShape, v))
}

// RequestShapeHasSuffix applies the HasSuffix predicate on the "request_shape" field.
func RequestShapeHasSuffix(v string) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldHasSuffix(FieldRequestShape, v))
}

// RequestShapeEqualFold applies the EqualFold predicate on the "request_shape" field.
func RequestShapeEqualFold(v string) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldEqualFold(FieldRequestShape, v))
}

// RequestShapeContainsFold applies the ContainsFold predicate on the "request_shape" field.
func RequestShapeContainsFold(v string) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldContainsFold(FieldRequestShape, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldContainsFold(FieldStatus, v))
}

// SortOrderEQ applies the EQ predicate on the "sort_order" field.
func SortOrderEQ(v int) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldEQ(FieldSortOrder, v))
}

// SortOrderNEQ applies the NEQ predicate on the "sort_order" field.
func SortOrderNEQ(v int) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldNEQ(FieldSortOrder, v))
}

// SortOrderIn applies the In predicate on the "sort_order" field.
func SortOrderIn(vs ...int) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldIn(FieldSortOrder, vs...))
}

// SortOrderNotIn applies the NotIn predicate on the "sort_order" field.
func SortOrderNotIn(vs ...int) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldNotIn(FieldSortOrder, vs...))
}

// SortOrderGT applies the GT predicate on the "sort_order" field.
func SortOrderGT(v int) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldGT(FieldSortOrder, v))
}

// SortOrderGTE applies the GTE predicate on the "sort_order" field.
func SortOrderGTE(v int) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldGTE(FieldSortOrder, v))
}

// SortOrderLT applies the LT predicate on the "sort_order" field.
func SortOrderLT(v int) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldLT(FieldSortOrder, v))
}

// SortOrderLTE applies the LTE predicate on the "sort_order" field.
func SortOrderLTE(v int) predicate.VideoModel {
	return predicate.VideoModel(sql.FieldLTE(FieldSortOrder, v))
}

// HasTemplate applies the HasEdge predicate on the "template" edge.
func HasTemplate() predicate.VideoModel {
	return predicate.VideoModel(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TemplateTable, TemplateColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTemplateWith applies the HasEdge predicate on the "template" edge with a given conditions (other predicates).
func HasTemplateWith(preds ...predicate.VideoCallTemplate) predicate.VideoModel {
	return predicate.VideoModel(func(s *sql.Selector) {
		step := newTemplateStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTasks applies the HasEdge predicate on the "tasks" edge.
func HasTasks() predicate.VideoModel {
	return predicate.VideoModel(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, TasksTable, TasksColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTasksWith applies the HasEdge predicate on the "tasks" edge with a given conditions (other predicates).
func HasTasksWith(preds ...predicate.VideoGenerationTask) predicate.VideoModel {
	return predicate.VideoModel(func(s *sql.Selector) {
		step := newTasksStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.VideoModel) predicate.VideoModel {
	return predicate.VideoModel(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.VideoModel) predicate.VideoModel {
	return predicate.VideoModel(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.VideoModel) predicate.VideoModel {
	return predicate.VideoModel(sql.NotPredicates(p))
}
