// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/ccapi/ent/apikeygroupbinding"
	"github.com/Wei-Shaw/ccapi/ent/predicate"
)

// APIKeyGroupBindingDelete is the builder for deleting a APIKeyGroupBinding entity.
type APIKeyGroupBindingDelete struct {
	config
	hooks    []Hook
	mutation *APIKeyGroupBindingMutation
}

// Where appends a list predicates to the APIKeyGroupBindingDelete builder.
func (_d *APIKeyGroupBindingDelete) Where(ps ...predicate.APIKeyGroupBinding) *APIKeyGroupBindingDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *APIKeyGroupBindingDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *APIKeyGroupBindingDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *APIKeyGroupBindingDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(apikeygroupbinding.Table, sqlgraph.NewFieldSpec(apikeygroupbinding.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// APIKeyGroupBindingDeleteOne is the builder for deleting a single APIKeyGroupBinding entity.
type APIKeyGroupBindingDeleteOne struct {
	_d *APIKeyGroupBindingDelete
}

// Where appends a list predicates to the APIKeyGroupBindingDelete builder.
func (_d *APIKeyGroupBindingDeleteOne) Where(ps ...predicate.APIKeyGroupBinding) *APIKeyGroupBindingDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *APIKeyGroupBindingDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{apikeygroupbinding.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *APIKeyGroupBindingDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
