// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/ccapi/ent/apikey"
	"github.com/Wei-Shaw/ccapi/ent/apikeygroupbinding"
	"github.com/Wei-Shaw/ccapi/ent/group"
)

// APIKeyGroupBindingCreate is the builder for creating a APIKeyGroupBinding entity.
type APIKeyGroupBindingCreate struct {
	config
	mutation *APIKeyGroupBindingMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *APIKeyGroupBindingCreate) SetCreatedAt(v time.Time) *APIKeyGroupBindingCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *APIKeyGroupBindingCreate) SetNillableCreatedAt(v *time.Time) *APIKeyGroupBindingCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *APIKeyGroupBindingCreate) SetUpdatedAt(v time.Time) *APIKeyGroupBindingCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *APIKeyGroupBindingCreate) SetNillableUpdatedAt(v *time.Time) *APIKeyGroupBindingCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetAPIKeyID sets the "api_key_id" field.
func (_c *APIKeyGroupBindingCreate) SetAPIKeyID(v int64) *APIKeyGroupBindingCreate {
	_c.mutation.SetAPIKeyID(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *APIKeyGroupBindingCreate) SetGroupID(v int64) *APIKeyGroupBindingCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetPriority sets the "priority" field.
func (_c *APIKeyGroupBindingCreate) SetPriority(v int) *APIKeyGroupBindingCreate {
	_c.mutation.SetPriority(v)
	return _c
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_c *APIKeyGroupBindingCreate) SetNillablePriority(v *int) *APIKeyGroupBindingCreate {
	if v != nil {
		_c.SetPriority(*v)
	}
	return _c
}

// SetWeight sets the "weight" field.
func (_c *APIKeyGroupBindingCreate) SetWeight(v int) *APIKeyGroupBindingCreate {
	_c.mutation.SetWeight(v)
	return _c
}

// SetNillableWeight sets the "weight" field if the given value is not nil.
func (_c *APIKeyGroupBindingCreate) SetNillableWeight(v *int) *APIKeyGroupBindingCreate {
	if v != nil {
		_c.SetWeight(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *APIKeyGroupBindingCreate) SetEnabled(v bool) *APIKeyGroupBindingCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *APIKeyGroupBindingCreate) SetNillableEnabled(v *bool) *APIKeyGroupBindingCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetAPIKey sets the "api_key" edge to the APIKey entity.
func (_c *APIKeyGroupBindingCreate) SetAPIKey(v *APIKey) *APIKeyGroupBindingCreate {
	return _c.SetAPIKeyID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_c *APIKeyGroupBindingCreate) SetGroup(v *Group) *APIKeyGroupBindingCreate {
	return _c.SetGroupID(v.ID)
}

// Mutation returns the APIKeyGroupBindingMutation object of the builder.
func (_c *APIKeyGroupBindingCreate) Mutation() *APIKeyGroupBindingMutation {
	return _c.mutation
}

// Save creates the APIKeyGroupBinding in the database.
func (_c *APIKeyGroupBindingCreate) Save(ctx context.Context) (*APIKeyGroupBinding, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *APIKeyGroupBindingCreate) SaveX(ctx context.Context) *APIKeyGroupBinding {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *APIKeyGroupBindingCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *APIKeyGroupBindingCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *APIKeyGroupBindingCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := apikeygroupbinding.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := apikeygroupbinding.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Priority(); !ok {
		v := apikeygroupbinding.DefaultPriority
		_c.mutation.SetPriority(v)
	}
	if _, ok := _c.mutation.Weight(); !ok {
		v := apikeygroupbinding.DefaultWeight
		_c.mutation.SetWeight(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := apikeygroupbinding.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *APIKeyGroupBindingCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "APIKeyGroupBinding.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "APIKeyGroupBinding.updated_at"`)}
	}
	if _, ok := _c.mutation.APIKeyID(); !ok {
		return &ValidationError{Name: "api_key_id", err: errors.New(`ent: missing required field "APIKeyGroupBinding.api_key_id"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "APIKeyGroupBinding.group_id"`)}
	}
	if _, ok := _c.mutation.Priority(); !ok {
		return &ValidationError{Name: "priority", err: errors.New(`ent: missing required field "APIKeyGroupBinding.priority"`)}
	}
	if _, ok := _c.mutation.Weight(); !ok {
		return &ValidationError{Name: "weight", err: errors.New(`ent: missing required field "APIKeyGroupBinding.weight"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "APIKeyGroupBinding.enabled"`)}
	}
	if len(_c.mutation.APIKeyIDs()) == 0 {
		return &ValidationError{Name: "api_key", err: errors.New(`ent: missing required edge "APIKeyGroupBinding.api_key"`)}
	}
	if len(_c.mutation.GroupIDs()) == 0 {
		return &ValidationError{Name: "group", err: errors.New(`ent: missing required edge "APIKeyGroupBinding.group"`)}
	}
	return nil
}

func (_c *APIKeyGroupBindingCreate) sqlSave(ctx context.Context) (*APIKeyGroupBinding, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *APIKeyGroupBindingCreate) createSpec() (*APIKeyGroupBinding, *sqlgraph.CreateSpec) {
	var (
		_node = &APIKeyGroupBinding{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(apikeygroupbinding.Table, sqlgraph.NewFieldSpec(apikeygroupbinding.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(apikeygroupbinding.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(apikeygroupbinding.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Priority(); ok {
		_spec.SetField(apikeygroupbinding.FieldPriority, field.TypeInt, value)
		_node.Priority = value
	}
	if value, ok := _c.mutation.Weight(); ok {
		_spec.SetField(apikeygroupbinding.FieldWeight, field.TypeInt, value)
		_node.Weight = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(apikeygroupbinding.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if nodes := _c.mutation.APIKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apikeygroupbinding.APIKeyTable,
			Columns: []string{apikeygroupbinding.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.APIKeyID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apikeygroupbinding.GroupTable,
			Columns: []string{apikeygroupbinding.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.APIKeyGroupBinding.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.APIKeyGroupBindingUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *APIKeyGroupBindingCreate) OnConflict(opts ...sql.ConflictOption) *APIKeyGroupBindingUpsertOne {
	_c.conflict = opts
	return &APIKeyGroupBindingUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.APIKeyGroupBinding.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *APIKeyGroupBindingCreate) OnConflictColumns(columns ...string) *APIKeyGroupBindingUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &APIKeyGroupBindingUpsertOne{
		create: _c,
	}
}

type (
	// APIKeyGroupBindingUpsertOne is the builder for "upsert"-ing
	//  one APIKeyGroupBinding node.
	APIKeyGroupBindingUpsertOne struct {
		create *APIKeyGroupBindingCreate
	}

	// APIKeyGroupBindingUpsert is the "OnConflict" setter.
	APIKeyGroupBindingUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *APIKeyGroupBindingUpsert) SetUpdatedAt(v time.Time) *APIKeyGroupBindingUpsert {
	u.Set(apikeygroupbinding.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *APIKeyGroupBindingUpsert) UpdateUpdatedAt() *APIKeyGroupBindingUpsert {
	u.SetExcluded(apikeygroupbinding.FieldUpdatedAt)
	return u
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *APIKeyGroupBindingUpsert) SetAPIKeyID(v int64) *APIKeyGroupBindingUpsert {
	u.Set(apikeygroupbinding.FieldAPIKeyID, v)
	return u
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *APIKeyGroupBindingUpsert) UpdateAPIKeyID() *APIKeyGroupBindingUpsert {
	u.SetExcluded(apikeygroupbinding.FieldAPIKeyID)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *APIKeyGroupBindingUpsert) SetGroupID(v int64) *APIKeyGroupBindingUpsert {
	u.Set(apikeygroupbinding.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *APIKeyGroupBindingUpsert) UpdateGroupID() *APIKeyGroupBindingUpsert {
	u.SetExcluded(apikeygroupbinding.FieldGroupID)
	return u
}

// SetPriority sets the "priority" field.
func (u *APIKeyGroupBindingUpsert) SetPriority(v int) *APIKeyGroupBindingUpsert {
	u.Set(apikeygroupbinding.FieldPriority, v)
	return u
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *APIKeyGroupBindingUpsert) UpdatePriority() *APIKeyGroupBindingUpsert {
	u.SetExcluded(apikeygroupbinding.FieldPriority)
	return u
}

// AddPriority adds v to the "priority" field.
func (u *APIKeyGroupBindingUpsert) AddPriority(v int) *APIKeyGroupBindingUpsert {
	u.Add(apikeygroupbinding.FieldPriority, v)
	return u
}

// SetWeight sets the "weight" field.
func (u *APIKeyGroupBindingUpsert) SetWeight(v int) *APIKeyGroupBindingUpsert {
	u.Set(apikeygroupbinding.FieldWeight, v)
	return u
}

// UpdateWeight sets the "weight" field to the value that was provided on create.
func (u *APIKeyGroupBindingUpsert) UpdateWeight() *APIKeyGroupBindingUpsert {
	u.SetExcluded(apikeygroupbinding.FieldWeight)
	return u
}

// AddWeight adds v to the "weight" field.
func (u *APIKeyGroupBindingUpsert) AddWeight(v int) *APIKeyGroupBindingUpsert {
	u.Add(apikeygroupbinding.FieldWeight, v)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *APIKeyGroupBindingUpsert) SetEnabled(v bool) *APIKeyGroupBindingUpsert {
	u.Set(apikeygroupbinding.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *APIKeyGroupBindingUpsert) UpdateEnabled() *APIKeyGroupBindingUpsert {
	u.SetExcluded(apikeygroupbinding.FieldEnabled)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.APIKeyGroupBinding.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *APIKeyGroupBindingUpsertOne) UpdateNewValues() *APIKeyGroupBindingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(apikeygroupbinding.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.APIKeyGroupBinding.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *APIKeyGroupBindingUpsertOne) Ignore() *APIKeyGroupBindingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *APIKeyGroupBindingUpsertOne) DoNothing() *APIKeyGroupBindingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the APIKeyGroupBindingCreate.OnConflict
// documentation for more info.
func (u *APIKeyGroupBindingUpsertOne) Update(set func(*APIKeyGroupBindingUpsert)) *APIKeyGroupBindingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&APIKeyGroupBindingUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *APIKeyGroupBindingUpsertOne) SetUpdatedAt(v time.Time) *APIKeyGroupBindingUpsertOne {
	return u.Update(func(s *APIKeyGroupBindingUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *APIKeyGroupBindingUpsertOne) UpdateUpdatedAt() *APIKeyGroupBindingUpsertOne {
	return u.Update(func(s *APIKeyGroupBindingUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *APIKeyGroupBindingUpsertOne) SetAPIKeyID(v int64) *APIKeyGroupBindingUpsertOne {
	return u.Update(func(s *APIKeyGroupBindingUpsert) {
		s.SetAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *APIKeyGroupBindingUpsertOne) UpdateAPIKeyID() *APIKeyGroupBindingUpsertOne {
	return u.Update(func(s *APIKeyGroupBindingUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *APIKeyGroupBindingUpsertOne) SetGroupID(v int64) *APIKeyGroupBindingUpsertOne {
	return u.Update(func(s *APIKeyGroupBindingUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *APIKeyGroupBindingUpsertOne) UpdateGroupID() *APIKeyGroupBindingUpsertOne {
	return u.Update(func(s *APIKeyGroupBindingUpsert) {
		s.UpdateGroupID()
	})
}

// SetPriority sets the "priority" field.
func (u *APIKeyGroupBindingUpsertOne) SetPriority(v int) *APIKeyGroupBindingUpsertOne {
	return u.Update(func(s *APIKeyGroupBindingUpsert) {
		s.SetPriority(v)
	})
}

// AddPriority adds v to the "priority" field.
func (u *APIKeyGroupBindingUpsertOne) AddPriority(v int) *APIKeyGroupBindingUpsertOne {
	return u.Update(func(s *APIKeyGroupBindingUpsert) {
		s.AddPriority(v)
	})
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *APIKeyGroupBindingUpsertOne) UpdatePriority() *APIKeyGroupBindingUpsertOne {
	return u.Update(func(s *APIKeyGroupBindingUpsert) {
		s.UpdatePriority()
	})
}

// SetWeight sets the "weight" field.
func (u *APIKeyGroupBindingUpsertOne) SetWeight(v int) *APIKeyGroupBindingUpsertOne {
	return u.Update(func(s *APIKeyGroupBindingUpsert) {
		s.SetWeight(v)
	})
}

// AddWeight adds v to the "weight" field.
func (u *APIKeyGroupBindingUpsertOne) AddWeight(v int) *APIKeyGroupBindingUpsertOne {
	return u.Update(func(s *APIKeyGroupBindingUpsert) {
		s.AddWeight(v)
	})
}

// UpdateWeight sets the "weight" field to the value that was provided on create.
func (u *APIKeyGroupBindingUpsertOne) UpdateWeight() *APIKeyGroupBindingUpsertOne {
	return u.Update(func(s *APIKeyGroupBindingUpsert) {
		s.UpdateWeight()
	})
}

// SetEnabled sets the "enabled" field.
func (u *APIKeyGroupBindingUpsertOne) SetEnabled(v bool) *APIKeyGroupBindingUpsertOne {
	return u.Update(func(s *APIKeyGroupBindingUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *APIKeyGroupBindingUpsertOne) UpdateEnabled() *APIKeyGroupBindingUpsertOne {
	return u.Update(func(s *APIKeyGroupBindingUpsert) {
		s.UpdateEnabled()
	})
}

// Exec executes the query.
func (u *APIKeyGroupBindingUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for APIKeyGroupBindingCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *APIKeyGroupBindingUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *APIKeyGroupBindingUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *APIKeyGroupBindingUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// APIKeyGroupBindingCreateBulk is the builder for creating many APIKeyGroupBinding entities in bulk.
type APIKeyGroupBindingCreateBulk struct {
	config
	err      error
	builders []*APIKeyGroupBindingCreate
	conflict []sql.ConflictOption
}

// Save creates the APIKeyGroupBinding entities in the database.
func (_c *APIKeyGroupBindingCreateBulk) Save(ctx context.Context) ([]*APIKeyGroupBinding, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*APIKeyGroupBinding, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*APIKeyGroupBindingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *APIKeyGroupBindingCreateBulk) SaveX(ctx context.Context) []*APIKeyGroupBinding {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *APIKeyGroupBindingCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *APIKeyGroupBindingCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.APIKeyGroupBinding.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.APIKeyGroupBindingUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *APIKeyGroupBindingCreateBulk) OnConflict(opts ...sql.ConflictOption) *APIKeyGroupBindingUpsertBulk {
	_c.conflict = opts
	return &APIKeyGroupBindingUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.APIKeyGroupBinding.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *APIKeyGroupBindingCreateBulk) OnConflictColumns(columns ...string) *APIKeyGroupBindingUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &APIKeyGroupBindingUpsertBulk{
		create: _c,
	}
}

// APIKeyGroupBindingUpsertBulk is the builder for "upsert"-ing
// a bulk of APIKeyGroupBinding nodes.
type APIKeyGroupBindingUpsertBulk struct {
	create *APIKeyGroupBindingCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.APIKeyGroupBinding.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *APIKeyGroupBindingUpsertBulk) UpdateNewValues() *APIKeyGroupBindingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(apikeygroupbinding.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.APIKeyGroupBinding.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *APIKeyGroupBindingUpsertBulk) Ignore() *APIKeyGroupBindingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *APIKeyGroupBindingUpsertBulk) DoNothing() *APIKeyGroupBindingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the APIKeyGroupBindingCreateBulk.OnConflict
// documentation for more info.
func (u *APIKeyGroupBindingUpsertBulk) Update(set func(*APIKeyGroupBindingUpsert)) *APIKeyGroupBindingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&APIKeyGroupBindingUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *APIKeyGroupBindingUpsertBulk) SetUpdatedAt(v time.Time) *APIKeyGroupBindingUpsertBulk {
	return u.Update(func(s *APIKeyGroupBindingUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *APIKeyGroupBindingUpsertBulk) UpdateUpdatedAt() *APIKeyGroupBindingUpsertBulk {
	return u.Update(func(s *APIKeyGroupBindingUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *APIKeyGroupBindingUpsertBulk) SetAPIKeyID(v int64) *APIKeyGroupBindingUpsertBulk {
	return u.Update(func(s *APIKeyGroupBindingUpsert) {
		s.SetAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *APIKeyGroupBindingUpsertBulk) UpdateAPIKeyID() *APIKeyGroupBindingUpsertBulk {
	return u.Update(func(s *APIKeyGroupBindingUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *APIKeyGroupBindingUpsertBulk) SetGroupID(v int64) *APIKeyGroupBindingUpsertBulk {
	return u.Update(func(s *APIKeyGroupBindingUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *APIKeyGroupBindingUpsertBulk) UpdateGroupID() *APIKeyGroupBindingUpsertBulk {
	return u.Update(func(s *APIKeyGroupBindingUpsert) {
		s.UpdateGroupID()
	})
}

// SetPriority sets the "priority" field.
func (u *APIKeyGroupBindingUpsertBulk) SetPriority(v int) *APIKeyGroupBindingUpsertBulk {
	return u.Update(func(s *APIKeyGroupBindingUpsert) {
		s.SetPriority(v)
	})
}

// AddPriority adds v to the "priority" field.
func (u *APIKeyGroupBindingUpsertBulk) AddPriority(v int) *APIKeyGroupBindingUpsertBulk {
	return u.Update(func(s *APIKeyGroupBindingUpsert) {
		s.AddPriority(v)
	})
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *APIKeyGroupBindingUpsertBulk) UpdatePriority() *APIKeyGroupBindingUpsertBulk {
	return u.Update(func(s *APIKeyGroupBindingUpsert) {
		s.UpdatePriority()
	})
}

// SetWeight sets the "weight" field.
func (u *APIKeyGroupBindingUpsertBulk) SetWeight(v int) *APIKeyGroupBindingUpsertBulk {
	return u.Update(func(s *APIKeyGroupBindingUpsert) {
		s.SetWeight(v)
	})
}

// AddWeight adds v to the "weight" field.
func (u *APIKeyGroupBindingUpsertBulk) AddWeight(v int) *APIKeyGroupBindingUpsertBulk {
	return u.Update(func(s *APIKeyGroupBindingUpsert) {
		s.AddWeight(v)
	})
}

// UpdateWeight sets the "weight" field to the value that was provided on create.
func (u *APIKeyGroupBindingUpsertBulk) UpdateWeight() *APIKeyGroupBindingUpsertBulk {
	return u.Update(func(s *APIKeyGroupBindingUpsert) {
		s.UpdateWeight()
	})
}

// SetEnabled sets the "enabled" field.
func (u *APIKeyGroupBindingUpsertBulk) SetEnabled(v bool) *APIKeyGroupBindingUpsertBulk {
	return u.Update(func(s *APIKeyGroupBindingUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *APIKeyGroupBindingUpsertBulk) UpdateEnabled() *APIKeyGroupBindingUpsertBulk {
	return u.Update(func(s *APIKeyGroupBindingUpsert) {
		s.UpdateEnabled()
	})
}

// Exec executes the query.
func (u *APIKeyGroupBindingUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the APIKeyGroupBindingCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for APIKeyGroupBindingCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *APIKeyGroupBindingUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
