// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/ccapi/ent/apikey"
	"github.com/Wei-Shaw/ccapi/ent/apikeygroupbinding"
	"github.com/Wei-Shaw/ccapi/ent/group"
	"github.com/Wei-Shaw/ccapi/ent/predicate"
)

// APIKeyGroupBindingUpdate is the builder for updating APIKeyGroupBinding entities.
type APIKeyGroupBindingUpdate struct {
	config
	hooks    []Hook
	mutation *APIKeyGroupBindingMutation
}

// Where appends a list predicates to the APIKeyGroupBindingUpdate builder.
func (_u *APIKeyGroupBindingUpdate) Where(ps ...predicate.APIKeyGroupBinding) *APIKeyGroupBindingUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *APIKeyGroupBindingUpdate) SetUpdatedAt(v time.Time) *APIKeyGroupBindingUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *APIKeyGroupBindingUpdate) SetAPIKeyID(v int64) *APIKeyGroupBindingUpdate {
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *APIKeyGroupBindingUpdate) SetNillableAPIKeyID(v *int64) *APIKeyGroupBindingUpdate {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *APIKeyGroupBindingUpdate) SetGroupID(v int64) *APIKeyGroupBindingUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *APIKeyGroupBindingUpdate) SetNillableGroupID(v *int64) *APIKeyGroupBindingUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *APIKeyGroupBindingUpdate) SetPriority(v int) *APIKeyGroupBindingUpdate {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *APIKeyGroupBindingUpdate) SetNillablePriority(v *int) *APIKeyGroupBindingUpdate {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *APIKeyGroupBindingUpdate) AddPriority(v int) *APIKeyGroupBindingUpdate {
	_u.mutation.AddPriority(v)
	return _u
}

// SetWeight sets the "weight" field.
func (_u *APIKeyGroupBindingUpdate) SetWeight(v int) *APIKeyGroupBindingUpdate {
	_u.mutation.ResetWeight()
	_u.mutation.SetWeight(v)
	return _u
}

// SetNillableWeight sets the "weight" field if the given value is not nil.
func (_u *APIKeyGroupBindingUpdate) SetNillableWeight(v *int) *APIKeyGroupBindingUpdate {
	if v != nil {
		_u.SetWeight(*v)
	}
	return _u
}

// AddWeight adds value to the "weight" field.
func (_u *APIKeyGroupBindingUpdate) AddWeight(v int) *APIKeyGroupBindingUpdate {
	_u.mutation.AddWeight(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *APIKeyGroupBindingUpdate) SetEnabled(v bool) *APIKeyGroupBindingUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *APIKeyGroupBindingUpdate) SetNillableEnabled(v *bool) *APIKeyGroupBindingUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetAPIKey sets the "api_key" edge to the APIKey entity.
func (_u *APIKeyGroupBindingUpdate) SetAPIKey(v *APIKey) *APIKeyGroupBindingUpdate {
	return _u.SetAPIKeyID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *APIKeyGroupBindingUpdate) SetGroup(v *Group) *APIKeyGroupBindingUpdate {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the APIKeyGroupBindingMutation object of the builder.
func (_u *APIKeyGroupBindingUpdate) Mutation() *APIKeyGroupBindingMutation {
	return _u.mutation
}

// ClearAPIKey clears the "api_key" edge to the APIKey entity.
func (_u *APIKeyGroupBindingUpdate) ClearAPIKey() *APIKeyGroupBindingUpdate {
	_u.mutation.ClearAPIKey()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *APIKeyGroupBindingUpdate) ClearGroup() *APIKeyGroupBindingUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *APIKeyGroupBindingUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *APIKeyGroupBindingUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *APIKeyGroupBindingUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *APIKeyGroupBindingUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *APIKeyGroupBindingUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := apikeygroupbinding.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *APIKeyGroupBindingUpdate) check() error {
	if _u.mutation.APIKeyCleared() && len(_u.mutation.APIKeyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "APIKeyGroupBinding.api_key"`)
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "APIKeyGroupBinding.group"`)
	}
	return nil
}

func (_u *APIKeyGroupBindingUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(apikeygroupbinding.Table, apikeygroupbinding.Columns, sqlgraph.NewFieldSpec(apikeygroupbinding.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(apikeygroupbinding.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(apikeygroupbinding.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(apikeygroupbinding.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Weight(); ok {
		_spec.SetField(apikeygroupbinding.FieldWeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWeight(); ok {
		_spec.AddField(apikeygroupbinding.FieldWeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(apikeygroupbinding.FieldEnabled, field.TypeBool, value)
	}
	if _u.mutation.APIKeyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apikeygroupbinding.APIKeyTable,
			Columns: []string{apikeygroupbinding.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APIKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apikeygroupbinding.APIKeyTable,
			Columns: []string{apikeygroupbinding.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apikeygroupbinding.GroupTable,
			Columns: []string{apikeygroupbinding.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apikeygroupbinding.GroupTable,
			Columns: []string{apikeygroupbinding.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{apikeygroupbinding.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// APIKeyGroupBindingUpdateOne is the builder for updating a single APIKeyGroupBinding entity.
type APIKeyGroupBindingUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *APIKeyGroupBindingMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *APIKeyGroupBindingUpdateOne) SetUpdatedAt(v time.Time) *APIKeyGroupBindingUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *APIKeyGroupBindingUpdateOne) SetAPIKeyID(v int64) *APIKeyGroupBindingUpdateOne {
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *APIKeyGroupBindingUpdateOne) SetNillableAPIKeyID(v *int64) *APIKeyGroupBindingUpdateOne {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *APIKeyGroupBindingUpdateOne) SetGroupID(v int64) *APIKeyGroupBindingUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *APIKeyGroupBindingUpdateOne) SetNillableGroupID(v *int64) *APIKeyGroupBindingUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *APIKeyGroupBindingUpdateOne) SetPriority(v int) *APIKeyGroupBindingUpdateOne {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *APIKeyGroupBindingUpdateOne) SetNillablePriority(v *int) *APIKeyGroupBindingUpdateOne {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *APIKeyGroupBindingUpdateOne) AddPriority(v int) *APIKeyGroupBindingUpdateOne {
	_u.mutation.AddPriority(v)
	return _u
}

// SetWeight sets the "weight" field.
func (_u *APIKeyGroupBindingUpdateOne) SetWeight(v int) *APIKeyGroupBindingUpdateOne {
	_u.mutation.ResetWeight()
	_u.mutation.SetWeight(v)
	return _u
}

// SetNillableWeight sets the "weight" field if the given value is not nil.
func (_u *APIKeyGroupBindingUpdateOne) SetNillableWeight(v *int) *APIKeyGroupBindingUpdateOne {
	if v != nil {
		_u.SetWeight(*v)
	}
	return _u
}

// AddWeight adds value to the "weight" field.
func (_u *APIKeyGroupBindingUpdateOne) AddWeight(v int) *APIKeyGroupBindingUpdateOne {
	_u.mutation.AddWeight(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *APIKeyGroupBindingUpdateOne) SetEnabled(v bool) *APIKeyGroupBindingUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *APIKeyGroupBindingUpdateOne) SetNillableEnabled(v *bool) *APIKeyGroupBindingUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetAPIKey sets the "api_key" edge to the APIKey entity.
func (_u *APIKeyGroupBindingUpdateOne) SetAPIKey(v *APIKey) *APIKeyGroupBindingUpdateOne {
	return _u.SetAPIKeyID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *APIKeyGroupBindingUpdateOne) SetGroup(v *Group) *APIKeyGroupBindingUpdateOne {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the APIKeyGroupBindingMutation object of the builder.
func (_u *APIKeyGroupBindingUpdateOne) Mutation() *APIKeyGroupBindingMutation {
	return _u.mutation
}

// ClearAPIKey clears the "api_key" edge to the APIKey entity.
func (_u *APIKeyGroupBindingUpdateOne) ClearAPIKey() *APIKeyGroupBindingUpdateOne {
	_u.mutation.ClearAPIKey()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *APIKeyGroupBindingUpdateOne) ClearGroup() *APIKeyGroupBindingUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// Where appends a list predicates to the APIKeyGroupBindingUpdate builder.
func (_u *APIKeyGroupBindingUpdateOne) Where(ps ...predicate.APIKeyGroupBinding) *APIKeyGroupBindingUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *APIKeyGroupBindingUpdateOne) Select(field string, fields ...string) *APIKeyGroupBindingUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated APIKeyGroupBinding entity.
func (_u *APIKeyGroupBindingUpdateOne) Save(ctx context.Context) (*APIKeyGroupBinding, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *APIKeyGroupBindingUpdateOne) SaveX(ctx context.Context) *APIKeyGroupBinding {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *APIKeyGroupBindingUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *APIKeyGroupBindingUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *APIKeyGroupBindingUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := apikeygroupbinding.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *APIKeyGroupBindingUpdateOne) check() error {
	if _u.mutation.APIKeyCleared() && len(_u.mutation.APIKeyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "APIKeyGroupBinding.api_key"`)
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "APIKeyGroupBinding.group"`)
	}
	return nil
}

func (_u *APIKeyGroupBindingUpdateOne) sqlSave(ctx context.Context) (_node *APIKeyGroupBinding, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(apikeygroupbinding.Table, apikeygroupbinding.Columns, sqlgraph.NewFieldSpec(apikeygroupbinding.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "APIKeyGroupBinding.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, apikeygroupbinding.FieldID)
		for _, f := range fields {
			if !apikeygroupbinding.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != apikeygroupbinding.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(apikeygroupbinding.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(apikeygroupbinding.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(apikeygroupbinding.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Weight(); ok {
		_spec.SetField(apikeygroupbinding.FieldWeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWeight(); ok {
		_spec.AddField(apikeygroupbinding.FieldWeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(apikeygroupbinding.FieldEnabled, field.TypeBool, value)
	}
	if _u.mutation.APIKeyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apikeygroupbinding.APIKeyTable,
			Columns: []string{apikeygroupbinding.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APIKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apikeygroupbinding.APIKeyTable,
			Columns: []string{apikeygroupbinding.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apikeygroupbinding.GroupTable,
			Columns: []string{apikeygroupbinding.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apikeygroupbinding.GroupTable,
			Columns: []string{apikeygroupbinding.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &APIKeyGroupBinding{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{apikeygroupbinding.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
