// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/videocalltemplate"
)

// VideoCallTemplate is the model entity for the VideoCallTemplate schema.
type VideoCallTemplate struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// CreateMethod holds the value of the "create_method" field.
	CreateMethod string `json:"create_method,omitempty"`
	// CreatePath holds the value of the "create_path" field.
	CreatePath string `json:"create_path,omitempty"`
	// QueryMethod holds the value of the "query_method" field.
	QueryMethod string `json:"query_method,omitempty"`
	// QueryPath holds the value of the "query_path" field.
	QueryPath string `json:"query_path,omitempty"`
	// ContentMethod holds the value of the "content_method" field.
	ContentMethod *string `json:"content_method,omitempty"`
	// ContentPath holds the value of the "content_path" field.
	ContentPath *string `json:"content_path,omitempty"`
	// CancelMethod holds the value of the "cancel_method" field.
	CancelMethod *string `json:"cancel_method,omitempty"`
	// CancelPath holds the value of the "cancel_path" field.
	CancelPath *string `json:"cancel_path,omitempty"`
	// StatusMapping holds the value of the "status_mapping" field.
	StatusMapping map[string]string `json:"status_mapping,omitempty"`
	// ResultMapping holds the value of the "result_mapping" field.
	ResultMapping map[string]string `json:"result_mapping,omitempty"`
	// ErrorMapping holds the value of the "error_mapping" field.
	ErrorMapping map[string]string `json:"error_mapping,omitempty"`
	// PollConfig holds the value of the "poll_config" field.
	PollConfig map[string]interface{} `json:"poll_config,omitempty"`
	// TimeoutConfig holds the value of the "timeout_config" field.
	TimeoutConfig map[string]interface{} `json:"timeout_config,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the VideoCallTemplateQuery when eager-loading is set.
	Edges        VideoCallTemplateEdges `json:"edges"`
	selectValues sql.SelectValues
}

// VideoCallTemplateEdges holds the relations/edges for other nodes in the graph.
type VideoCallTemplateEdges struct {
	// VideoModels holds the value of the video_models edge.
	VideoModels []*VideoModel `json:"video_models,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// VideoModelsOrErr returns the VideoModels value or an error if the edge
// was not loaded in eager-loading.
func (e VideoCallTemplateEdges) VideoModelsOrErr() ([]*VideoModel, error) {
	if e.loadedTypes[0] {
		return e.VideoModels, nil
	}
	return nil, &NotLoadedError{edge: "video_models"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*VideoCallTemplate) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case videocalltemplate.FieldStatusMapping, videocalltemplate.FieldResultMapping, videocalltemplate.FieldErrorMapping, videocalltemplate.FieldPollConfig, videocalltemplate.FieldTimeoutConfig:
			values[i] = new([]byte)
		case videocalltemplate.FieldID:
			values[i] = new(sql.NullInt64)
		case videocalltemplate.FieldName, videocalltemplate.FieldCreateMethod, videocalltemplate.FieldCreatePath, videocalltemplate.FieldQueryMethod, videocalltemplate.FieldQueryPath, videocalltemplate.FieldContentMethod, videocalltemplate.FieldContentPath, videocalltemplate.FieldCancelMethod, videocalltemplate.FieldCancelPath, videocalltemplate.FieldStatus:
			values[i] = new(sql.NullString)
		case videocalltemplate.FieldCreatedAt, videocalltemplate.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the VideoCallTemplate fields.
func (_m *VideoCallTemplate) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case videocalltemplate.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case videocalltemplate.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case videocalltemplate.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case videocalltemplate.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case videocalltemplate.FieldCreateMethod:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field create_method", values[i])
			} else if value.Valid {
				_m.CreateMethod = value.String
			}
		case videocalltemplate.FieldCreatePath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field create_path", values[i])
			} else if value.Valid {
				_m.CreatePath = value.String
			}
		case videocalltemplate.FieldQueryMethod:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field query_method", values[i])
			} else if value.Valid {
				_m.QueryMethod = value.String
			}
		case videocalltemplate.FieldQueryPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field query_path", values[i])
			} else if value.Valid {
				_m.QueryPath = value.String
			}
		case videocalltemplate.FieldContentMethod:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content_method", values[i])
			} else if value.Valid {
				_m.ContentMethod = new(string)
				*_m.ContentMethod = value.String
			}
		case videocalltemplate.FieldContentPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content_path", values[i])
			} else if value.Valid {
				_m.ContentPath = new(string)
				*_m.ContentPath = value.String
			}
		case videocalltemplate.FieldCancelMethod:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cancel_method", values[i])
			} else if value.Valid {
				_m.CancelMethod = new(string)
				*_m.CancelMethod = value.String
			}
		case videocalltemplate.FieldCancelPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cancel_path", values[i])
			} else if value.Valid {
				_m.CancelPath = new(string)
				*_m.CancelPath = value.String
			}
		case videocalltemplate.FieldStatusMapping:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field status_mapping", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.StatusMapping); err != nil {
					return fmt.Errorf("unmarshal field status_mapping: %w", err)
				}
			}
		case videocalltemplate.FieldResultMapping:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field result_mapping", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ResultMapping); err != nil {
					return fmt.Errorf("unmarshal field result_mapping: %w", err)
				}
			}
		case videocalltemplate.FieldErrorMapping:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field error_mapping", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ErrorMapping); err != nil {
					return fmt.Errorf("unmarshal field error_mapping: %w", err)
				}
			}
		case videocalltemplate.FieldPollConfig:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field poll_config", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.PollConfig); err != nil {
					return fmt.Errorf("unmarshal field poll_config: %w", err)
				}
			}
		case videocalltemplate.FieldTimeoutConfig:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field timeout_config", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.TimeoutConfig); err != nil {
					return fmt.Errorf("unmarshal field timeout_config: %w", err)
				}
			}
		case videocalltemplate.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the VideoCallTemplate.
// This includes values selected through modifiers, order, etc.
func (_m *VideoCallTemplate) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryVideoModels queries the "video_models" edge of the VideoCallTemplate entity.
func (_m *VideoCallTemplate) QueryVideoModels() *VideoModelQuery {
	return NewVideoCallTemplateClient(_m.config).QueryVideoModels(_m)
}

// Update returns a builder for updating this VideoCallTemplate.
// Note that you need to call VideoCallTemplate.Unwrap() before calling this method if this VideoCallTemplate
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *VideoCallTemplate) Update() *VideoCallTemplateUpdateOne {
	return NewVideoCallTemplateClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the VideoCallTemplate entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *VideoCallTemplate) Unwrap() *VideoCallTemplate {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: VideoCallTemplate is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *VideoCallTemplate) String() string {
	var builder strings.Builder
	builder.WriteString("VideoCallTemplate(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("create_method=")
	builder.WriteString(_m.CreateMethod)
	builder.WriteString(", ")
	builder.WriteString("create_path=")
	builder.WriteString(_m.CreatePath)
	builder.WriteString(", ")
	builder.WriteString("query_method=")
	builder.WriteString(_m.QueryMethod)
	builder.WriteString(", ")
	builder.WriteString("query_path=")
	builder.WriteString(_m.QueryPath)
	builder.WriteString(", ")
	if v := _m.ContentMethod; v != nil {
		builder.WriteString("content_method=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ContentPath; v != nil {
		builder.WriteString("content_path=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.CancelMethod; v != nil {
		builder.WriteString("cancel_method=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.CancelPath; v != nil {
		builder.WriteString("cancel_path=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("status_mapping=")
	builder.WriteString(fmt.Sprintf("%v", _m.StatusMapping))
	builder.WriteString(", ")
	builder.WriteString("result_mapping=")
	builder.WriteString(fmt.Sprintf("%v", _m.ResultMapping))
	builder.WriteString(", ")
	builder.WriteString("error_mapping=")
	builder.WriteString(fmt.Sprintf("%v", _m.ErrorMapping))
	builder.WriteString(", ")
	builder.WriteString("poll_config=")
	builder.WriteString(fmt.Sprintf("%v", _m.PollConfig))
	builder.WriteString(", ")
	builder.WriteString("timeout_config=")
	builder.WriteString(fmt.Sprintf("%v", _m.TimeoutConfig))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteByte(')')
	return builder.String()
}

// VideoCallTemplates is a parsable slice of VideoCallTemplate.
type VideoCallTemplates []*VideoCallTemplate
