// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/videocalltemplate"
	"github.com/Wei-Shaw/sub2api/ent/videomodel"
)

// VideoCallTemplateCreate is the builder for creating a VideoCallTemplate entity.
type VideoCallTemplateCreate struct {
	config
	mutation *VideoCallTemplateMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *VideoCallTemplateCreate) SetCreatedAt(v time.Time) *VideoCallTemplateCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *VideoCallTemplateCreate) SetNillableCreatedAt(v *time.Time) *VideoCallTemplateCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *VideoCallTemplateCreate) SetUpdatedAt(v time.Time) *VideoCallTemplateCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *VideoCallTemplateCreate) SetNillableUpdatedAt(v *time.Time) *VideoCallTemplateCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *VideoCallTemplateCreate) SetName(v string) *VideoCallTemplateCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetCreateMethod sets the "create_method" field.
func (_c *VideoCallTemplateCreate) SetCreateMethod(v string) *VideoCallTemplateCreate {
	_c.mutation.SetCreateMethod(v)
	return _c
}

// SetNillableCreateMethod sets the "create_method" field if the given value is not nil.
func (_c *VideoCallTemplateCreate) SetNillableCreateMethod(v *string) *VideoCallTemplateCreate {
	if v != nil {
		_c.SetCreateMethod(*v)
	}
	return _c
}

// SetCreatePath sets the "create_path" field.
func (_c *VideoCallTemplateCreate) SetCreatePath(v string) *VideoCallTemplateCreate {
	_c.mutation.SetCreatePath(v)
	return _c
}

// SetQueryMethod sets the "query_method" field.
func (_c *VideoCallTemplateCreate) SetQueryMethod(v string) *VideoCallTemplateCreate {
	_c.mutation.SetQueryMethod(v)
	return _c
}

// SetNillableQueryMethod sets the "query_method" field if the given value is not nil.
func (_c *VideoCallTemplateCreate) SetNillableQueryMethod(v *string) *VideoCallTemplateCreate {
	if v != nil {
		_c.SetQueryMethod(*v)
	}
	return _c
}

// SetQueryPath sets the "query_path" field.
func (_c *VideoCallTemplateCreate) SetQueryPath(v string) *VideoCallTemplateCreate {
	_c.mutation.SetQueryPath(v)
	return _c
}

// SetContentMethod sets the "content_method" field.
func (_c *VideoCallTemplateCreate) SetContentMethod(v string) *VideoCallTemplateCreate {
	_c.mutation.SetContentMethod(v)
	return _c
}

// SetNillableContentMethod sets the "content_method" field if the given value is not nil.
func (_c *VideoCallTemplateCreate) SetNillableContentMethod(v *string) *VideoCallTemplateCreate {
	if v != nil {
		_c.SetContentMethod(*v)
	}
	return _c
}

// SetContentPath sets the "content_path" field.
func (_c *VideoCallTemplateCreate) SetContentPath(v string) *VideoCallTemplateCreate {
	_c.mutation.SetContentPath(v)
	return _c
}

// SetNillableContentPath sets the "content_path" field if the given value is not nil.
func (_c *VideoCallTemplateCreate) SetNillableContentPath(v *string) *VideoCallTemplateCreate {
	if v != nil {
		_c.SetContentPath(*v)
	}
	return _c
}

// SetCancelMethod sets the "cancel_method" field.
func (_c *VideoCallTemplateCreate) SetCancelMethod(v string) *VideoCallTemplateCreate {
	_c.mutation.SetCancelMethod(v)
	return _c
}

// SetNillableCancelMethod sets the "cancel_method" field if the given value is not nil.
func (_c *VideoCallTemplateCreate) SetNillableCancelMethod(v *string) *VideoCallTemplateCreate {
	if v != nil {
		_c.SetCancelMethod(*v)
	}
	return _c
}

// SetCancelPath sets the "cancel_path" field.
func (_c *VideoCallTemplateCreate) SetCancelPath(v string) *VideoCallTemplateCreate {
	_c.mutation.SetCancelPath(v)
	return _c
}

// SetNillableCancelPath sets the "cancel_path" field if the given value is not nil.
func (_c *VideoCallTemplateCreate) SetNillableCancelPath(v *string) *VideoCallTemplateCreate {
	if v != nil {
		_c.SetCancelPath(*v)
	}
	return _c
}

// SetStatusMapping sets the "status_mapping" field.
func (_c *VideoCallTemplateCreate) SetStatusMapping(v map[string]string) *VideoCallTemplateCreate {
	_c.mutation.SetStatusMapping(v)
	return _c
}

// SetResultMapping sets the "result_mapping" field.
func (_c *VideoCallTemplateCreate) SetResultMapping(v map[string]string) *VideoCallTemplateCreate {
	_c.mutation.SetResultMapping(v)
	return _c
}

// SetErrorMapping sets the "error_mapping" field.
func (_c *VideoCallTemplateCreate) SetErrorMapping(v map[string]string) *VideoCallTemplateCreate {
	_c.mutation.SetErrorMapping(v)
	return _c
}

// SetPollConfig sets the "poll_config" field.
func (_c *VideoCallTemplateCreate) SetPollConfig(v map[string]interface{}) *VideoCallTemplateCreate {
	_c.mutation.SetPollConfig(v)
	return _c
}

// SetTimeoutConfig sets the "timeout_config" field.
func (_c *VideoCallTemplateCreate) SetTimeoutConfig(v map[string]interface{}) *VideoCallTemplateCreate {
	_c.mutation.SetTimeoutConfig(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *VideoCallTemplateCreate) SetStatus(v string) *VideoCallTemplateCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *VideoCallTemplateCreate) SetNillableStatus(v *string) *VideoCallTemplateCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// AddVideoModelIDs adds the "video_models" edge to the VideoModel entity by IDs.
func (_c *VideoCallTemplateCreate) AddVideoModelIDs(ids ...int64) *VideoCallTemplateCreate {
	_c.mutation.AddVideoModelIDs(ids...)
	return _c
}

// AddVideoModels adds the "video_models" edges to the VideoModel entity.
func (_c *VideoCallTemplateCreate) AddVideoModels(v ...*VideoModel) *VideoCallTemplateCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddVideoModelIDs(ids...)
}

// Mutation returns the VideoCallTemplateMutation object of the builder.
func (_c *VideoCallTemplateCreate) Mutation() *VideoCallTemplateMutation {
	return _c.mutation
}

// Save creates the VideoCallTemplate in the database.
func (_c *VideoCallTemplateCreate) Save(ctx context.Context) (*VideoCallTemplate, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *VideoCallTemplateCreate) SaveX(ctx context.Context) *VideoCallTemplate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VideoCallTemplateCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VideoCallTemplateCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *VideoCallTemplateCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := videocalltemplate.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := videocalltemplate.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.CreateMethod(); !ok {
		v := videocalltemplate.DefaultCreateMethod
		_c.mutation.SetCreateMethod(v)
	}
	if _, ok := _c.mutation.QueryMethod(); !ok {
		v := videocalltemplate.DefaultQueryMethod
		_c.mutation.SetQueryMethod(v)
	}
	if _, ok := _c.mutation.StatusMapping(); !ok {
		v := videocalltemplate.DefaultStatusMapping
		_c.mutation.SetStatusMapping(v)
	}
	if _, ok := _c.mutation.ResultMapping(); !ok {
		v := videocalltemplate.DefaultResultMapping
		_c.mutation.SetResultMapping(v)
	}
	if _, ok := _c.mutation.ErrorMapping(); !ok {
		v := videocalltemplate.DefaultErrorMapping
		_c.mutation.SetErrorMapping(v)
	}
	if _, ok := _c.mutation.PollConfig(); !ok {
		v := videocalltemplate.DefaultPollConfig()
		_c.mutation.SetPollConfig(v)
	}
	if _, ok := _c.mutation.TimeoutConfig(); !ok {
		v := videocalltemplate.DefaultTimeoutConfig()
		_c.mutation.SetTimeoutConfig(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := videocalltemplate.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *VideoCallTemplateCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "VideoCallTemplate.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "VideoCallTemplate.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "VideoCallTemplate.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := videocalltemplate.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "VideoCallTemplate.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreateMethod(); !ok {
		return &ValidationError{Name: "create_method", err: errors.New(`ent: missing required field "VideoCallTemplate.create_method"`)}
	}
	if v, ok := _c.mutation.CreateMethod(); ok {
		if err := videocalltemplate.CreateMethodValidator(v); err != nil {
			return &ValidationError{Name: "create_method", err: fmt.Errorf(`ent: validator failed for field "VideoCallTemplate.create_method": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatePath(); !ok {
		return &ValidationError{Name: "create_path", err: errors.New(`ent: missing required field "VideoCallTemplate.create_path"`)}
	}
	if v, ok := _c.mutation.CreatePath(); ok {
		if err := videocalltemplate.CreatePathValidator(v); err != nil {
			return &ValidationError{Name: "create_path", err: fmt.Errorf(`ent: validator failed for field "VideoCallTemplate.create_path": %w`, err)}
		}
	}
	if _, ok := _c.mutation.QueryMethod(); !ok {
		return &ValidationError{Name: "query_method", err: errors.New(`ent: missing required field "VideoCallTemplate.query_method"`)}
	}
	if v, ok := _c.mutation.QueryMethod(); ok {
		if err := videocalltemplate.QueryMethodValidator(v); err != nil {
			return &ValidationError{Name: "query_method", err: fmt.Errorf(`ent: validator failed for field "VideoCallTemplate.query_method": %w`, err)}
		}
	}
	if _, ok := _c.mutation.QueryPath(); !ok {
		return &ValidationError{Name: "query_path", err: errors.New(`ent: missing required field "VideoCallTemplate.query_path"`)}
	}
	if v, ok := _c.mutation.QueryPath(); ok {
		if err := videocalltemplate.QueryPathValidator(v); err != nil {
			return &ValidationError{Name: "query_path", err: fmt.Errorf(`ent: validator failed for field "VideoCallTemplate.query_path": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ContentMethod(); ok {
		if err := videocalltemplate.ContentMethodValidator(v); err != nil {
			return &ValidationError{Name: "content_method", err: fmt.Errorf(`ent: validator failed for field "VideoCallTemplate.content_method": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ContentPath(); ok {
		if err := videocalltemplate.ContentPathValidator(v); err != nil {
			return &ValidationError{Name: "content_path", err: fmt.Errorf(`ent: validator failed for field "VideoCallTemplate.content_path": %w`, err)}
		}
	}
	if v, ok := _c.mutation.CancelMethod(); ok {
		if err := videocalltemplate.CancelMethodValidator(v); err != nil {
			return &ValidationError{Name: "cancel_method", err: fmt.Errorf(`ent: validator failed for field "VideoCallTemplate.cancel_method": %w`, err)}
		}
	}
	if v, ok := _c.mutation.CancelPath(); ok {
		if err := videocalltemplate.CancelPathValidator(v); err != nil {
			return &ValidationError{Name: "cancel_path", err: fmt.Errorf(`ent: validator failed for field "VideoCallTemplate.cancel_path": %w`, err)}
		}
	}
	if _, ok := _c.mutation.StatusMapping(); !ok {
		return &ValidationError{Name: "status_mapping", err: errors.New(`ent: missing required field "VideoCallTemplate.status_mapping"`)}
	}
	if _, ok := _c.mutation.ResultMapping(); !ok {
		return &ValidationError{Name: "result_mapping", err: errors.New(`ent: missing required field "VideoCallTemplate.result_mapping"`)}
	}
	if _, ok := _c.mutation.ErrorMapping(); !ok {
		return &ValidationError{Name: "error_mapping", err: errors.New(`ent: missing required field "VideoCallTemplate.error_mapping"`)}
	}
	if _, ok := _c.mutation.PollConfig(); !ok {
		return &ValidationError{Name: "poll_config", err: errors.New(`ent: missing required field "VideoCallTemplate.poll_config"`)}
	}
	if _, ok := _c.mutation.TimeoutConfig(); !ok {
		return &ValidationError{Name: "timeout_config", err: errors.New(`ent: missing required field "VideoCallTemplate.timeout_config"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "VideoCallTemplate.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := videocalltemplate.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "VideoCallTemplate.status": %w`, err)}
		}
	}
	return nil
}

func (_c *VideoCallTemplateCreate) sqlSave(ctx context.Context) (*VideoCallTemplate, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *VideoCallTemplateCreate) createSpec() (*VideoCallTemplate, *sqlgraph.CreateSpec) {
	var (
		_node = &VideoCallTemplate{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(videocalltemplate.Table, sqlgraph.NewFieldSpec(videocalltemplate.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(videocalltemplate.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(videocalltemplate.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(videocalltemplate.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.CreateMethod(); ok {
		_spec.SetField(videocalltemplate.FieldCreateMethod, field.TypeString, value)
		_node.CreateMethod = value
	}
	if value, ok := _c.mutation.CreatePath(); ok {
		_spec.SetField(videocalltemplate.FieldCreatePath, field.TypeString, value)
		_node.CreatePath = value
	}
	if value, ok := _c.mutation.QueryMethod(); ok {
		_spec.SetField(videocalltemplate.FieldQueryMethod, field.TypeString, value)
		_node.QueryMethod = value
	}
	if value, ok := _c.mutation.QueryPath(); ok {
		_spec.SetField(videocalltemplate.FieldQueryPath, field.TypeString, value)
		_node.QueryPath = value
	}
	if value, ok := _c.mutation.ContentMethod(); ok {
		_spec.SetField(videocalltemplate.FieldContentMethod, field.TypeString, value)
		_node.ContentMethod = &value
	}
	if value, ok := _c.mutation.ContentPath(); ok {
		_spec.SetField(videocalltemplate.FieldContentPath, field.TypeString, value)
		_node.ContentPath = &value
	}
	if value, ok := _c.mutation.CancelMethod(); ok {
		_spec.SetField(videocalltemplate.FieldCancelMethod, field.TypeString, value)
		_node.CancelMethod = &value
	}
	if value, ok := _c.mutation.CancelPath(); ok {
		_spec.SetField(videocalltemplate.FieldCancelPath, field.TypeString, value)
		_node.CancelPath = &value
	}
	if value, ok := _c.mutation.StatusMapping(); ok {
		_spec.SetField(videocalltemplate.FieldStatusMapping, field.TypeJSON, value)
		_node.StatusMapping = value
	}
	if value, ok := _c.mutation.ResultMapping(); ok {
		_spec.SetField(videocalltemplate.FieldResultMapping, field.TypeJSON, value)
		_node.ResultMapping = value
	}
	if value, ok := _c.mutation.ErrorMapping(); ok {
		_spec.SetField(videocalltemplate.FieldErrorMapping, field.TypeJSON, value)
		_node.ErrorMapping = value
	}
	if value, ok := _c.mutation.PollConfig(); ok {
		_spec.SetField(videocalltemplate.FieldPollConfig, field.TypeJSON, value)
		_node.PollConfig = value
	}
	if value, ok := _c.mutation.TimeoutConfig(); ok {
		_spec.SetField(videocalltemplate.FieldTimeoutConfig, field.TypeJSON, value)
		_node.TimeoutConfig = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(videocalltemplate.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if nodes := _c.mutation.VideoModelsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   videocalltemplate.VideoModelsTable,
			Columns: []string{videocalltemplate.VideoModelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(videomodel.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.VideoCallTemplate.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.VideoCallTemplateUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *VideoCallTemplateCreate) OnConflict(opts ...sql.ConflictOption) *VideoCallTemplateUpsertOne {
	_c.conflict = opts
	return &VideoCallTemplateUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.VideoCallTemplate.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *VideoCallTemplateCreate) OnConflictColumns(columns ...string) *VideoCallTemplateUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &VideoCallTemplateUpsertOne{
		create: _c,
	}
}

type (
	// VideoCallTemplateUpsertOne is the builder for "upsert"-ing
	//  one VideoCallTemplate node.
	VideoCallTemplateUpsertOne struct {
		create *VideoCallTemplateCreate
	}

	// VideoCallTemplateUpsert is the "OnConflict" setter.
	VideoCallTemplateUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *VideoCallTemplateUpsert) SetUpdatedAt(v time.Time) *VideoCallTemplateUpsert {
	u.Set(videocalltemplate.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *VideoCallTemplateUpsert) UpdateUpdatedAt() *VideoCallTemplateUpsert {
	u.SetExcluded(videocalltemplate.FieldUpdatedAt)
	return u
}

// SetName sets the "name" field.
func (u *VideoCallTemplateUpsert) SetName(v string) *VideoCallTemplateUpsert {
	u.Set(videocalltemplate.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *VideoCallTemplateUpsert) UpdateName() *VideoCallTemplateUpsert {
	u.SetExcluded(videocalltemplate.FieldName)
	return u
}

// SetCreateMethod sets the "create_method" field.
func (u *VideoCallTemplateUpsert) SetCreateMethod(v string) *VideoCallTemplateUpsert {
	u.Set(videocalltemplate.FieldCreateMethod, v)
	return u
}

// UpdateCreateMethod sets the "create_method" field to the value that was provided on create.
func (u *VideoCallTemplateUpsert) UpdateCreateMethod() *VideoCallTemplateUpsert {
	u.SetExcluded(videocalltemplate.FieldCreateMethod)
	return u
}

// SetCreatePath sets the "create_path" field.
func (u *VideoCallTemplateUpsert) SetCreatePath(v string) *VideoCallTemplateUpsert {
	u.Set(videocalltemplate.FieldCreatePath, v)
	return u
}

// UpdateCreatePath sets the "create_path" field to the value that was provided on create.
func (u *VideoCallTemplateUpsert) UpdateCreatePath() *VideoCallTemplateUpsert {
	u.SetExcluded(videocalltemplate.FieldCreatePath)
	return u
}

// SetQueryMethod sets the "query_method" field.
func (u *VideoCallTemplateUpsert) SetQueryMethod(v string) *VideoCallTemplateUpsert {
	u.Set(videocalltemplate.FieldQueryMethod, v)
	return u
}

// UpdateQueryMethod sets the "query_method" field to the value that was provided on create.
func (u *VideoCallTemplateUpsert) UpdateQueryMethod() *VideoCallTemplateUpsert {
	u.SetExcluded(videocalltemplate.FieldQueryMethod)
	return u
}

// SetQueryPath sets the "query_path" field.
func (u *VideoCallTemplateUpsert) SetQueryPath(v string) *VideoCallTemplateUpsert {
	u.Set(videocalltemplate.FieldQueryPath, v)
	return u
}

// UpdateQueryPath sets the "query_path" field to the value that was provided on create.
func (u *VideoCallTemplateUpsert) UpdateQueryPath() *VideoCallTemplateUpsert {
	u.SetExcluded(videocalltemplate.FieldQueryPath)
	return u
}

// SetContentMethod sets the "content_method" field.
func (u *VideoCallTemplateUpsert) SetContentMethod(v string) *VideoCallTemplateUpsert {
	u.Set(videocalltemplate.FieldContentMethod, v)
	return u
}

// UpdateContentMethod sets the "content_method" field to the value that was provided on create.
func (u *VideoCallTemplateUpsert) UpdateContentMethod() *VideoCallTemplateUpsert {
	u.SetExcluded(videocalltemplate.FieldContentMethod)
	return u
}

// ClearContentMethod clears the value of the "content_method" field.
func (u *VideoCallTemplateUpsert) ClearContentMethod() *VideoCallTemplateUpsert {
	u.SetNull(videocalltemplate.FieldContentMethod)
	return u
}

// SetContentPath sets the "content_path" field.
func (u *VideoCallTemplateUpsert) SetContentPath(v string) *VideoCallTemplateUpsert {
	u.Set(videocalltemplate.FieldContentPath, v)
	return u
}

// UpdateContentPath sets the "content_path" field to the value that was provided on create.
func (u *VideoCallTemplateUpsert) UpdateContentPath() *VideoCallTemplateUpsert {
	u.SetExcluded(videocalltemplate.FieldContentPath)
	return u
}

// ClearContentPath clears the value of the "content_path" field.
func (u *VideoCallTemplateUpsert) ClearContentPath() *VideoCallTemplateUpsert {
	u.SetNull(videocalltemplate.FieldContentPath)
	return u
}

// SetCancelMethod sets the "cancel_method" field.
func (u *VideoCallTemplateUpsert) SetCancelMethod(v string) *VideoCallTemplateUpsert {
	u.Set(videocalltemplate.FieldCancelMethod, v)
	return u
}

// UpdateCancelMethod sets the "cancel_method" field to the value that was provided on create.
func (u *VideoCallTemplateUpsert) UpdateCancelMethod() *VideoCallTemplateUpsert {
	u.SetExcluded(videocalltemplate.FieldCancelMethod)
	return u
}

// ClearCancelMethod clears the value of the "cancel_method" field.
func (u *VideoCallTemplateUpsert) ClearCancelMethod() *VideoCallTemplateUpsert {
	u.SetNull(videocalltemplate.FieldCancelMethod)
	return u
}

// SetCancelPath sets the "cancel_path" field.
func (u *VideoCallTemplateUpsert) SetCancelPath(v string) *VideoCallTemplateUpsert {
	u.Set(videocalltemplate.FieldCancelPath, v)
	return u
}

// UpdateCancelPath sets the "cancel_path" field to the value that was provided on create.
func (u *VideoCallTemplateUpsert) UpdateCancelPath() *VideoCallTemplateUpsert {
	u.SetExcluded(videocalltemplate.FieldCancelPath)
	return u
}

// ClearCancelPath clears the value of the "cancel_path" field.
func (u *VideoCallTemplateUpsert) ClearCancelPath() *VideoCallTemplateUpsert {
	u.SetNull(videocalltemplate.FieldCancelPath)
	return u
}

// SetStatusMapping sets the "status_mapping" field.
func (u *VideoCallTemplateUpsert) SetStatusMapping(v map[string]string) *VideoCallTemplateUpsert {
	u.Set(videocalltemplate.FieldStatusMapping, v)
	return u
}

// UpdateStatusMapping sets the "status_mapping" field to the value that was provided on create.
func (u *VideoCallTemplateUpsert) UpdateStatusMapping() *VideoCallTemplateUpsert {
	u.SetExcluded(videocalltemplate.FieldStatusMapping)
	return u
}

// SetResultMapping sets the "result_mapping" field.
func (u *VideoCallTemplateUpsert) SetResultMapping(v map[string]string) *VideoCallTemplateUpsert {
	u.Set(videocalltemplate.FieldResultMapping, v)
	return u
}

// UpdateResultMapping sets the "result_mapping" field to the value that was provided on create.
func (u *VideoCallTemplateUpsert) UpdateResultMapping() *VideoCallTemplateUpsert {
	u.SetExcluded(videocalltemplate.FieldResultMapping)
	return u
}

// SetErrorMapping sets the "error_mapping" field.
func (u *VideoCallTemplateUpsert) SetErrorMapping(v map[string]string) *VideoCallTemplateUpsert {
	u.Set(videocalltemplate.FieldErrorMapping, v)
	return u
}

// UpdateErrorMapping sets the "error_mapping" field to the value that was provided on create.
func (u *VideoCallTemplateUpsert) UpdateErrorMapping() *VideoCallTemplateUpsert {
	u.SetExcluded(videocalltemplate.FieldErrorMapping)
	return u
}

// SetPollConfig sets the "poll_config" field.
func (u *VideoCallTemplateUpsert) SetPollConfig(v map[string]interface{}) *VideoCallTemplateUpsert {
	u.Set(videocalltemplate.FieldPollConfig, v)
	return u
}

// UpdatePollConfig sets the "poll_config" field to the value that was provided on create.
func (u *VideoCallTemplateUpsert) UpdatePollConfig() *VideoCallTemplateUpsert {
	u.SetExcluded(videocalltemplate.FieldPollConfig)
	return u
}

// SetTimeoutConfig sets the "timeout_config" field.
func (u *VideoCallTemplateUpsert) SetTimeoutConfig(v map[string]interface{}) *VideoCallTemplateUpsert {
	u.Set(videocalltemplate.FieldTimeoutConfig, v)
	return u
}

// UpdateTimeoutConfig sets the "timeout_config" field to the value that was provided on create.
func (u *VideoCallTemplateUpsert) UpdateTimeoutConfig() *VideoCallTemplateUpsert {
	u.SetExcluded(videocalltemplate.FieldTimeoutConfig)
	return u
}

// SetStatus sets the "status" field.
func (u *VideoCallTemplateUpsert) SetStatus(v string) *VideoCallTemplateUpsert {
	u.Set(videocalltemplate.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *VideoCallTemplateUpsert) UpdateStatus() *VideoCallTemplateUpsert {
	u.SetExcluded(videocalltemplate.FieldStatus)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.VideoCallTemplate.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *VideoCallTemplateUpsertOne) UpdateNewValues() *VideoCallTemplateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(videocalltemplate.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.VideoCallTemplate.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *VideoCallTemplateUpsertOne) Ignore() *VideoCallTemplateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *VideoCallTemplateUpsertOne) DoNothing() *VideoCallTemplateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the VideoCallTemplateCreate.OnConflict
// documentation for more info.
func (u *VideoCallTemplateUpsertOne) Update(set func(*VideoCallTemplateUpsert)) *VideoCallTemplateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&VideoCallTemplateUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *VideoCallTemplateUpsertOne) SetUpdatedAt(v time.Time) *VideoCallTemplateUpsertOne {
	return u.Update(func(s *VideoCallTemplateUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *VideoCallTemplateUpsertOne) UpdateUpdatedAt() *VideoCallTemplateUpsertOne {
	return u.Update(func(s *VideoCallTemplateUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *VideoCallTemplateUpsertOne) SetName(v string) *VideoCallTemplateUpsertOne {
	return u.Update(func(s *VideoCallTemplateUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *VideoCallTemplateUpsertOne) UpdateName() *VideoCallTemplateUpsertOne {
	return u.Update(func(s *VideoCallTemplateUpsert) {
		s.UpdateName()
	})
}

// SetCreateMethod sets the "create_method" field.
func (u *VideoCallTemplateUpsertOne) SetCreateMethod(v string) *VideoCallTemplateUpsertOne {
	return u.Update(func(s *VideoCallTemplateUpsert) {
		s.SetCreateMethod(v)
	})
}

// UpdateCreateMethod sets the "create_method" field to the value that was provided on create.
func (u *VideoCallTemplateUpsertOne) UpdateCreateMethod() *VideoCallTemplateUpsertOne {
	return u.Update(func(s *VideoCallTemplateUpsert) {
		s.UpdateCreateMethod()
	})
}

// SetCreatePath sets the "create_path" field.
func (u *VideoCallTemplateUpsertOne) SetCreatePath(v string) *VideoCallTemplateUpsertOne {
	return u.Update(func(s *VideoCallTemplateUpsert) {
		s.SetCreatePath(v)
	})
}

// UpdateCreatePath sets the "create_path" field to the value that was provided on create.
func (u *VideoCallTemplateUpsertOne) UpdateCreatePath() *VideoCallTemplateUpsertOne {
	return u.Update(func(s *VideoCallTemplateUpsert) {
		s.UpdateCreatePath()
	})
}

// SetQueryMethod sets the "query_method" field.
func (u *VideoCallTemplateUpsertOne) SetQueryMethod(v string) *VideoCallTemplateUpsertOne {
	return u.Update(func(s *VideoCallTemplateUpsert) {
		s.SetQueryMethod(v)
	})
}

// UpdateQueryMethod sets the "query_method" field to the value that was provided on create.
func (u *VideoCallTemplateUpsertOne) UpdateQueryMethod() *VideoCallTemplateUpsertOne {
	return u.Update(func(s *VideoCallTemplateUpsert) {
		s.UpdateQueryMethod()
	})
}

// SetQueryPath sets the "query_path" field.
func (u *VideoCallTemplateUpsertOne) SetQueryPath(v string) *VideoCallTemplateUpsertOne {
	return u.Update(func(s *VideoCallTemplateUpsert) {
		s.SetQueryPath(v)
	})
}

// UpdateQueryPath sets the "query_path" field to the value that was provided on create.
func (u *VideoCallTemplateUpsertOne) UpdateQueryPath() *VideoCallTemplateUpsertOne {
	return u.Update(func(s *VideoCallTemplateUpsert) {
		s.UpdateQueryPath()
	})
}

// SetContentMethod sets the "content_method" field.
func (u *VideoCallTemplateUpsertOne) SetContentMethod(v string) *VideoCallTemplateUpsertOne {
	return u.Update(func(s *VideoCallTemplateUpsert) {
		s.SetContentMethod(v)
	})
}

// UpdateContentMethod sets the "content_method" field to the value that was provided on create.
func (u *VideoCallTemplateUpsertOne) UpdateContentMethod() *VideoCallTemplateUpsertOne {
	return u.Update(func(s *VideoCallTemplateUpsert) {
		s.UpdateContentMethod()
	})
}

// ClearContentMethod clears the value of the "content_method" field.
func (u *VideoCallTemplateUpsertOne) ClearContentMethod() *VideoCallTemplateUpsertOne {
	return u.Update(func(s *VideoCallTemplateUpsert) {
		s.ClearContentMethod()
	})
}

// SetContentPath sets the "content_path" field.
func (u *VideoCallTemplateUpsertOne) SetContentPath(v string) *VideoCallTemplateUpsertOne {
	return u.Update(func(s *VideoCallTemplateUpsert) {
		s.SetContentPath(v)
	})
}

// UpdateContentPath sets the "content_path" field to the value that was provided on create.
func (u *VideoCallTemplateUpsertOne) UpdateContentPath() *VideoCallTemplateUpsertOne {
	return u.Update(func(s *VideoCallTemplateUpsert) {
		s.UpdateContentPath()
	})
}

// ClearContentPath clears the value of the "content_path" field.
func (u *VideoCallTemplateUpsertOne) ClearContentPath() *VideoCallTemplateUpsertOne {
	return u.Update(func(s *VideoCallTemplateUpsert) {
		s.ClearContentPath()
	})
}

// SetCancelMethod sets the "cancel_method" field.
func (u *VideoCallTemplateUpsertOne) SetCancelMethod(v string) *VideoCallTemplateUpsertOne {
	return u.Update(func(s *VideoCallTemplateUpsert) {
		s.SetCancelMethod(v)
	})
}

// UpdateCancelMethod sets the "cancel_method" field to the value that was provided on create.
func (u *VideoCallTemplateUpsertOne) UpdateCancelMethod() *VideoCallTemplateUpsertOne {
	return u.Update(func(s *VideoCallTemplateUpsert) {
		s.UpdateCancelMethod()
	})
}

// ClearCancelMethod clears the value of the "cancel_method" field.
func (u *VideoCallTemplateUpsertOne) ClearCancelMethod() *VideoCallTemplateUpsertOne {
	return u.Update(func(s *VideoCallTemplateUpsert) {
		s.ClearCancelMethod()
	})
}

// SetCancelPath sets the "cancel_path" field.
func (u *VideoCallTemplateUpsertOne) SetCancelPath(v string) *VideoCallTemplateUpsertOne {
	return u.Update(func(s *VideoCallTemplateUpsert) {
		s.SetCancelPath(v)
	})
}

// UpdateCancelPath sets the "cancel_path" field to the value that was provided on create.
func (u *VideoCallTemplateUpsertOne) UpdateCancelPath() *VideoCallTemplateUpsertOne {
	return u.Update(func(s *VideoCallTemplateUpsert) {
		s.UpdateCancelPath()
	})
}

// ClearCancelPath clears the value of the "cancel_path" field.
func (u *VideoCallTemplateUpsertOne) ClearCancelPath() *VideoCallTemplateUpsertOne {
	return u.Update(func(s *VideoCallTemplateUpsert) {
		s.ClearCancelPath()
	})
}

// SetStatusMapping sets the "status_mapping" field.
func (u *VideoCallTemplateUpsertOne) SetStatusMapping(v map[string]string) *VideoCallTemplateUpsertOne {
	return u.Update(func(s *VideoCallTemplateUpsert) {
		s.SetStatusMapping(v)
	})
}

// UpdateStatusMapping sets the "status_mapping" field to the value that was provided on create.
func (u *VideoCallTemplateUpsertOne) UpdateStatusMapping() *VideoCallTemplateUpsertOne {
	return u.Update(func(s *VideoCallTemplateUpsert) {
		s.UpdateStatusMapping()
	})
}

// SetResultMapping sets the "result_mapping" field.
func (u *VideoCallTemplateUpsertOne) SetResultMapping(v map[string]string) *VideoCallTemplateUpsertOne {
	return u.Update(func(s *VideoCallTemplateUpsert) {
		s.SetResultMapping(v)
	})
}

// UpdateResultMapping sets the "result_mapping" field to the value that was provided on create.
func (u *VideoCallTemplateUpsertOne) UpdateResultMapping() *VideoCallTemplateUpsertOne {
	return u.Update(func(s *VideoCallTemplateUpsert) {
		s.UpdateResultMapping()
	})
}

// SetErrorMapping sets the "error_mapping" field.
func (u *VideoCallTemplateUpsertOne) SetErrorMapping(v map[string]string) *VideoCallTemplateUpsertOne {
	return u.Update(func(s *VideoCallTemplateUpsert) {
		s.SetErrorMapping(v)
	})
}

// UpdateErrorMapping sets the "error_mapping" field to the value that was provided on create.
func (u *VideoCallTemplateUpsertOne) UpdateErrorMapping() *VideoCallTemplateUpsertOne {
	return u.Update(func(s *VideoCallTemplateUpsert) {
		s.UpdateErrorMapping()
	})
}

// SetPollConfig sets the "poll_config" field.
func (u *VideoCallTemplateUpsertOne) SetPollConfig(v map[string]interface{}) *VideoCallTemplateUpsertOne {
	return u.Update(func(s *VideoCallTemplateUpsert) {
		s.SetPollConfig(v)
	})
}

// UpdatePollConfig sets the "poll_config" field to the value that was provided on create.
func (u *VideoCallTemplateUpsertOne) UpdatePollConfig() *VideoCallTemplateUpsertOne {
	return u.Update(func(s *VideoCallTemplateUpsert) {
		s.UpdatePollConfig()
	})
}

// SetTimeoutConfig sets the "timeout_config" field.
func (u *VideoCallTemplateUpsertOne) SetTimeoutConfig(v map[string]interface{}) *VideoCallTemplateUpsertOne {
	return u.Update(func(s *VideoCallTemplateUpsert) {
		s.SetTimeoutConfig(v)
	})
}

// UpdateTimeoutConfig sets the "timeout_config" field to the value that was provided on create.
func (u *VideoCallTemplateUpsertOne) UpdateTimeoutConfig() *VideoCallTemplateUpsertOne {
	return u.Update(func(s *VideoCallTemplateUpsert) {
		s.UpdateTimeoutConfig()
	})
}

// SetStatus sets the "status" field.
func (u *VideoCallTemplateUpsertOne) SetStatus(v string) *VideoCallTemplateUpsertOne {
	return u.Update(func(s *VideoCallTemplateUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *VideoCallTemplateUpsertOne) UpdateStatus() *VideoCallTemplateUpsertOne {
	return u.Update(func(s *VideoCallTemplateUpsert) {
		s.UpdateStatus()
	})
}

// Exec executes the query.
func (u *VideoCallTemplateUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for VideoCallTemplateCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *VideoCallTemplateUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *VideoCallTemplateUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *VideoCallTemplateUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// VideoCallTemplateCreateBulk is the builder for creating many VideoCallTemplate entities in bulk.
type VideoCallTemplateCreateBulk struct {
	config
	err      error
	builders []*VideoCallTemplateCreate
	conflict []sql.ConflictOption
}

// Save creates the VideoCallTemplate entities in the database.
func (_c *VideoCallTemplateCreateBulk) Save(ctx context.Context) ([]*VideoCallTemplate, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*VideoCallTemplate, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*VideoCallTemplateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *VideoCallTemplateCreateBulk) SaveX(ctx context.Context) []*VideoCallTemplate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VideoCallTemplateCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VideoCallTemplateCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.VideoCallTemplate.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.VideoCallTemplateUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *VideoCallTemplateCreateBulk) OnConflict(opts ...sql.ConflictOption) *VideoCallTemplateUpsertBulk {
	_c.conflict = opts
	return &VideoCallTemplateUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.VideoCallTemplate.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *VideoCallTemplateCreateBulk) OnConflictColumns(columns ...string) *VideoCallTemplateUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &VideoCallTemplateUpsertBulk{
		create: _c,
	}
}

// VideoCallTemplateUpsertBulk is the builder for "upsert"-ing
// a bulk of VideoCallTemplate nodes.
type VideoCallTemplateUpsertBulk struct {
	create *VideoCallTemplateCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.VideoCallTemplate.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *VideoCallTemplateUpsertBulk) UpdateNewValues() *VideoCallTemplateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(videocalltemplate.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.VideoCallTemplate.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *VideoCallTemplateUpsertBulk) Ignore() *VideoCallTemplateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *VideoCallTemplateUpsertBulk) DoNothing() *VideoCallTemplateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the VideoCallTemplateCreateBulk.OnConflict
// documentation for more info.
func (u *VideoCallTemplateUpsertBulk) Update(set func(*VideoCallTemplateUpsert)) *VideoCallTemplateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&VideoCallTemplateUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *VideoCallTemplateUpsertBulk) SetUpdatedAt(v time.Time) *VideoCallTemplateUpsertBulk {
	return u.Update(func(s *VideoCallTemplateUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *VideoCallTemplateUpsertBulk) UpdateUpdatedAt() *VideoCallTemplateUpsertBulk {
	return u.Update(func(s *VideoCallTemplateUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *VideoCallTemplateUpsertBulk) SetName(v string) *VideoCallTemplateUpsertBulk {
	return u.Update(func(s *VideoCallTemplateUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *VideoCallTemplateUpsertBulk) UpdateName() *VideoCallTemplateUpsertBulk {
	return u.Update(func(s *VideoCallTemplateUpsert) {
		s.UpdateName()
	})
}

// SetCreateMethod sets the "create_method" field.
func (u *VideoCallTemplateUpsertBulk) SetCreateMethod(v string) *VideoCallTemplateUpsertBulk {
	return u.Update(func(s *VideoCallTemplateUpsert) {
		s.SetCreateMethod(v)
	})
}

// UpdateCreateMethod sets the "create_method" field to the value that was provided on create.
func (u *VideoCallTemplateUpsertBulk) UpdateCreateMethod() *VideoCallTemplateUpsertBulk {
	return u.Update(func(s *VideoCallTemplateUpsert) {
		s.UpdateCreateMethod()
	})
}

// SetCreatePath sets the "create_path" field.
func (u *VideoCallTemplateUpsertBulk) SetCreatePath(v string) *VideoCallTemplateUpsertBulk {
	return u.Update(func(s *VideoCallTemplateUpsert) {
		s.SetCreatePath(v)
	})
}

// UpdateCreatePath sets the "create_path" field to the value that was provided on create.
func (u *VideoCallTemplateUpsertBulk) UpdateCreatePath() *VideoCallTemplateUpsertBulk {
	return u.Update(func(s *VideoCallTemplateUpsert) {
		s.UpdateCreatePath()
	})
}

// SetQueryMethod sets the "query_method" field.
func (u *VideoCallTemplateUpsertBulk) SetQueryMethod(v string) *VideoCallTemplateUpsertBulk {
	return u.Update(func(s *VideoCallTemplateUpsert) {
		s.SetQueryMethod(v)
	})
}

// UpdateQueryMethod sets the "query_method" field to the value that was provided on create.
func (u *VideoCallTemplateUpsertBulk) UpdateQueryMethod() *VideoCallTemplateUpsertBulk {
	return u.Update(func(s *VideoCallTemplateUpsert) {
		s.UpdateQueryMethod()
	})
}

// SetQueryPath sets the "query_path" field.
func (u *VideoCallTemplateUpsertBulk) SetQueryPath(v string) *VideoCallTemplateUpsertBulk {
	return u.Update(func(s *VideoCallTemplateUpsert) {
		s.SetQueryPath(v)
	})
}

// UpdateQueryPath sets the "query_path" field to the value that was provided on create.
func (u *VideoCallTemplateUpsertBulk) UpdateQueryPath() *VideoCallTemplateUpsertBulk {
	return u.Update(func(s *VideoCallTemplateUpsert) {
		s.UpdateQueryPath()
	})
}

// SetContentMethod sets the "content_method" field.
func (u *VideoCallTemplateUpsertBulk) SetContentMethod(v string) *VideoCallTemplateUpsertBulk {
	return u.Update(func(s *VideoCallTemplateUpsert) {
		s.SetContentMethod(v)
	})
}

// UpdateContentMethod sets the "content_method" field to the value that was provided on create.
func (u *VideoCallTemplateUpsertBulk) UpdateContentMethod() *VideoCallTemplateUpsertBulk {
	return u.Update(func(s *VideoCallTemplateUpsert) {
		s.UpdateContentMethod()
	})
}

// ClearContentMethod clears the value of the "content_method" field.
func (u *VideoCallTemplateUpsertBulk) ClearContentMethod() *VideoCallTemplateUpsertBulk {
	return u.Update(func(s *VideoCallTemplateUpsert) {
		s.ClearContentMethod()
	})
}

// SetContentPath sets the "content_path" field.
func (u *VideoCallTemplateUpsertBulk) SetContentPath(v string) *VideoCallTemplateUpsertBulk {
	return u.Update(func(s *VideoCallTemplateUpsert) {
		s.SetContentPath(v)
	})
}

// UpdateContentPath sets the "content_path" field to the value that was provided on create.
func (u *VideoCallTemplateUpsertBulk) UpdateContentPath() *VideoCallTemplateUpsertBulk {
	return u.Update(func(s *VideoCallTemplateUpsert) {
		s.UpdateContentPath()
	})
}

// ClearContentPath clears the value of the "content_path" field.
func (u *VideoCallTemplateUpsertBulk) ClearContentPath() *VideoCallTemplateUpsertBulk {
	return u.Update(func(s *VideoCallTemplateUpsert) {
		s.ClearContentPath()
	})
}

// SetCancelMethod sets the "cancel_method" field.
func (u *VideoCallTemplateUpsertBulk) SetCancelMethod(v string) *VideoCallTemplateUpsertBulk {
	return u.Update(func(s *VideoCallTemplateUpsert) {
		s.SetCancelMethod(v)
	})
}

// UpdateCancelMethod sets the "cancel_method" field to the value that was provided on create.
func (u *VideoCallTemplateUpsertBulk) UpdateCancelMethod() *VideoCallTemplateUpsertBulk {
	return u.Update(func(s *VideoCallTemplateUpsert) {
		s.UpdateCancelMethod()
	})
}

// ClearCancelMethod clears the value of the "cancel_method" field.
func (u *VideoCallTemplateUpsertBulk) ClearCancelMethod() *VideoCallTemplateUpsertBulk {
	return u.Update(func(s *VideoCallTemplateUpsert) {
		s.ClearCancelMethod()
	})
}

// SetCancelPath sets the "cancel_path" field.
func (u *VideoCallTemplateUpsertBulk) SetCancelPath(v string) *VideoCallTemplateUpsertBulk {
	return u.Update(func(s *VideoCallTemplateUpsert) {
		s.SetCancelPath(v)
	})
}

// UpdateCancelPath sets the "cancel_path" field to the value that was provided on create.
func (u *VideoCallTemplateUpsertBulk) UpdateCancelPath() *VideoCallTemplateUpsertBulk {
	return u.Update(func(s *VideoCallTemplateUpsert) {
		s.UpdateCancelPath()
	})
}

// ClearCancelPath clears the value of the "cancel_path" field.
func (u *VideoCallTemplateUpsertBulk) ClearCancelPath() *VideoCallTemplateUpsertBulk {
	return u.Update(func(s *VideoCallTemplateUpsert) {
		s.ClearCancelPath()
	})
}

// SetStatusMapping sets the "status_mapping" field.
func (u *VideoCallTemplateUpsertBulk) SetStatusMapping(v map[string]string) *VideoCallTemplateUpsertBulk {
	return u.Update(func(s *VideoCallTemplateUpsert) {
		s.SetStatusMapping(v)
	})
}

// UpdateStatusMapping sets the "status_mapping" field to the value that was provided on create.
func (u *VideoCallTemplateUpsertBulk) UpdateStatusMapping() *VideoCallTemplateUpsertBulk {
	return u.Update(func(s *VideoCallTemplateUpsert) {
		s.UpdateStatusMapping()
	})
}

// SetResultMapping sets the "result_mapping" field.
func (u *VideoCallTemplateUpsertBulk) SetResultMapping(v map[string]string) *VideoCallTemplateUpsertBulk {
	return u.Update(func(s *VideoCallTemplateUpsert) {
		s.SetResultMapping(v)
	})
}

// UpdateResultMapping sets the "result_mapping" field to the value that was provided on create.
func (u *VideoCallTemplateUpsertBulk) UpdateResultMapping() *VideoCallTemplateUpsertBulk {
	return u.Update(func(s *VideoCallTemplateUpsert) {
		s.UpdateResultMapping()
	})
}

// SetErrorMapping sets the "error_mapping" field.
func (u *VideoCallTemplateUpsertBulk) SetErrorMapping(v map[string]string) *VideoCallTemplateUpsertBulk {
	return u.Update(func(s *VideoCallTemplateUpsert) {
		s.SetErrorMapping(v)
	})
}

// UpdateErrorMapping sets the "error_mapping" field to the value that was provided on create.
func (u *VideoCallTemplateUpsertBulk) UpdateErrorMapping() *VideoCallTemplateUpsertBulk {
	return u.Update(func(s *VideoCallTemplateUpsert) {
		s.UpdateErrorMapping()
	})
}

// SetPollConfig sets the "poll_config" field.
func (u *VideoCallTemplateUpsertBulk) SetPollConfig(v map[string]interface{}) *VideoCallTemplateUpsertBulk {
	return u.Update(func(s *VideoCallTemplateUpsert) {
		s.SetPollConfig(v)
	})
}

// UpdatePollConfig sets the "poll_config" field to the value that was provided on create.
func (u *VideoCallTemplateUpsertBulk) UpdatePollConfig() *VideoCallTemplateUpsertBulk {
	return u.Update(func(s *VideoCallTemplateUpsert) {
		s.UpdatePollConfig()
	})
}

// SetTimeoutConfig sets the "timeout_config" field.
func (u *VideoCallTemplateUpsertBulk) SetTimeoutConfig(v map[string]interface{}) *VideoCallTemplateUpsertBulk {
	return u.Update(func(s *VideoCallTemplateUpsert) {
		s.SetTimeoutConfig(v)
	})
}

// UpdateTimeoutConfig sets the "timeout_config" field to the value that was provided on create.
func (u *VideoCallTemplateUpsertBulk) UpdateTimeoutConfig() *VideoCallTemplateUpsertBulk {
	return u.Update(func(s *VideoCallTemplateUpsert) {
		s.UpdateTimeoutConfig()
	})
}

// SetStatus sets the "status" field.
func (u *VideoCallTemplateUpsertBulk) SetStatus(v string) *VideoCallTemplateUpsertBulk {
	return u.Update(func(s *VideoCallTemplateUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *VideoCallTemplateUpsertBulk) UpdateStatus() *VideoCallTemplateUpsertBulk {
	return u.Update(func(s *VideoCallTemplateUpsert) {
		s.UpdateStatus()
	})
}

// Exec executes the query.
func (u *VideoCallTemplateUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the VideoCallTemplateCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for VideoCallTemplateCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *VideoCallTemplateUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
