// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/videocalltemplate"
	"github.com/Wei-Shaw/sub2api/ent/videogenerationtask"
	"github.com/Wei-Shaw/sub2api/ent/videomodel"
)

// VideoModelCreate is the builder for creating a VideoModel entity.
type VideoModelCreate struct {
	config
	mutation *VideoModelMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *VideoModelCreate) SetCreatedAt(v time.Time) *VideoModelCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *VideoModelCreate) SetNillableCreatedAt(v *time.Time) *VideoModelCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *VideoModelCreate) SetUpdatedAt(v time.Time) *VideoModelCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *VideoModelCreate) SetNillableUpdatedAt(v *time.Time) *VideoModelCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetPublicModel sets the "public_model" field.
func (_c *VideoModelCreate) SetPublicModel(v string) *VideoModelCreate {
	_c.mutation.SetPublicModel(v)
	return _c
}

// SetDisplayName sets the "display_name" field.
func (_c *VideoModelCreate) SetDisplayName(v string) *VideoModelCreate {
	_c.mutation.SetDisplayName(v)
	return _c
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_c *VideoModelCreate) SetNillableDisplayName(v *string) *VideoModelCreate {
	if v != nil {
		_c.SetDisplayName(*v)
	}
	return _c
}

// SetTemplateID sets the "template_id" field.
func (_c *VideoModelCreate) SetTemplateID(v int64) *VideoModelCreate {
	_c.mutation.SetTemplateID(v)
	return _c
}

// SetUpstreamModelID sets the "upstream_model_id" field.
func (_c *VideoModelCreate) SetUpstreamModelID(v string) *VideoModelCreate {
	_c.mutation.SetUpstreamModelID(v)
	return _c
}

// SetNillableUpstreamModelID sets the "upstream_model_id" field if the given value is not nil.
func (_c *VideoModelCreate) SetNillableUpstreamModelID(v *string) *VideoModelCreate {
	if v != nil {
		_c.SetUpstreamModelID(*v)
	}
	return _c
}

// SetRequestShape sets the "request_shape" field.
func (_c *VideoModelCreate) SetRequestShape(v string) *VideoModelCreate {
	_c.mutation.SetRequestShape(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *VideoModelCreate) SetStatus(v string) *VideoModelCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *VideoModelCreate) SetNillableStatus(v *string) *VideoModelCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCapabilities sets the "capabilities" field.
func (_c *VideoModelCreate) SetCapabilities(v map[string]interface{}) *VideoModelCreate {
	_c.mutation.SetCapabilities(v)
	return _c
}

// SetDefaults sets the "defaults" field.
func (_c *VideoModelCreate) SetDefaults(v map[string]interface{}) *VideoModelCreate {
	_c.mutation.SetDefaults(v)
	return _c
}

// SetLimits sets the "limits" field.
func (_c *VideoModelCreate) SetLimits(v map[string]interface{}) *VideoModelCreate {
	_c.mutation.SetLimits(v)
	return _c
}

// SetSupportedOptions sets the "supported_options" field.
func (_c *VideoModelCreate) SetSupportedOptions(v map[string]interface{}) *VideoModelCreate {
	_c.mutation.SetSupportedOptions(v)
	return _c
}

// SetExtraBodyAllow sets the "extra_body_allow" field.
func (_c *VideoModelCreate) SetExtraBodyAllow(v []string) *VideoModelCreate {
	_c.mutation.SetExtraBodyAllow(v)
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *VideoModelCreate) SetSortOrder(v int) *VideoModelCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *VideoModelCreate) SetNillableSortOrder(v *int) *VideoModelCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// SetTemplate sets the "template" edge to the VideoCallTemplate entity.
func (_c *VideoModelCreate) SetTemplate(v *VideoCallTemplate) *VideoModelCreate {
	return _c.SetTemplateID(v.ID)
}

// AddTaskIDs adds the "tasks" edge to the VideoGenerationTask entity by IDs.
func (_c *VideoModelCreate) AddTaskIDs(ids ...int64) *VideoModelCreate {
	_c.mutation.AddTaskIDs(ids...)
	return _c
}

// AddTasks adds the "tasks" edges to the VideoGenerationTask entity.
func (_c *VideoModelCreate) AddTasks(v ...*VideoGenerationTask) *VideoModelCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTaskIDs(ids...)
}

// Mutation returns the VideoModelMutation object of the builder.
func (_c *VideoModelCreate) Mutation() *VideoModelMutation {
	return _c.mutation
}

// Save creates the VideoModel in the database.
func (_c *VideoModelCreate) Save(ctx context.Context) (*VideoModel, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *VideoModelCreate) SaveX(ctx context.Context) *VideoModel {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VideoModelCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VideoModelCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *VideoModelCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := videomodel.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := videomodel.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := videomodel.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Capabilities(); !ok {
		v := videomodel.DefaultCapabilities()
		_c.mutation.SetCapabilities(v)
	}
	if _, ok := _c.mutation.Defaults(); !ok {
		v := videomodel.DefaultDefaults()
		_c.mutation.SetDefaults(v)
	}
	if _, ok := _c.mutation.Limits(); !ok {
		v := videomodel.DefaultLimits()
		_c.mutation.SetLimits(v)
	}
	if _, ok := _c.mutation.SupportedOptions(); !ok {
		v := videomodel.DefaultSupportedOptions()
		_c.mutation.SetSupportedOptions(v)
	}
	if _, ok := _c.mutation.ExtraBodyAllow(); !ok {
		v := videomodel.DefaultExtraBodyAllow
		_c.mutation.SetExtraBodyAllow(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := videomodel.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *VideoModelCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "VideoModel.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "VideoModel.updated_at"`)}
	}
	if _, ok := _c.mutation.PublicModel(); !ok {
		return &ValidationError{Name: "public_model", err: errors.New(`ent: missing required field "VideoModel.public_model"`)}
	}
	if v, ok := _c.mutation.PublicModel(); ok {
		if err := videomodel.PublicModelValidator(v); err != nil {
			return &ValidationError{Name: "public_model", err: fmt.Errorf(`ent: validator failed for field "VideoModel.public_model": %w`, err)}
		}
	}
	if v, ok := _c.mutation.DisplayName(); ok {
		if err := videomodel.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "VideoModel.display_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TemplateID(); !ok {
		return &ValidationError{Name: "template_id", err: errors.New(`ent: missing required field "VideoModel.template_id"`)}
	}
	if v, ok := _c.mutation.UpstreamModelID(); ok {
		if err := videomodel.UpstreamModelIDValidator(v); err != nil {
			return &ValidationError{Name: "upstream_model_id", err: fmt.Errorf(`ent: validator failed for field "VideoModel.upstream_model_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RequestShape(); !ok {
		return &ValidationError{Name: "request_shape", err: errors.New(`ent: missing required field "VideoModel.request_shape"`)}
	}
	if v, ok := _c.mutation.RequestShape(); ok {
		if err := videomodel.RequestShapeValidator(v); err != nil {
			return &ValidationError{Name: "request_shape", err: fmt.Errorf(`ent: validator failed for field "VideoModel.request_shape": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "VideoModel.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := videomodel.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "VideoModel.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Capabilities(); !ok {
		return &ValidationError{Name: "capabilities", err: errors.New(`ent: missing required field "VideoModel.capabilities"`)}
	}
	if _, ok := _c.mutation.Defaults(); !ok {
		return &ValidationError{Name: "defaults", err: errors.New(`ent: missing required field "VideoModel.defaults"`)}
	}
	if _, ok := _c.mutation.Limits(); !ok {
		return &ValidationError{Name: "limits", err: errors.New(`ent: missing required field "VideoModel.limits"`)}
	}
	if _, ok := _c.mutation.SupportedOptions(); !ok {
		return &ValidationError{Name: "supported_options", err: errors.New(`ent: missing required field "VideoModel.supported_options"`)}
	}
	if _, ok := _c.mutation.ExtraBodyAllow(); !ok {
		return &ValidationError{Name: "extra_body_allow", err: errors.New(`ent: missing required field "VideoModel.extra_body_allow"`)}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "VideoModel.sort_order"`)}
	}
	if len(_c.mutation.TemplateIDs()) == 0 {
		return &ValidationError{Name: "template", err: errors.New(`ent: missing required edge "VideoModel.template"`)}
	}
	return nil
}

func (_c *VideoModelCreate) sqlSave(ctx context.Context) (*VideoModel, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *VideoModelCreate) createSpec() (*VideoModel, *sqlgraph.CreateSpec) {
	var (
		_node = &VideoModel{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(videomodel.Table, sqlgraph.NewFieldSpec(videomodel.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(videomodel.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(videomodel.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.PublicModel(); ok {
		_spec.SetField(videomodel.FieldPublicModel, field.TypeString, value)
		_node.PublicModel = value
	}
	if value, ok := _c.mutation.DisplayName(); ok {
		_spec.SetField(videomodel.FieldDisplayName, field.TypeString, value)
		_node.DisplayName = &value
	}
	if value, ok := _c.mutation.UpstreamModelID(); ok {
		_spec.SetField(videomodel.FieldUpstreamModelID, field.TypeString, value)
		_node.UpstreamModelID = &value
	}
	if value, ok := _c.mutation.RequestShape(); ok {
		_spec.SetField(videomodel.FieldRequestShape, field.TypeString, value)
		_node.RequestShape = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(videomodel.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Capabilities(); ok {
		_spec.SetField(videomodel.FieldCapabilities, field.TypeJSON, value)
		_node.Capabilities = value
	}
	if value, ok := _c.mutation.Defaults(); ok {
		_spec.SetField(videomodel.FieldDefaults, field.TypeJSON, value)
		_node.Defaults = value
	}
	if value, ok := _c.mutation.Limits(); ok {
		_spec.SetField(videomodel.FieldLimits, field.TypeJSON, value)
		_node.Limits = value
	}
	if value, ok := _c.mutation.SupportedOptions(); ok {
		_spec.SetField(videomodel.FieldSupportedOptions, field.TypeJSON, value)
		_node.SupportedOptions = value
	}
	if value, ok := _c.mutation.ExtraBodyAllow(); ok {
		_spec.SetField(videomodel.FieldExtraBodyAllow, field.TypeJSON, value)
		_node.ExtraBodyAllow = value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(videomodel.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if nodes := _c.mutation.TemplateIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   videomodel.TemplateTable,
			Columns: []string{videomodel.TemplateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(videocalltemplate.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TemplateID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TasksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   videomodel.TasksTable,
			Columns: []string{videomodel.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(videogenerationtask.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.VideoModel.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.VideoModelUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *VideoModelCreate) OnConflict(opts ...sql.ConflictOption) *VideoModelUpsertOne {
	_c.conflict = opts
	return &VideoModelUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.VideoModel.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *VideoModelCreate) OnConflictColumns(columns ...string) *VideoModelUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &VideoModelUpsertOne{
		create: _c,
	}
}

type (
	// VideoModelUpsertOne is the builder for "upsert"-ing
	//  one VideoModel node.
	VideoModelUpsertOne struct {
		create *VideoModelCreate
	}

	// VideoModelUpsert is the "OnConflict" setter.
	VideoModelUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *VideoModelUpsert) SetUpdatedAt(v time.Time) *VideoModelUpsert {
	u.Set(videomodel.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *VideoModelUpsert) UpdateUpdatedAt() *VideoModelUpsert {
	u.SetExcluded(videomodel.FieldUpdatedAt)
	return u
}

// SetPublicModel sets the "public_model" field.
func (u *VideoModelUpsert) SetPublicModel(v string) *VideoModelUpsert {
	u.Set(videomodel.FieldPublicModel, v)
	return u
}

// UpdatePublicModel sets the "public_model" field to the value that was provided on create.
func (u *VideoModelUpsert) UpdatePublicModel() *VideoModelUpsert {
	u.SetExcluded(videomodel.FieldPublicModel)
	return u
}

// SetDisplayName sets the "display_name" field.
func (u *VideoModelUpsert) SetDisplayName(v string) *VideoModelUpsert {
	u.Set(videomodel.FieldDisplayName, v)
	return u
}

// UpdateDisplayName sets the "display_name" field to the value that was provided on create.
func (u *VideoModelUpsert) UpdateDisplayName() *VideoModelUpsert {
	u.SetExcluded(videomodel.FieldDisplayName)
	return u
}

// ClearDisplayName clears the value of the "display_name" field.
func (u *VideoModelUpsert) ClearDisplayName() *VideoModelUpsert {
	u.SetNull(videomodel.FieldDisplayName)
	return u
}

// SetTemplateID sets the "template_id" field.
func (u *VideoModelUpsert) SetTemplateID(v int64) *VideoModelUpsert {
	u.Set(videomodel.FieldTemplateID, v)
	return u
}

// UpdateTemplateID sets the "template_id" field to the value that was provided on create.
func (u *VideoModelUpsert) UpdateTemplateID() *VideoModelUpsert {
	u.SetExcluded(videomodel.FieldTemplateID)
	return u
}

// SetUpstreamModelID sets the "upstream_model_id" field.
func (u *VideoModelUpsert) SetUpstreamModelID(v string) *VideoModelUpsert {
	u.Set(videomodel.FieldUpstreamModelID, v)
	return u
}

// UpdateUpstreamModelID sets the "upstream_model_id" field to the value that was provided on create.
func (u *VideoModelUpsert) UpdateUpstreamModelID() *VideoModelUpsert {
	u.SetExcluded(videomodel.FieldUpstreamModelID)
	return u
}

// ClearUpstreamModelID clears the value of the "upstream_model_id" field.
func (u *VideoModelUpsert) ClearUpstreamModelID() *VideoModelUpsert {
	u.SetNull(videomodel.FieldUpstreamModelID)
	return u
}

// SetRequestShape sets the "request_shape" field.
func (u *VideoModelUpsert) SetRequestShape(v string) *VideoModelUpsert {
	u.Set(videomodel.FieldRequestShape, v)
	return u
}

// UpdateRequestShape sets the "request_shape" field to the value that was provided on create.
func (u *VideoModelUpsert) UpdateRequestShape() *VideoModelUpsert {
	u.SetExcluded(videomodel.FieldRequestShape)
	return u
}

// SetStatus sets the "status" field.
func (u *VideoModelUpsert) SetStatus(v string) *VideoModelUpsert {
	u.Set(videomodel.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *VideoModelUpsert) UpdateStatus() *VideoModelUpsert {
	u.SetExcluded(videomodel.FieldStatus)
	return u
}

// SetCapabilities sets the "capabilities" field.
func (u *VideoModelUpsert) SetCapabilities(v map[string]interface{}) *VideoModelUpsert {
	u.Set(videomodel.FieldCapabilities, v)
	return u
}

// UpdateCapabilities sets the "capabilities" field to the value that was provided on create.
func (u *VideoModelUpsert) UpdateCapabilities() *VideoModelUpsert {
	u.SetExcluded(videomodel.FieldCapabilities)
	return u
}

// SetDefaults sets the "defaults" field.
func (u *VideoModelUpsert) SetDefaults(v map[string]interface{}) *VideoModelUpsert {
	u.Set(videomodel.FieldDefaults, v)
	return u
}

// UpdateDefaults sets the "defaults" field to the value that was provided on create.
func (u *VideoModelUpsert) UpdateDefaults() *VideoModelUpsert {
	u.SetExcluded(videomodel.FieldDefaults)
	return u
}

// SetLimits sets the "limits" field.
func (u *VideoModelUpsert) SetLimits(v map[string]interface{}) *VideoModelUpsert {
	u.Set(videomodel.FieldLimits, v)
	return u
}

// UpdateLimits sets the "limits" field to the value that was provided on create.
func (u *VideoModelUpsert) UpdateLimits() *VideoModelUpsert {
	u.SetExcluded(videomodel.FieldLimits)
	return u
}

// SetSupportedOptions sets the "supported_options" field.
func (u *VideoModelUpsert) SetSupportedOptions(v map[string]interface{}) *VideoModelUpsert {
	u.Set(videomodel.FieldSupportedOptions, v)
	return u
}

// UpdateSupportedOptions sets the "supported_options" field to the value that was provided on create.
func (u *VideoModelUpsert) UpdateSupportedOptions() *VideoModelUpsert {
	u.SetExcluded(videomodel.FieldSupportedOptions)
	return u
}

// SetExtraBodyAllow sets the "extra_body_allow" field.
func (u *VideoModelUpsert) SetExtraBodyAllow(v []string) *VideoModelUpsert {
	u.Set(videomodel.FieldExtraBodyAllow, v)
	return u
}

// UpdateExtraBodyAllow sets the "extra_body_allow" field to the value that was provided on create.
func (u *VideoModelUpsert) UpdateExtraBodyAllow() *VideoModelUpsert {
	u.SetExcluded(videomodel.FieldExtraBodyAllow)
	return u
}

// SetSortOrder sets the "sort_order" field.
func (u *VideoModelUpsert) SetSortOrder(v int) *VideoModelUpsert {
	u.Set(videomodel.FieldSortOrder, v)
	return u
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *VideoModelUpsert) UpdateSortOrder() *VideoModelUpsert {
	u.SetExcluded(videomodel.FieldSortOrder)
	return u
}

// AddSortOrder adds v to the "sort_order" field.
func (u *VideoModelUpsert) AddSortOrder(v int) *VideoModelUpsert {
	u.Add(videomodel.FieldSortOrder, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.VideoModel.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *VideoModelUpsertOne) UpdateNewValues() *VideoModelUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(videomodel.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.VideoModel.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *VideoModelUpsertOne) Ignore() *VideoModelUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *VideoModelUpsertOne) DoNothing() *VideoModelUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the VideoModelCreate.OnConflict
// documentation for more info.
func (u *VideoModelUpsertOne) Update(set func(*VideoModelUpsert)) *VideoModelUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&VideoModelUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *VideoModelUpsertOne) SetUpdatedAt(v time.Time) *VideoModelUpsertOne {
	return u.Update(func(s *VideoModelUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *VideoModelUpsertOne) UpdateUpdatedAt() *VideoModelUpsertOne {
	return u.Update(func(s *VideoModelUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetPublicModel sets the "public_model" field.
func (u *VideoModelUpsertOne) SetPublicModel(v string) *VideoModelUpsertOne {
	return u.Update(func(s *VideoModelUpsert) {
		s.SetPublicModel(v)
	})
}

// UpdatePublicModel sets the "public_model" field to the value that was provided on create.
func (u *VideoModelUpsertOne) UpdatePublicModel() *VideoModelUpsertOne {
	return u.Update(func(s *VideoModelUpsert) {
		s.UpdatePublicModel()
	})
}

// SetDisplayName sets the "display_name" field.
func (u *VideoModelUpsertOne) SetDisplayName(v string) *VideoModelUpsertOne {
	return u.Update(func(s *VideoModelUpsert) {
		s.SetDisplayName(v)
	})
}

// UpdateDisplayName sets the "display_name" field to the value that was provided on create.
func (u *VideoModelUpsertOne) UpdateDisplayName() *VideoModelUpsertOne {
	return u.Update(func(s *VideoModelUpsert) {
		s.UpdateDisplayName()
	})
}

// ClearDisplayName clears the value of the "display_name" field.
func (u *VideoModelUpsertOne) ClearDisplayName() *VideoModelUpsertOne {
	return u.Update(func(s *VideoModelUpsert) {
		s.ClearDisplayName()
	})
}

// SetTemplateID sets the "template_id" field.
func (u *VideoModelUpsertOne) SetTemplateID(v int64) *VideoModelUpsertOne {
	return u.Update(func(s *VideoModelUpsert) {
		s.SetTemplateID(v)
	})
}

// UpdateTemplateID sets the "template_id" field to the value that was provided on create.
func (u *VideoModelUpsertOne) UpdateTemplateID() *VideoModelUpsertOne {
	return u.Update(func(s *VideoModelUpsert) {
		s.UpdateTemplateID()
	})
}

// SetUpstreamModelID sets the "upstream_model_id" field.
func (u *VideoModelUpsertOne) SetUpstreamModelID(v string) *VideoModelUpsertOne {
	return u.Update(func(s *VideoModelUpsert) {
		s.SetUpstreamModelID(v)
	})
}

// UpdateUpstreamModelID sets the "upstream_model_id" field to the value that was provided on create.
func (u *VideoModelUpsertOne) UpdateUpstreamModelID() *VideoModelUpsertOne {
	return u.Update(func(s *VideoModelUpsert) {
		s.UpdateUpstreamModelID()
	})
}

// ClearUpstreamModelID clears the value of the "upstream_model_id" field.
func (u *VideoModelUpsertOne) ClearUpstreamModelID() *VideoModelUpsertOne {
	return u.Update(func(s *VideoModelUpsert) {
		s.ClearUpstreamModelID()
	})
}

// SetRequestShape sets the "request_shape" field.
func (u *VideoModelUpsertOne) SetRequestShape(v string) *VideoModelUpsertOne {
	return u.Update(func(s *VideoModelUpsert) {
		s.SetRequestShape(v)
	})
}

// UpdateRequestShape sets the "request_shape" field to the value that was provided on create.
func (u *VideoModelUpsertOne) UpdateRequestShape() *VideoModelUpsertOne {
	return u.Update(func(s *VideoModelUpsert) {
		s.UpdateRequestShape()
	})
}

// SetStatus sets the "status" field.
func (u *VideoModelUpsertOne) SetStatus(v string) *VideoModelUpsertOne {
	return u.Update(func(s *VideoModelUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *VideoModelUpsertOne) UpdateStatus() *VideoModelUpsertOne {
	return u.Update(func(s *VideoModelUpsert) {
		s.UpdateStatus()
	})
}

// SetCapabilities sets the "capabilities" field.
func (u *VideoModelUpsertOne) SetCapabilities(v map[string]interface{}) *VideoModelUpsertOne {
	return u.Update(func(s *VideoModelUpsert) {
		s.SetCapabilities(v)
	})
}

// UpdateCapabilities sets the "capabilities" field to the value that was provided on create.
func (u *VideoModelUpsertOne) UpdateCapabilities() *VideoModelUpsertOne {
	return u.Update(func(s *VideoModelUpsert) {
		s.UpdateCapabilities()
	})
}

// SetDefaults sets the "defaults" field.
func (u *VideoModelUpsertOne) SetDefaults(v map[string]interface{}) *VideoModelUpsertOne {
	return u.Update(func(s *VideoModelUpsert) {
		s.SetDefaults(v)
	})
}

// UpdateDefaults sets the "defaults" field to the value that was provided on create.
func (u *VideoModelUpsertOne) UpdateDefaults() *VideoModelUpsertOne {
	return u.Update(func(s *VideoModelUpsert) {
		s.UpdateDefaults()
	})
}

// SetLimits sets the "limits" field.
func (u *VideoModelUpsertOne) SetLimits(v map[string]interface{}) *VideoModelUpsertOne {
	return u.Update(func(s *VideoModelUpsert) {
		s.SetLimits(v)
	})
}

// UpdateLimits sets the "limits" field to the value that was provided on create.
func (u *VideoModelUpsertOne) UpdateLimits() *VideoModelUpsertOne {
	return u.Update(func(s *VideoModelUpsert) {
		s.UpdateLimits()
	})
}

// SetSupportedOptions sets the "supported_options" field.
func (u *VideoModelUpsertOne) SetSupportedOptions(v map[string]interface{}) *VideoModelUpsertOne {
	return u.Update(func(s *VideoModelUpsert) {
		s.SetSupportedOptions(v)
	})
}

// UpdateSupportedOptions sets the "supported_options" field to the value that was provided on create.
func (u *VideoModelUpsertOne) UpdateSupportedOptions() *VideoModelUpsertOne {
	return u.Update(func(s *VideoModelUpsert) {
		s.UpdateSupportedOptions()
	})
}

// SetExtraBodyAllow sets the "extra_body_allow" field.
func (u *VideoModelUpsertOne) SetExtraBodyAllow(v []string) *VideoModelUpsertOne {
	return u.Update(func(s *VideoModelUpsert) {
		s.SetExtraBodyAllow(v)
	})
}

// UpdateExtraBodyAllow sets the "extra_body_allow" field to the value that was provided on create.
func (u *VideoModelUpsertOne) UpdateExtraBodyAllow() *VideoModelUpsertOne {
	return u.Update(func(s *VideoModelUpsert) {
		s.UpdateExtraBodyAllow()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *VideoModelUpsertOne) SetSortOrder(v int) *VideoModelUpsertOne {
	return u.Update(func(s *VideoModelUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *VideoModelUpsertOne) AddSortOrder(v int) *VideoModelUpsertOne {
	return u.Update(func(s *VideoModelUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *VideoModelUpsertOne) UpdateSortOrder() *VideoModelUpsertOne {
	return u.Update(func(s *VideoModelUpsert) {
		s.UpdateSortOrder()
	})
}

// Exec executes the query.
func (u *VideoModelUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for VideoModelCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *VideoModelUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *VideoModelUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *VideoModelUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// VideoModelCreateBulk is the builder for creating many VideoModel entities in bulk.
type VideoModelCreateBulk struct {
	config
	err      error
	builders []*VideoModelCreate
	conflict []sql.ConflictOption
}

// Save creates the VideoModel entities in the database.
func (_c *VideoModelCreateBulk) Save(ctx context.Context) ([]*VideoModel, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*VideoModel, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*VideoModelMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *VideoModelCreateBulk) SaveX(ctx context.Context) []*VideoModel {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VideoModelCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VideoModelCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.VideoModel.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.VideoModelUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *VideoModelCreateBulk) OnConflict(opts ...sql.ConflictOption) *VideoModelUpsertBulk {
	_c.conflict = opts
	return &VideoModelUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.VideoModel.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *VideoModelCreateBulk) OnConflictColumns(columns ...string) *VideoModelUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &VideoModelUpsertBulk{
		create: _c,
	}
}

// VideoModelUpsertBulk is the builder for "upsert"-ing
// a bulk of VideoModel nodes.
type VideoModelUpsertBulk struct {
	create *VideoModelCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.VideoModel.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *VideoModelUpsertBulk) UpdateNewValues() *VideoModelUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(videomodel.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.VideoModel.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *VideoModelUpsertBulk) Ignore() *VideoModelUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *VideoModelUpsertBulk) DoNothing() *VideoModelUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the VideoModelCreateBulk.OnConflict
// documentation for more info.
func (u *VideoModelUpsertBulk) Update(set func(*VideoModelUpsert)) *VideoModelUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&VideoModelUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *VideoModelUpsertBulk) SetUpdatedAt(v time.Time) *VideoModelUpsertBulk {
	return u.Update(func(s *VideoModelUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *VideoModelUpsertBulk) UpdateUpdatedAt() *VideoModelUpsertBulk {
	return u.Update(func(s *VideoModelUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetPublicModel sets the "public_model" field.
func (u *VideoModelUpsertBulk) SetPublicModel(v string) *VideoModelUpsertBulk {
	return u.Update(func(s *VideoModelUpsert) {
		s.SetPublicModel(v)
	})
}

// UpdatePublicModel sets the "public_model" field to the value that was provided on create.
func (u *VideoModelUpsertBulk) UpdatePublicModel() *VideoModelUpsertBulk {
	return u.Update(func(s *VideoModelUpsert) {
		s.UpdatePublicModel()
	})
}

// SetDisplayName sets the "display_name" field.
func (u *VideoModelUpsertBulk) SetDisplayName(v string) *VideoModelUpsertBulk {
	return u.Update(func(s *VideoModelUpsert) {
		s.SetDisplayName(v)
	})
}

// UpdateDisplayName sets the "display_name" field to the value that was provided on create.
func (u *VideoModelUpsertBulk) UpdateDisplayName() *VideoModelUpsertBulk {
	return u.Update(func(s *VideoModelUpsert) {
		s.UpdateDisplayName()
	})
}

// ClearDisplayName clears the value of the "display_name" field.
func (u *VideoModelUpsertBulk) ClearDisplayName() *VideoModelUpsertBulk {
	return u.Update(func(s *VideoModelUpsert) {
		s.ClearDisplayName()
	})
}

// SetTemplateID sets the "template_id" field.
func (u *VideoModelUpsertBulk) SetTemplateID(v int64) *VideoModelUpsertBulk {
	return u.Update(func(s *VideoModelUpsert) {
		s.SetTemplateID(v)
	})
}

// UpdateTemplateID sets the "template_id" field to the value that was provided on create.
func (u *VideoModelUpsertBulk) UpdateTemplateID() *VideoModelUpsertBulk {
	return u.Update(func(s *VideoModelUpsert) {
		s.UpdateTemplateID()
	})
}

// SetUpstreamModelID sets the "upstream_model_id" field.
func (u *VideoModelUpsertBulk) SetUpstreamModelID(v string) *VideoModelUpsertBulk {
	return u.Update(func(s *VideoModelUpsert) {
		s.SetUpstreamModelID(v)
	})
}

// UpdateUpstreamModelID sets the "upstream_model_id" field to the value that was provided on create.
func (u *VideoModelUpsertBulk) UpdateUpstreamModelID() *VideoModelUpsertBulk {
	return u.Update(func(s *VideoModelUpsert) {
		s.UpdateUpstreamModelID()
	})
}

// ClearUpstreamModelID clears the value of the "upstream_model_id" field.
func (u *VideoModelUpsertBulk) ClearUpstreamModelID() *VideoModelUpsertBulk {
	return u.Update(func(s *VideoModelUpsert) {
		s.ClearUpstreamModelID()
	})
}

// SetRequestShape sets the "request_shape" field.
func (u *VideoModelUpsertBulk) SetRequestShape(v string) *VideoModelUpsertBulk {
	return u.Update(func(s *VideoModelUpsert) {
		s.SetRequestShape(v)
	})
}

// UpdateRequestShape sets the "request_shape" field to the value that was provided on create.
func (u *VideoModelUpsertBulk) UpdateRequestShape() *VideoModelUpsertBulk {
	return u.Update(func(s *VideoModelUpsert) {
		s.UpdateRequestShape()
	})
}

// SetStatus sets the "status" field.
func (u *VideoModelUpsertBulk) SetStatus(v string) *VideoModelUpsertBulk {
	return u.Update(func(s *VideoModelUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *VideoModelUpsertBulk) UpdateStatus() *VideoModelUpsertBulk {
	return u.Update(func(s *VideoModelUpsert) {
		s.UpdateStatus()
	})
}

// SetCapabilities sets the "capabilities" field.
func (u *VideoModelUpsertBulk) SetCapabilities(v map[string]interface{}) *VideoModelUpsertBulk {
	return u.Update(func(s *VideoModelUpsert) {
		s.SetCapabilities(v)
	})
}

// UpdateCapabilities sets the "capabilities" field to the value that was provided on create.
func (u *VideoModelUpsertBulk) UpdateCapabilities() *VideoModelUpsertBulk {
	return u.Update(func(s *VideoModelUpsert) {
		s.UpdateCapabilities()
	})
}

// SetDefaults sets the "defaults" field.
func (u *VideoModelUpsertBulk) SetDefaults(v map[string]interface{}) *VideoModelUpsertBulk {
	return u.Update(func(s *VideoModelUpsert) {
		s.SetDefaults(v)
	})
}

// UpdateDefaults sets the "defaults" field to the value that was provided on create.
func (u *VideoModelUpsertBulk) UpdateDefaults() *VideoModelUpsertBulk {
	return u.Update(func(s *VideoModelUpsert) {
		s.UpdateDefaults()
	})
}

// SetLimits sets the "limits" field.
func (u *VideoModelUpsertBulk) SetLimits(v map[string]interface{}) *VideoModelUpsertBulk {
	return u.Update(func(s *VideoModelUpsert) {
		s.SetLimits(v)
	})
}

// UpdateLimits sets the "limits" field to the value that was provided on create.
func (u *VideoModelUpsertBulk) UpdateLimits() *VideoModelUpsertBulk {
	return u.Update(func(s *VideoModelUpsert) {
		s.UpdateLimits()
	})
}

// SetSupportedOptions sets the "supported_options" field.
func (u *VideoModelUpsertBulk) SetSupportedOptions(v map[string]interface{}) *VideoModelUpsertBulk {
	return u.Update(func(s *VideoModelUpsert) {
		s.SetSupportedOptions(v)
	})
}

// UpdateSupportedOptions sets the "supported_options" field to the value that was provided on create.
func (u *VideoModelUpsertBulk) UpdateSupportedOptions() *VideoModelUpsertBulk {
	return u.Update(func(s *VideoModelUpsert) {
		s.UpdateSupportedOptions()
	})
}

// SetExtraBodyAllow sets the "extra_body_allow" field.
func (u *VideoModelUpsertBulk) SetExtraBodyAllow(v []string) *VideoModelUpsertBulk {
	return u.Update(func(s *VideoModelUpsert) {
		s.SetExtraBodyAllow(v)
	})
}

// UpdateExtraBodyAllow sets the "extra_body_allow" field to the value that was provided on create.
func (u *VideoModelUpsertBulk) UpdateExtraBodyAllow() *VideoModelUpsertBulk {
	return u.Update(func(s *VideoModelUpsert) {
		s.UpdateExtraBodyAllow()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *VideoModelUpsertBulk) SetSortOrder(v int) *VideoModelUpsertBulk {
	return u.Update(func(s *VideoModelUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *VideoModelUpsertBulk) AddSortOrder(v int) *VideoModelUpsertBulk {
	return u.Update(func(s *VideoModelUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *VideoModelUpsertBulk) UpdateSortOrder() *VideoModelUpsertBulk {
	return u.Update(func(s *VideoModelUpsert) {
		s.UpdateSortOrder()
	})
}

// Exec executes the query.
func (u *VideoModelUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the VideoModelCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for VideoModelCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *VideoModelUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
