// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/ccapi/ent/predicate"
	"github.com/Wei-Shaw/ccapi/ent/videogenerationtask"
)

// VideoGenerationTaskDelete is the builder for deleting a VideoGenerationTask entity.
type VideoGenerationTaskDelete struct {
	config
	hooks    []Hook
	mutation *VideoGenerationTaskMutation
}

// Where appends a list predicates to the VideoGenerationTaskDelete builder.
func (_d *VideoGenerationTaskDelete) Where(ps ...predicate.VideoGenerationTask) *VideoGenerationTaskDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *VideoGenerationTaskDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *VideoGenerationTaskDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *VideoGenerationTaskDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(videogenerationtask.Table, sqlgraph.NewFieldSpec(videogenerationtask.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// VideoGenerationTaskDeleteOne is the builder for deleting a single VideoGenerationTask entity.
type VideoGenerationTaskDeleteOne struct {
	_d *VideoGenerationTaskDelete
}

// Where appends a list predicates to the VideoGenerationTaskDelete builder.
func (_d *VideoGenerationTaskDeleteOne) Where(ps ...predicate.VideoGenerationTask) *VideoGenerationTaskDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *VideoGenerationTaskDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{videogenerationtask.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *VideoGenerationTaskDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
