// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/ccapi/ent/account"
	"github.com/Wei-Shaw/ccapi/ent/apikey"
	"github.com/Wei-Shaw/ccapi/ent/group"
	"github.com/Wei-Shaw/ccapi/ent/user"
	"github.com/Wei-Shaw/ccapi/ent/videogenerationtask"
	"github.com/Wei-Shaw/ccapi/ent/videomodel"
)

// VideoGenerationTask is the model entity for the VideoGenerationTask schema.
type VideoGenerationTask struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// PublicID holds the value of the "public_id" field.
	PublicID string `json:"public_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// APIKeyID holds the value of the "api_key_id" field.
	APIKeyID int64 `json:"api_key_id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID *int64 `json:"group_id,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID int64 `json:"account_id,omitempty"`
	// ChannelID holds the value of the "channel_id" field.
	ChannelID *int64 `json:"channel_id,omitempty"`
	// VideoModelID holds the value of the "video_model_id" field.
	VideoModelID int64 `json:"video_model_id,omitempty"`
	// RequestedModel holds the value of the "requested_model" field.
	RequestedModel string `json:"requested_model,omitempty"`
	// UpstreamModel holds the value of the "upstream_model" field.
	UpstreamModel string `json:"upstream_model,omitempty"`
	// UpstreamTaskID holds the value of the "upstream_task_id" field.
	UpstreamTaskID *string `json:"upstream_task_id,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Progress holds the value of the "progress" field.
	Progress int `json:"progress,omitempty"`
	// BillingState holds the value of the "billing_state" field.
	BillingState string `json:"billing_state,omitempty"`
	// RequestPayload holds the value of the "request_payload" field.
	RequestPayload map[string]interface{} `json:"request_payload,omitempty"`
	// UpstreamRequestPayload holds the value of the "upstream_request_payload" field.
	UpstreamRequestPayload map[string]interface{} `json:"upstream_request_payload,omitempty"`
	// UpstreamResponsePayload holds the value of the "upstream_response_payload" field.
	UpstreamResponsePayload map[string]interface{} `json:"upstream_response_payload,omitempty"`
	// ResultPayload holds the value of the "result_payload" field.
	ResultPayload map[string]interface{} `json:"result_payload,omitempty"`
	// ErrorCode holds the value of the "error_code" field.
	ErrorCode *string `json:"error_code,omitempty"`
	// ErrorMessage holds the value of the "error_message" field.
	ErrorMessage *string `json:"error_message,omitempty"`
	// ContentURL holds the value of the "content_url" field.
	ContentURL *string `json:"content_url,omitempty"`
	// UpstreamContentURL holds the value of the "upstream_content_url" field.
	UpstreamContentURL *string `json:"upstream_content_url,omitempty"`
	// LocalContentURL holds the value of the "local_content_url" field.
	LocalContentURL *string `json:"local_content_url,omitempty"`
	// BillingMode holds the value of the "billing_mode" field.
	BillingMode string `json:"billing_mode,omitempty"`
	// UnitPrice holds the value of the "unit_price" field.
	UnitPrice float64 `json:"unit_price,omitempty"`
	// UnitSeconds holds the value of the "unit_seconds" field.
	UnitSeconds *float64 `json:"unit_seconds,omitempty"`
	// RequestedSeconds holds the value of the "requested_seconds" field.
	RequestedSeconds *int `json:"requested_seconds,omitempty"`
	// BillableSeconds holds the value of the "billable_seconds" field.
	BillableSeconds *int `json:"billable_seconds,omitempty"`
	// ReservedCost holds the value of the "reserved_cost" field.
	ReservedCost float64 `json:"reserved_cost,omitempty"`
	// EstimatedCost holds the value of the "estimated_cost" field.
	EstimatedCost float64 `json:"estimated_cost,omitempty"`
	// ActualCost holds the value of the "actual_cost" field.
	ActualCost float64 `json:"actual_cost,omitempty"`
	// IdempotencyKey holds the value of the "idempotency_key" field.
	IdempotencyKey *string `json:"idempotency_key,omitempty"`
	// SubmittedAt holds the value of the "submitted_at" field.
	SubmittedAt *time.Time `json:"submitted_at,omitempty"`
	// StartedAt holds the value of the "started_at" field.
	StartedAt *time.Time `json:"started_at,omitempty"`
	// CompletedAt holds the value of the "completed_at" field.
	CompletedAt *time.Time `json:"completed_at,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	// NextPollAt holds the value of the "next_poll_at" field.
	NextPollAt *time.Time `json:"next_poll_at,omitempty"`
	// PollCount holds the value of the "poll_count" field.
	PollCount int `json:"poll_count,omitempty"`
	// LockedUntil holds the value of the "locked_until" field.
	LockedUntil *time.Time `json:"locked_until,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the VideoGenerationTaskQuery when eager-loading is set.
	Edges        VideoGenerationTaskEdges `json:"edges"`
	selectValues sql.SelectValues
}

// VideoGenerationTaskEdges holds the relations/edges for other nodes in the graph.
type VideoGenerationTaskEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// APIKey holds the value of the api_key edge.
	APIKey *APIKey `json:"api_key,omitempty"`
	// Account holds the value of the account edge.
	Account *Account `json:"account,omitempty"`
	// Group holds the value of the group edge.
	Group *Group `json:"group,omitempty"`
	// VideoModel holds the value of the video_model edge.
	VideoModel *VideoModel `json:"video_model,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [5]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e VideoGenerationTaskEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// APIKeyOrErr returns the APIKey value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e VideoGenerationTaskEdges) APIKeyOrErr() (*APIKey, error) {
	if e.APIKey != nil {
		return e.APIKey, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: apikey.Label}
	}
	return nil, &NotLoadedError{edge: "api_key"}
}

// AccountOrErr returns the Account value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e VideoGenerationTaskEdges) AccountOrErr() (*Account, error) {
	if e.Account != nil {
		return e.Account, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: account.Label}
	}
	return nil, &NotLoadedError{edge: "account"}
}

// GroupOrErr returns the Group value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e VideoGenerationTaskEdges) GroupOrErr() (*Group, error) {
	if e.Group != nil {
		return e.Group, nil
	} else if e.loadedTypes[3] {
		return nil, &NotFoundError{label: group.Label}
	}
	return nil, &NotLoadedError{edge: "group"}
}

// VideoModelOrErr returns the VideoModel value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e VideoGenerationTaskEdges) VideoModelOrErr() (*VideoModel, error) {
	if e.VideoModel != nil {
		return e.VideoModel, nil
	} else if e.loadedTypes[4] {
		return nil, &NotFoundError{label: videomodel.Label}
	}
	return nil, &NotLoadedError{edge: "video_model"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*VideoGenerationTask) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case videogenerationtask.FieldRequestPayload, videogenerationtask.FieldUpstreamRequestPayload, videogenerationtask.FieldUpstreamResponsePayload, videogenerationtask.FieldResultPayload:
			values[i] = new([]byte)
		case videogenerationtask.FieldUnitPrice, videogenerationtask.FieldUnitSeconds, videogenerationtask.FieldReservedCost, videogenerationtask.FieldEstimatedCost, videogenerationtask.FieldActualCost:
			values[i] = new(sql.NullFloat64)
		case videogenerationtask.FieldID, videogenerationtask.FieldUserID, videogenerationtask.FieldAPIKeyID, videogenerationtask.FieldGroupID, videogenerationtask.FieldAccountID, videogenerationtask.FieldChannelID, videogenerationtask.FieldVideoModelID, videogenerationtask.FieldProgress, videogenerationtask.FieldRequestedSeconds, videogenerationtask.FieldBillableSeconds, videogenerationtask.FieldPollCount:
			values[i] = new(sql.NullInt64)
		case videogenerationtask.FieldPublicID, videogenerationtask.FieldRequestedModel, videogenerationtask.FieldUpstreamModel, videogenerationtask.FieldUpstreamTaskID, videogenerationtask.FieldStatus, videogenerationtask.FieldBillingState, videogenerationtask.FieldErrorCode, videogenerationtask.FieldErrorMessage, videogenerationtask.FieldContentURL, videogenerationtask.FieldUpstreamContentURL, videogenerationtask.FieldLocalContentURL, videogenerationtask.FieldBillingMode, videogenerationtask.FieldIdempotencyKey:
			values[i] = new(sql.NullString)
		case videogenerationtask.FieldSubmittedAt, videogenerationtask.FieldStartedAt, videogenerationtask.FieldCompletedAt, videogenerationtask.FieldExpiresAt, videogenerationtask.FieldNextPollAt, videogenerationtask.FieldLockedUntil, videogenerationtask.FieldCreatedAt, videogenerationtask.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the VideoGenerationTask fields.
func (_m *VideoGenerationTask) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case videogenerationtask.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case videogenerationtask.FieldPublicID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field public_id", values[i])
			} else if value.Valid {
				_m.PublicID = value.String
			}
		case videogenerationtask.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case videogenerationtask.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				_m.APIKeyID = value.Int64
			}
		case videogenerationtask.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = new(int64)
				*_m.GroupID = value.Int64
			}
		case videogenerationtask.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.Int64
			}
		case videogenerationtask.FieldChannelID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field channel_id", values[i])
			} else if value.Valid {
				_m.ChannelID = new(int64)
				*_m.ChannelID = value.Int64
			}
		case videogenerationtask.FieldVideoModelID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field video_model_id", values[i])
			} else if value.Valid {
				_m.VideoModelID = value.Int64
			}
		case videogenerationtask.FieldRequestedModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field requested_model", values[i])
			} else if value.Valid {
				_m.RequestedModel = value.String
			}
		case videogenerationtask.FieldUpstreamModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_model", values[i])
			} else if value.Valid {
				_m.UpstreamModel = value.String
			}
		case videogenerationtask.FieldUpstreamTaskID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_task_id", values[i])
			} else if value.Valid {
				_m.UpstreamTaskID = new(string)
				*_m.UpstreamTaskID = value.String
			}
		case videogenerationtask.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case videogenerationtask.FieldProgress:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field progress", values[i])
			} else if value.Valid {
				_m.Progress = int(value.Int64)
			}
		case videogenerationtask.FieldBillingState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field billing_state", values[i])
			} else if value.Valid {
				_m.BillingState = value.String
			}
		case videogenerationtask.FieldRequestPayload:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field request_payload", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.RequestPayload); err != nil {
					return fmt.Errorf("unmarshal field request_payload: %w", err)
				}
			}
		case videogenerationtask.FieldUpstreamRequestPayload:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_request_payload", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.UpstreamRequestPayload); err != nil {
					return fmt.Errorf("unmarshal field upstream_request_payload: %w", err)
				}
			}
		case videogenerationtask.FieldUpstreamResponsePayload:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_response_payload", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.UpstreamResponsePayload); err != nil {
					return fmt.Errorf("unmarshal field upstream_response_payload: %w", err)
				}
			}
		case videogenerationtask.FieldResultPayload:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field result_payload", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ResultPayload); err != nil {
					return fmt.Errorf("unmarshal field result_payload: %w", err)
				}
			}
		case videogenerationtask.FieldErrorCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_code", values[i])
			} else if value.Valid {
				_m.ErrorCode = new(string)
				*_m.ErrorCode = value.String
			}
		case videogenerationtask.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				_m.ErrorMessage = new(string)
				*_m.ErrorMessage = value.String
			}
		case videogenerationtask.FieldContentURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content_url", values[i])
			} else if value.Valid {
				_m.ContentURL = new(string)
				*_m.ContentURL = value.String
			}
		case videogenerationtask.FieldUpstreamContentURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_content_url", values[i])
			} else if value.Valid {
				_m.UpstreamContentURL = new(string)
				*_m.UpstreamContentURL = value.String
			}
		case videogenerationtask.FieldLocalContentURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field local_content_url", values[i])
			} else if value.Valid {
				_m.LocalContentURL = new(string)
				*_m.LocalContentURL = value.String
			}
		case videogenerationtask.FieldBillingMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field billing_mode", values[i])
			} else if value.Valid {
				_m.BillingMode = value.String
			}
		case videogenerationtask.FieldUnitPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field unit_price", values[i])
			} else if value.Valid {
				_m.UnitPrice = value.Float64
			}
		case videogenerationtask.FieldUnitSeconds:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field unit_seconds", values[i])
			} else if value.Valid {
				_m.UnitSeconds = new(float64)
				*_m.UnitSeconds = value.Float64
			}
		case videogenerationtask.FieldRequestedSeconds:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field requested_seconds", values[i])
			} else if value.Valid {
				_m.RequestedSeconds = new(int)
				*_m.RequestedSeconds = int(value.Int64)
			}
		case videogenerationtask.FieldBillableSeconds:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field billable_seconds", values[i])
			} else if value.Valid {
				_m.BillableSeconds = new(int)
				*_m.BillableSeconds = int(value.Int64)
			}
		case videogenerationtask.FieldReservedCost:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field reserved_cost", values[i])
			} else if value.Valid {
				_m.ReservedCost = value.Float64
			}
		case videogenerationtask.FieldEstimatedCost:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field estimated_cost", values[i])
			} else if value.Valid {
				_m.EstimatedCost = value.Float64
			}
		case videogenerationtask.FieldActualCost:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field actual_cost", values[i])
			} else if value.Valid {
				_m.ActualCost = value.Float64
			}
		case videogenerationtask.FieldIdempotencyKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field idempotency_key", values[i])
			} else if value.Valid {
				_m.IdempotencyKey = new(string)
				*_m.IdempotencyKey = value.String
			}
		case videogenerationtask.FieldSubmittedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field submitted_at", values[i])
			} else if value.Valid {
				_m.SubmittedAt = new(time.Time)
				*_m.SubmittedAt = value.Time
			}
		case videogenerationtask.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = new(time.Time)
				*_m.StartedAt = value.Time
			}
		case videogenerationtask.FieldCompletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field completed_at", values[i])
			} else if value.Valid {
				_m.CompletedAt = new(time.Time)
				*_m.CompletedAt = value.Time
			}
		case videogenerationtask.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = new(time.Time)
				*_m.ExpiresAt = value.Time
			}
		case videogenerationtask.FieldNextPollAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field next_poll_at", values[i])
			} else if value.Valid {
				_m.NextPollAt = new(time.Time)
				*_m.NextPollAt = value.Time
			}
		case videogenerationtask.FieldPollCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field poll_count", values[i])
			} else if value.Valid {
				_m.PollCount = int(value.Int64)
			}
		case videogenerationtask.FieldLockedUntil:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field locked_until", values[i])
			} else if value.Valid {
				_m.LockedUntil = new(time.Time)
				*_m.LockedUntil = value.Time
			}
		case videogenerationtask.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case videogenerationtask.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the VideoGenerationTask.
// This includes values selected through modifiers, order, etc.
func (_m *VideoGenerationTask) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the VideoGenerationTask entity.
func (_m *VideoGenerationTask) QueryUser() *UserQuery {
	return NewVideoGenerationTaskClient(_m.config).QueryUser(_m)
}

// QueryAPIKey queries the "api_key" edge of the VideoGenerationTask entity.
func (_m *VideoGenerationTask) QueryAPIKey() *APIKeyQuery {
	return NewVideoGenerationTaskClient(_m.config).QueryAPIKey(_m)
}

// QueryAccount queries the "account" edge of the VideoGenerationTask entity.
func (_m *VideoGenerationTask) QueryAccount() *AccountQuery {
	return NewVideoGenerationTaskClient(_m.config).QueryAccount(_m)
}

// QueryGroup queries the "group" edge of the VideoGenerationTask entity.
func (_m *VideoGenerationTask) QueryGroup() *GroupQuery {
	return NewVideoGenerationTaskClient(_m.config).QueryGroup(_m)
}

// QueryVideoModel queries the "video_model" edge of the VideoGenerationTask entity.
func (_m *VideoGenerationTask) QueryVideoModel() *VideoModelQuery {
	return NewVideoGenerationTaskClient(_m.config).QueryVideoModel(_m)
}

// Update returns a builder for updating this VideoGenerationTask.
// Note that you need to call VideoGenerationTask.Unwrap() before calling this method if this VideoGenerationTask
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *VideoGenerationTask) Update() *VideoGenerationTaskUpdateOne {
	return NewVideoGenerationTaskClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the VideoGenerationTask entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *VideoGenerationTask) Unwrap() *VideoGenerationTask {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: VideoGenerationTask is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *VideoGenerationTask) String() string {
	var builder strings.Builder
	builder.WriteString("VideoGenerationTask(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("public_id=")
	builder.WriteString(_m.PublicID)
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("api_key_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.APIKeyID))
	builder.WriteString(", ")
	if v := _m.GroupID; v != nil {
		builder.WriteString("group_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	if v := _m.ChannelID; v != nil {
		builder.WriteString("channel_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("video_model_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.VideoModelID))
	builder.WriteString(", ")
	builder.WriteString("requested_model=")
	builder.WriteString(_m.RequestedModel)
	builder.WriteString(", ")
	builder.WriteString("upstream_model=")
	builder.WriteString(_m.UpstreamModel)
	builder.WriteString(", ")
	if v := _m.UpstreamTaskID; v != nil {
		builder.WriteString("upstream_task_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("progress=")
	builder.WriteString(fmt.Sprintf("%v", _m.Progress))
	builder.WriteString(", ")
	builder.WriteString("billing_state=")
	builder.WriteString(_m.BillingState)
	builder.WriteString(", ")
	builder.WriteString("request_payload=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequestPayload))
	builder.WriteString(", ")
	builder.WriteString("upstream_request_payload=")
	builder.WriteString(fmt.Sprintf("%v", _m.UpstreamRequestPayload))
	builder.WriteString(", ")
	builder.WriteString("upstream_response_payload=")
	builder.WriteString(fmt.Sprintf("%v", _m.UpstreamResponsePayload))
	builder.WriteString(", ")
	builder.WriteString("result_payload=")
	builder.WriteString(fmt.Sprintf("%v", _m.ResultPayload))
	builder.WriteString(", ")
	if v := _m.ErrorCode; v != nil {
		builder.WriteString("error_code=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ErrorMessage; v != nil {
		builder.WriteString("error_message=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ContentURL; v != nil {
		builder.WriteString("content_url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.UpstreamContentURL; v != nil {
		builder.WriteString("upstream_content_url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.LocalContentURL; v != nil {
		builder.WriteString("local_content_url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("billing_mode=")
	builder.WriteString(_m.BillingMode)
	builder.WriteString(", ")
	builder.WriteString("unit_price=")
	builder.WriteString(fmt.Sprintf("%v", _m.UnitPrice))
	builder.WriteString(", ")
	if v := _m.UnitSeconds; v != nil {
		builder.WriteString("unit_seconds=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.RequestedSeconds; v != nil {
		builder.WriteString("requested_seconds=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.BillableSeconds; v != nil {
		builder.WriteString("billable_seconds=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("reserved_cost=")
	builder.WriteString(fmt.Sprintf("%v", _m.ReservedCost))
	builder.WriteString(", ")
	builder.WriteString("estimated_cost=")
	builder.WriteString(fmt.Sprintf("%v", _m.EstimatedCost))
	builder.WriteString(", ")
	builder.WriteString("actual_cost=")
	builder.WriteString(fmt.Sprintf("%v", _m.ActualCost))
	builder.WriteString(", ")
	if v := _m.IdempotencyKey; v != nil {
		builder.WriteString("idempotency_key=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.SubmittedAt; v != nil {
		builder.WriteString("submitted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.StartedAt; v != nil {
		builder.WriteString("started_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.CompletedAt; v != nil {
		builder.WriteString("completed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ExpiresAt; v != nil {
		builder.WriteString("expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.NextPollAt; v != nil {
		builder.WriteString("next_poll_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("poll_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.PollCount))
	builder.WriteString(", ")
	if v := _m.LockedUntil; v != nil {
		builder.WriteString("locked_until=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// VideoGenerationTasks is a parsable slice of VideoGenerationTask.
type VideoGenerationTasks []*VideoGenerationTask
