// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/ccapi/ent/predicate"
	"github.com/Wei-Shaw/ccapi/ent/videocalltemplate"
	"github.com/Wei-Shaw/ccapi/ent/videogenerationtask"
	"github.com/Wei-Shaw/ccapi/ent/videomodel"
)

// VideoModelUpdate is the builder for updating VideoModel entities.
type VideoModelUpdate struct {
	config
	hooks    []Hook
	mutation *VideoModelMutation
}

// Where appends a list predicates to the VideoModelUpdate builder.
func (_u *VideoModelUpdate) Where(ps ...predicate.VideoModel) *VideoModelUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *VideoModelUpdate) SetUpdatedAt(v time.Time) *VideoModelUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetPublicModel sets the "public_model" field.
func (_u *VideoModelUpdate) SetPublicModel(v string) *VideoModelUpdate {
	_u.mutation.SetPublicModel(v)
	return _u
}

// SetNillablePublicModel sets the "public_model" field if the given value is not nil.
func (_u *VideoModelUpdate) SetNillablePublicModel(v *string) *VideoModelUpdate {
	if v != nil {
		_u.SetPublicModel(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *VideoModelUpdate) SetDisplayName(v string) *VideoModelUpdate {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *VideoModelUpdate) SetNillableDisplayName(v *string) *VideoModelUpdate {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// ClearDisplayName clears the value of the "display_name" field.
func (_u *VideoModelUpdate) ClearDisplayName() *VideoModelUpdate {
	_u.mutation.ClearDisplayName()
	return _u
}

// SetTemplateID sets the "template_id" field.
func (_u *VideoModelUpdate) SetTemplateID(v int64) *VideoModelUpdate {
	_u.mutation.SetTemplateID(v)
	return _u
}

// SetNillableTemplateID sets the "template_id" field if the given value is not nil.
func (_u *VideoModelUpdate) SetNillableTemplateID(v *int64) *VideoModelUpdate {
	if v != nil {
		_u.SetTemplateID(*v)
	}
	return _u
}

// SetUpstreamModelID sets the "upstream_model_id" field.
func (_u *VideoModelUpdate) SetUpstreamModelID(v string) *VideoModelUpdate {
	_u.mutation.SetUpstreamModelID(v)
	return _u
}

// SetNillableUpstreamModelID sets the "upstream_model_id" field if the given value is not nil.
func (_u *VideoModelUpdate) SetNillableUpstreamModelID(v *string) *VideoModelUpdate {
	if v != nil {
		_u.SetUpstreamModelID(*v)
	}
	return _u
}

// ClearUpstreamModelID clears the value of the "upstream_model_id" field.
func (_u *VideoModelUpdate) ClearUpstreamModelID() *VideoModelUpdate {
	_u.mutation.ClearUpstreamModelID()
	return _u
}

// SetRequestShape sets the "request_shape" field.
func (_u *VideoModelUpdate) SetRequestShape(v string) *VideoModelUpdate {
	_u.mutation.SetRequestShape(v)
	return _u
}

// SetNillableRequestShape sets the "request_shape" field if the given value is not nil.
func (_u *VideoModelUpdate) SetNillableRequestShape(v *string) *VideoModelUpdate {
	if v != nil {
		_u.SetRequestShape(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *VideoModelUpdate) SetStatus(v string) *VideoModelUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *VideoModelUpdate) SetNillableStatus(v *string) *VideoModelUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCapabilities sets the "capabilities" field.
func (_u *VideoModelUpdate) SetCapabilities(v map[string]interface{}) *VideoModelUpdate {
	_u.mutation.SetCapabilities(v)
	return _u
}

// SetDefaults sets the "defaults" field.
func (_u *VideoModelUpdate) SetDefaults(v map[string]interface{}) *VideoModelUpdate {
	_u.mutation.SetDefaults(v)
	return _u
}

// SetLimits sets the "limits" field.
func (_u *VideoModelUpdate) SetLimits(v map[string]interface{}) *VideoModelUpdate {
	_u.mutation.SetLimits(v)
	return _u
}

// SetSupportedOptions sets the "supported_options" field.
func (_u *VideoModelUpdate) SetSupportedOptions(v map[string]interface{}) *VideoModelUpdate {
	_u.mutation.SetSupportedOptions(v)
	return _u
}

// SetExtraBodyAllow sets the "extra_body_allow" field.
func (_u *VideoModelUpdate) SetExtraBodyAllow(v []string) *VideoModelUpdate {
	_u.mutation.SetExtraBodyAllow(v)
	return _u
}

// AppendExtraBodyAllow appends value to the "extra_body_allow" field.
func (_u *VideoModelUpdate) AppendExtraBodyAllow(v []string) *VideoModelUpdate {
	_u.mutation.AppendExtraBodyAllow(v)
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *VideoModelUpdate) SetSortOrder(v int) *VideoModelUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *VideoModelUpdate) SetNillableSortOrder(v *int) *VideoModelUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *VideoModelUpdate) AddSortOrder(v int) *VideoModelUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetTemplate sets the "template" edge to the VideoCallTemplate entity.
func (_u *VideoModelUpdate) SetTemplate(v *VideoCallTemplate) *VideoModelUpdate {
	return _u.SetTemplateID(v.ID)
}

// AddTaskIDs adds the "tasks" edge to the VideoGenerationTask entity by IDs.
func (_u *VideoModelUpdate) AddTaskIDs(ids ...int64) *VideoModelUpdate {
	_u.mutation.AddTaskIDs(ids...)
	return _u
}

// AddTasks adds the "tasks" edges to the VideoGenerationTask entity.
func (_u *VideoModelUpdate) AddTasks(v ...*VideoGenerationTask) *VideoModelUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTaskIDs(ids...)
}

// Mutation returns the VideoModelMutation object of the builder.
func (_u *VideoModelUpdate) Mutation() *VideoModelMutation {
	return _u.mutation
}

// ClearTemplate clears the "template" edge to the VideoCallTemplate entity.
func (_u *VideoModelUpdate) ClearTemplate() *VideoModelUpdate {
	_u.mutation.ClearTemplate()
	return _u
}

// ClearTasks clears all "tasks" edges to the VideoGenerationTask entity.
func (_u *VideoModelUpdate) ClearTasks() *VideoModelUpdate {
	_u.mutation.ClearTasks()
	return _u
}

// RemoveTaskIDs removes the "tasks" edge to VideoGenerationTask entities by IDs.
func (_u *VideoModelUpdate) RemoveTaskIDs(ids ...int64) *VideoModelUpdate {
	_u.mutation.RemoveTaskIDs(ids...)
	return _u
}

// RemoveTasks removes "tasks" edges to VideoGenerationTask entities.
func (_u *VideoModelUpdate) RemoveTasks(v ...*VideoGenerationTask) *VideoModelUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTaskIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *VideoModelUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VideoModelUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *VideoModelUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VideoModelUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *VideoModelUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := videomodel.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *VideoModelUpdate) check() error {
	if v, ok := _u.mutation.PublicModel(); ok {
		if err := videomodel.PublicModelValidator(v); err != nil {
			return &ValidationError{Name: "public_model", err: fmt.Errorf(`ent: validator failed for field "VideoModel.public_model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DisplayName(); ok {
		if err := videomodel.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "VideoModel.display_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamModelID(); ok {
		if err := videomodel.UpstreamModelIDValidator(v); err != nil {
			return &ValidationError{Name: "upstream_model_id", err: fmt.Errorf(`ent: validator failed for field "VideoModel.upstream_model_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestShape(); ok {
		if err := videomodel.RequestShapeValidator(v); err != nil {
			return &ValidationError{Name: "request_shape", err: fmt.Errorf(`ent: validator failed for field "VideoModel.request_shape": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := videomodel.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "VideoModel.status": %w`, err)}
		}
	}
	if _u.mutation.TemplateCleared() && len(_u.mutation.TemplateIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "VideoModel.template"`)
	}
	return nil
}

func (_u *VideoModelUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(videomodel.Table, videomodel.Columns, sqlgraph.NewFieldSpec(videomodel.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(videomodel.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PublicModel(); ok {
		_spec.SetField(videomodel.FieldPublicModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(videomodel.FieldDisplayName, field.TypeString, value)
	}
	if _u.mutation.DisplayNameCleared() {
		_spec.ClearField(videomodel.FieldDisplayName, field.TypeString)
	}
	if value, ok := _u.mutation.UpstreamModelID(); ok {
		_spec.SetField(videomodel.FieldUpstreamModelID, field.TypeString, value)
	}
	if _u.mutation.UpstreamModelIDCleared() {
		_spec.ClearField(videomodel.FieldUpstreamModelID, field.TypeString)
	}
	if value, ok := _u.mutation.RequestShape(); ok {
		_spec.SetField(videomodel.FieldRequestShape, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(videomodel.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Capabilities(); ok {
		_spec.SetField(videomodel.FieldCapabilities, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Defaults(); ok {
		_spec.SetField(videomodel.FieldDefaults, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Limits(); ok {
		_spec.SetField(videomodel.FieldLimits, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.SupportedOptions(); ok {
		_spec.SetField(videomodel.FieldSupportedOptions, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.ExtraBodyAllow(); ok {
		_spec.SetField(videomodel.FieldExtraBodyAllow, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedExtraBodyAllow(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, videomodel.FieldExtraBodyAllow, value)
		})
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(videomodel.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(videomodel.FieldSortOrder, field.TypeInt, value)
	}
	if _u.mutation.TemplateCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   videomodel.TemplateTable,
			Columns: []string{videomodel.TemplateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(videocalltemplate.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TemplateIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   videomodel.TemplateTable,
			Columns: []string{videomodel.TemplateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(videocalltemplate.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   videomodel.TasksTable,
			Columns: []string{videomodel.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(videogenerationtask.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTasksIDs(); len(nodes) > 0 && !_u.mutation.TasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   videomodel.TasksTable,
			Columns: []string{videomodel.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(videogenerationtask.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TasksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   videomodel.TasksTable,
			Columns: []string{videomodel.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(videogenerationtask.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{videomodel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// VideoModelUpdateOne is the builder for updating a single VideoModel entity.
type VideoModelUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *VideoModelMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *VideoModelUpdateOne) SetUpdatedAt(v time.Time) *VideoModelUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetPublicModel sets the "public_model" field.
func (_u *VideoModelUpdateOne) SetPublicModel(v string) *VideoModelUpdateOne {
	_u.mutation.SetPublicModel(v)
	return _u
}

// SetNillablePublicModel sets the "public_model" field if the given value is not nil.
func (_u *VideoModelUpdateOne) SetNillablePublicModel(v *string) *VideoModelUpdateOne {
	if v != nil {
		_u.SetPublicModel(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *VideoModelUpdateOne) SetDisplayName(v string) *VideoModelUpdateOne {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *VideoModelUpdateOne) SetNillableDisplayName(v *string) *VideoModelUpdateOne {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// ClearDisplayName clears the value of the "display_name" field.
func (_u *VideoModelUpdateOne) ClearDisplayName() *VideoModelUpdateOne {
	_u.mutation.ClearDisplayName()
	return _u
}

// SetTemplateID sets the "template_id" field.
func (_u *VideoModelUpdateOne) SetTemplateID(v int64) *VideoModelUpdateOne {
	_u.mutation.SetTemplateID(v)
	return _u
}

// SetNillableTemplateID sets the "template_id" field if the given value is not nil.
func (_u *VideoModelUpdateOne) SetNillableTemplateID(v *int64) *VideoModelUpdateOne {
	if v != nil {
		_u.SetTemplateID(*v)
	}
	return _u
}

// SetUpstreamModelID sets the "upstream_model_id" field.
func (_u *VideoModelUpdateOne) SetUpstreamModelID(v string) *VideoModelUpdateOne {
	_u.mutation.SetUpstreamModelID(v)
	return _u
}

// SetNillableUpstreamModelID sets the "upstream_model_id" field if the given value is not nil.
func (_u *VideoModelUpdateOne) SetNillableUpstreamModelID(v *string) *VideoModelUpdateOne {
	if v != nil {
		_u.SetUpstreamModelID(*v)
	}
	return _u
}

// ClearUpstreamModelID clears the value of the "upstream_model_id" field.
func (_u *VideoModelUpdateOne) ClearUpstreamModelID() *VideoModelUpdateOne {
	_u.mutation.ClearUpstreamModelID()
	return _u
}

// SetRequestShape sets the "request_shape" field.
func (_u *VideoModelUpdateOne) SetRequestShape(v string) *VideoModelUpdateOne {
	_u.mutation.SetRequestShape(v)
	return _u
}

// SetNillableRequestShape sets the "request_shape" field if the given value is not nil.
func (_u *VideoModelUpdateOne) SetNillableRequestShape(v *string) *VideoModelUpdateOne {
	if v != nil {
		_u.SetRequestShape(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *VideoModelUpdateOne) SetStatus(v string) *VideoModelUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *VideoModelUpdateOne) SetNillableStatus(v *string) *VideoModelUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCapabilities sets the "capabilities" field.
func (_u *VideoModelUpdateOne) SetCapabilities(v map[string]interface{}) *VideoModelUpdateOne {
	_u.mutation.SetCapabilities(v)
	return _u
}

// SetDefaults sets the "defaults" field.
func (_u *VideoModelUpdateOne) SetDefaults(v map[string]interface{}) *VideoModelUpdateOne {
	_u.mutation.SetDefaults(v)
	return _u
}

// SetLimits sets the "limits" field.
func (_u *VideoModelUpdateOne) SetLimits(v map[string]interface{}) *VideoModelUpdateOne {
	_u.mutation.SetLimits(v)
	return _u
}

// SetSupportedOptions sets the "supported_options" field.
func (_u *VideoModelUpdateOne) SetSupportedOptions(v map[string]interface{}) *VideoModelUpdateOne {
	_u.mutation.SetSupportedOptions(v)
	return _u
}

// SetExtraBodyAllow sets the "extra_body_allow" field.
func (_u *VideoModelUpdateOne) SetExtraBodyAllow(v []string) *VideoModelUpdateOne {
	_u.mutation.SetExtraBodyAllow(v)
	return _u
}

// AppendExtraBodyAllow appends value to the "extra_body_allow" field.
func (_u *VideoModelUpdateOne) AppendExtraBodyAllow(v []string) *VideoModelUpdateOne {
	_u.mutation.AppendExtraBodyAllow(v)
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *VideoModelUpdateOne) SetSortOrder(v int) *VideoModelUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *VideoModelUpdateOne) SetNillableSortOrder(v *int) *VideoModelUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *VideoModelUpdateOne) AddSortOrder(v int) *VideoModelUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetTemplate sets the "template" edge to the VideoCallTemplate entity.
func (_u *VideoModelUpdateOne) SetTemplate(v *VideoCallTemplate) *VideoModelUpdateOne {
	return _u.SetTemplateID(v.ID)
}

// AddTaskIDs adds the "tasks" edge to the VideoGenerationTask entity by IDs.
func (_u *VideoModelUpdateOne) AddTaskIDs(ids ...int64) *VideoModelUpdateOne {
	_u.mutation.AddTaskIDs(ids...)
	return _u
}

// AddTasks adds the "tasks" edges to the VideoGenerationTask entity.
func (_u *VideoModelUpdateOne) AddTasks(v ...*VideoGenerationTask) *VideoModelUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTaskIDs(ids...)
}

// Mutation returns the VideoModelMutation object of the builder.
func (_u *VideoModelUpdateOne) Mutation() *VideoModelMutation {
	return _u.mutation
}

// ClearTemplate clears the "template" edge to the VideoCallTemplate entity.
func (_u *VideoModelUpdateOne) ClearTemplate() *VideoModelUpdateOne {
	_u.mutation.ClearTemplate()
	return _u
}

// ClearTasks clears all "tasks" edges to the VideoGenerationTask entity.
func (_u *VideoModelUpdateOne) ClearTasks() *VideoModelUpdateOne {
	_u.mutation.ClearTasks()
	return _u
}

// RemoveTaskIDs removes the "tasks" edge to VideoGenerationTask entities by IDs.
func (_u *VideoModelUpdateOne) RemoveTaskIDs(ids ...int64) *VideoModelUpdateOne {
	_u.mutation.RemoveTaskIDs(ids...)
	return _u
}

// RemoveTasks removes "tasks" edges to VideoGenerationTask entities.
func (_u *VideoModelUpdateOne) RemoveTasks(v ...*VideoGenerationTask) *VideoModelUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTaskIDs(ids...)
}

// Where appends a list predicates to the VideoModelUpdate builder.
func (_u *VideoModelUpdateOne) Where(ps ...predicate.VideoModel) *VideoModelUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *VideoModelUpdateOne) Select(field string, fields ...string) *VideoModelUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated VideoModel entity.
func (_u *VideoModelUpdateOne) Save(ctx context.Context) (*VideoModel, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VideoModelUpdateOne) SaveX(ctx context.Context) *VideoModel {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *VideoModelUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VideoModelUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *VideoModelUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := videomodel.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *VideoModelUpdateOne) check() error {
	if v, ok := _u.mutation.PublicModel(); ok {
		if err := videomodel.PublicModelValidator(v); err != nil {
			return &ValidationError{Name: "public_model", err: fmt.Errorf(`ent: validator failed for field "VideoModel.public_model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DisplayName(); ok {
		if err := videomodel.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "VideoModel.display_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamModelID(); ok {
		if err := videomodel.UpstreamModelIDValidator(v); err != nil {
			return &ValidationError{Name: "upstream_model_id", err: fmt.Errorf(`ent: validator failed for field "VideoModel.upstream_model_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestShape(); ok {
		if err := videomodel.RequestShapeValidator(v); err != nil {
			return &ValidationError{Name: "request_shape", err: fmt.Errorf(`ent: validator failed for field "VideoModel.request_shape": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := videomodel.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "VideoModel.status": %w`, err)}
		}
	}
	if _u.mutation.TemplateCleared() && len(_u.mutation.TemplateIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "VideoModel.template"`)
	}
	return nil
}

func (_u *VideoModelUpdateOne) sqlSave(ctx context.Context) (_node *VideoModel, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(videomodel.Table, videomodel.Columns, sqlgraph.NewFieldSpec(videomodel.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "VideoModel.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, videomodel.FieldID)
		for _, f := range fields {
			if !videomodel.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != videomodel.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(videomodel.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PublicModel(); ok {
		_spec.SetField(videomodel.FieldPublicModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(videomodel.FieldDisplayName, field.TypeString, value)
	}
	if _u.mutation.DisplayNameCleared() {
		_spec.ClearField(videomodel.FieldDisplayName, field.TypeString)
	}
	if value, ok := _u.mutation.UpstreamModelID(); ok {
		_spec.SetField(videomodel.FieldUpstreamModelID, field.TypeString, value)
	}
	if _u.mutation.UpstreamModelIDCleared() {
		_spec.ClearField(videomodel.FieldUpstreamModelID, field.TypeString)
	}
	if value, ok := _u.mutation.RequestShape(); ok {
		_spec.SetField(videomodel.FieldRequestShape, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(videomodel.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Capabilities(); ok {
		_spec.SetField(videomodel.FieldCapabilities, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Defaults(); ok {
		_spec.SetField(videomodel.FieldDefaults, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Limits(); ok {
		_spec.SetField(videomodel.FieldLimits, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.SupportedOptions(); ok {
		_spec.SetField(videomodel.FieldSupportedOptions, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.ExtraBodyAllow(); ok {
		_spec.SetField(videomodel.FieldExtraBodyAllow, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedExtraBodyAllow(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, videomodel.FieldExtraBodyAllow, value)
		})
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(videomodel.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(videomodel.FieldSortOrder, field.TypeInt, value)
	}
	if _u.mutation.TemplateCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   videomodel.TemplateTable,
			Columns: []string{videomodel.TemplateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(videocalltemplate.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TemplateIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   videomodel.TemplateTable,
			Columns: []string{videomodel.TemplateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(videocalltemplate.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   videomodel.TasksTable,
			Columns: []string{videomodel.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(videogenerationtask.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTasksIDs(); len(nodes) > 0 && !_u.mutation.TasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   videomodel.TasksTable,
			Columns: []string{videomodel.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(videogenerationtask.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TasksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   videomodel.TasksTable,
			Columns: []string{videomodel.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(videogenerationtask.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &VideoModel{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{videomodel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
