// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/ccapi/ent/videocalltemplate"
	"github.com/Wei-Shaw/ccapi/ent/videomodel"
)

// VideoModel is the model entity for the VideoModel schema.
type VideoModel struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// PublicModel holds the value of the "public_model" field.
	PublicModel string `json:"public_model,omitempty"`
	// DisplayName holds the value of the "display_name" field.
	DisplayName *string `json:"display_name,omitempty"`
	// TemplateID holds the value of the "template_id" field.
	TemplateID int64 `json:"template_id,omitempty"`
	// UpstreamModelID holds the value of the "upstream_model_id" field.
	UpstreamModelID *string `json:"upstream_model_id,omitempty"`
	// RequestShape holds the value of the "request_shape" field.
	RequestShape string `json:"request_shape,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Capabilities holds the value of the "capabilities" field.
	Capabilities map[string]interface{} `json:"capabilities,omitempty"`
	// Defaults holds the value of the "defaults" field.
	Defaults map[string]interface{} `json:"defaults,omitempty"`
	// Limits holds the value of the "limits" field.
	Limits map[string]interface{} `json:"limits,omitempty"`
	// SupportedOptions holds the value of the "supported_options" field.
	SupportedOptions map[string]interface{} `json:"supported_options,omitempty"`
	// ExtraBodyAllow holds the value of the "extra_body_allow" field.
	ExtraBodyAllow []string `json:"extra_body_allow,omitempty"`
	// SortOrder holds the value of the "sort_order" field.
	SortOrder int `json:"sort_order,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the VideoModelQuery when eager-loading is set.
	Edges        VideoModelEdges `json:"edges"`
	selectValues sql.SelectValues
}

// VideoModelEdges holds the relations/edges for other nodes in the graph.
type VideoModelEdges struct {
	// Template holds the value of the template edge.
	Template *VideoCallTemplate `json:"template,omitempty"`
	// Tasks holds the value of the tasks edge.
	Tasks []*VideoGenerationTask `json:"tasks,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// TemplateOrErr returns the Template value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e VideoModelEdges) TemplateOrErr() (*VideoCallTemplate, error) {
	if e.Template != nil {
		return e.Template, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: videocalltemplate.Label}
	}
	return nil, &NotLoadedError{edge: "template"}
}

// TasksOrErr returns the Tasks value or an error if the edge
// was not loaded in eager-loading.
func (e VideoModelEdges) TasksOrErr() ([]*VideoGenerationTask, error) {
	if e.loadedTypes[1] {
		return e.Tasks, nil
	}
	return nil, &NotLoadedError{edge: "tasks"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*VideoModel) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case videomodel.FieldCapabilities, videomodel.FieldDefaults, videomodel.FieldLimits, videomodel.FieldSupportedOptions, videomodel.FieldExtraBodyAllow:
			values[i] = new([]byte)
		case videomodel.FieldID, videomodel.FieldTemplateID, videomodel.FieldSortOrder:
			values[i] = new(sql.NullInt64)
		case videomodel.FieldPublicModel, videomodel.FieldDisplayName, videomodel.FieldUpstreamModelID, videomodel.FieldRequestShape, videomodel.FieldStatus:
			values[i] = new(sql.NullString)
		case videomodel.FieldCreatedAt, videomodel.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the VideoModel fields.
func (_m *VideoModel) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case videomodel.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case videomodel.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case videomodel.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case videomodel.FieldPublicModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field public_model", values[i])
			} else if value.Valid {
				_m.PublicModel = value.String
			}
		case videomodel.FieldDisplayName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field display_name", values[i])
			} else if value.Valid {
				_m.DisplayName = new(string)
				*_m.DisplayName = value.String
			}
		case videomodel.FieldTemplateID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field template_id", values[i])
			} else if value.Valid {
				_m.TemplateID = value.Int64
			}
		case videomodel.FieldUpstreamModelID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_model_id", values[i])
			} else if value.Valid {
				_m.UpstreamModelID = new(string)
				*_m.UpstreamModelID = value.String
			}
		case videomodel.FieldRequestShape:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_shape", values[i])
			} else if value.Valid {
				_m.RequestShape = value.String
			}
		case videomodel.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case videomodel.FieldCapabilities:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field capabilities", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Capabilities); err != nil {
					return fmt.Errorf("unmarshal field capabilities: %w", err)
				}
			}
		case videomodel.FieldDefaults:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field defaults", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Defaults); err != nil {
					return fmt.Errorf("unmarshal field defaults: %w", err)
				}
			}
		case videomodel.FieldLimits:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field limits", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Limits); err != nil {
					return fmt.Errorf("unmarshal field limits: %w", err)
				}
			}
		case videomodel.FieldSupportedOptions:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field supported_options", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.SupportedOptions); err != nil {
					return fmt.Errorf("unmarshal field supported_options: %w", err)
				}
			}
		case videomodel.FieldExtraBodyAllow:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field extra_body_allow", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ExtraBodyAllow); err != nil {
					return fmt.Errorf("unmarshal field extra_body_allow: %w", err)
				}
			}
		case videomodel.FieldSortOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort_order", values[i])
			} else if value.Valid {
				_m.SortOrder = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the VideoModel.
// This includes values selected through modifiers, order, etc.
func (_m *VideoModel) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTemplate queries the "template" edge of the VideoModel entity.
func (_m *VideoModel) QueryTemplate() *VideoCallTemplateQuery {
	return NewVideoModelClient(_m.config).QueryTemplate(_m)
}

// QueryTasks queries the "tasks" edge of the VideoModel entity.
func (_m *VideoModel) QueryTasks() *VideoGenerationTaskQuery {
	return NewVideoModelClient(_m.config).QueryTasks(_m)
}

// Update returns a builder for updating this VideoModel.
// Note that you need to call VideoModel.Unwrap() before calling this method if this VideoModel
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *VideoModel) Update() *VideoModelUpdateOne {
	return NewVideoModelClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the VideoModel entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *VideoModel) Unwrap() *VideoModel {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: VideoModel is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *VideoModel) String() string {
	var builder strings.Builder
	builder.WriteString("VideoModel(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("public_model=")
	builder.WriteString(_m.PublicModel)
	builder.WriteString(", ")
	if v := _m.DisplayName; v != nil {
		builder.WriteString("display_name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("template_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TemplateID))
	builder.WriteString(", ")
	if v := _m.UpstreamModelID; v != nil {
		builder.WriteString("upstream_model_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("request_shape=")
	builder.WriteString(_m.RequestShape)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("capabilities=")
	builder.WriteString(fmt.Sprintf("%v", _m.Capabilities))
	builder.WriteString(", ")
	builder.WriteString("defaults=")
	builder.WriteString(fmt.Sprintf("%v", _m.Defaults))
	builder.WriteString(", ")
	builder.WriteString("limits=")
	builder.WriteString(fmt.Sprintf("%v", _m.Limits))
	builder.WriteString(", ")
	builder.WriteString("supported_options=")
	builder.WriteString(fmt.Sprintf("%v", _m.SupportedOptions))
	builder.WriteString(", ")
	builder.WriteString("extra_body_allow=")
	builder.WriteString(fmt.Sprintf("%v", _m.ExtraBodyAllow))
	builder.WriteString(", ")
	builder.WriteString("sort_order=")
	builder.WriteString(fmt.Sprintf("%v", _m.SortOrder))
	builder.WriteByte(')')
	return builder.String()
}

// VideoModels is a parsable slice of VideoModel.
type VideoModels []*VideoModel
