// Code generated by ent, DO NOT EDIT.

package videogenerationtask

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the videogenerationtask type in the database.
	Label = "video_generation_task"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPublicID holds the string denoting the public_id field in the database.
	FieldPublicID = "public_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldAPIKeyID holds the string denoting the api_key_id field in the database.
	FieldAPIKeyID = "api_key_id"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldChannelID holds the string denoting the channel_id field in the database.
	FieldChannelID = "channel_id"
	// FieldVideoModelID holds the string denoting the video_model_id field in the database.
	FieldVideoModelID = "video_model_id"
	// FieldRequestedModel holds the string denoting the requested_model field in the database.
	FieldRequestedModel = "requested_model"
	// FieldUpstreamModel holds the string denoting the upstream_model field in the database.
	FieldUpstreamModel = "upstream_model"
	// FieldUpstreamTaskID holds the string denoting the upstream_task_id field in the database.
	FieldUpstreamTaskID = "upstream_task_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldProgress holds the string denoting the progress field in the database.
	FieldProgress = "progress"
	// FieldBillingState holds the string denoting the billing_state field in the database.
	FieldBillingState = "billing_state"
	// FieldRequestPayload holds the string denoting the request_payload field in the database.
	FieldRequestPayload = "request_payload"
	// FieldUpstreamRequestPayload holds the string denoting the upstream_request_payload field in the database.
	FieldUpstreamRequestPayload = "upstream_request_payload"
	// FieldUpstreamResponsePayload holds the string denoting the upstream_response_payload field in the database.
	FieldUpstreamResponsePayload = "upstream_response_payload"
	// FieldResultPayload holds the string denoting the result_payload field in the database.
	FieldResultPayload = "result_payload"
	// FieldErrorCode holds the string denoting the error_code field in the database.
	FieldErrorCode = "error_code"
	// FieldErrorMessage holds the string denoting the error_message field in the database.
	FieldErrorMessage = "error_message"
	// FieldContentURL holds the string denoting the content_url field in the database.
	FieldContentURL = "content_url"
	// FieldUpstreamContentURL holds the string denoting the upstream_content_url field in the database.
	FieldUpstreamContentURL = "upstream_content_url"
	// FieldLocalContentURL holds the string denoting the local_content_url field in the database.
	FieldLocalContentURL = "local_content_url"
	// FieldBillingMode holds the string denoting the billing_mode field in the database.
	FieldBillingMode = "billing_mode"
	// FieldUnitPrice holds the string denoting the unit_price field in the database.
	FieldUnitPrice = "unit_price"
	// FieldUnitSeconds holds the string denoting the unit_seconds field in the database.
	FieldUnitSeconds = "unit_seconds"
	// FieldRequestedSeconds holds the string denoting the requested_seconds field in the database.
	FieldRequestedSeconds = "requested_seconds"
	// FieldBillableSeconds holds the string denoting the billable_seconds field in the database.
	FieldBillableSeconds = "billable_seconds"
	// FieldReservedCost holds the string denoting the reserved_cost field in the database.
	FieldReservedCost = "reserved_cost"
	// FieldEstimatedCost holds the string denoting the estimated_cost field in the database.
	FieldEstimatedCost = "estimated_cost"
	// FieldActualCost holds the string denoting the actual_cost field in the database.
	FieldActualCost = "actual_cost"
	// FieldIdempotencyKey holds the string denoting the idempotency_key field in the database.
	FieldIdempotencyKey = "idempotency_key"
	// FieldSubmittedAt holds the string denoting the submitted_at field in the database.
	FieldSubmittedAt = "submitted_at"
	// FieldStartedAt holds the string denoting the started_at field in the database.
	FieldStartedAt = "started_at"
	// FieldCompletedAt holds the string denoting the completed_at field in the database.
	FieldCompletedAt = "completed_at"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldNextPollAt holds the string denoting the next_poll_at field in the database.
	FieldNextPollAt = "next_poll_at"
	// FieldPollCount holds the string denoting the poll_count field in the database.
	FieldPollCount = "poll_count"
	// FieldLockedUntil holds the string denoting the locked_until field in the database.
	FieldLockedUntil = "locked_until"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeAPIKey holds the string denoting the api_key edge name in mutations.
	EdgeAPIKey = "api_key"
	// EdgeAccount holds the string denoting the account edge name in mutations.
	EdgeAccount = "account"
	// EdgeGroup holds the string denoting the group edge name in mutations.
	EdgeGroup = "group"
	// EdgeVideoModel holds the string denoting the video_model edge name in mutations.
	EdgeVideoModel = "video_model"
	// Table holds the table name of the videogenerationtask in the database.
	Table = "video_generation_tasks"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "video_generation_tasks"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// APIKeyTable is the table that holds the api_key relation/edge.
	APIKeyTable = "video_generation_tasks"
	// APIKeyInverseTable is the table name for the APIKey entity.
	// It exists in this package in order to avoid circular dependency with the "apikey" package.
	APIKeyInverseTable = "api_keys"
	// APIKeyColumn is the table column denoting the api_key relation/edge.
	APIKeyColumn = "api_key_id"
	// AccountTable is the table that holds the account relation/edge.
	AccountTable = "video_generation_tasks"
	// AccountInverseTable is the table name for the Account entity.
	// It exists in this package in order to avoid circular dependency with the "account" package.
	AccountInverseTable = "accounts"
	// AccountColumn is the table column denoting the account relation/edge.
	AccountColumn = "account_id"
	// GroupTable is the table that holds the group relation/edge.
	GroupTable = "video_generation_tasks"
	// GroupInverseTable is the table name for the Group entity.
	// It exists in this package in order to avoid circular dependency with the "group" package.
	GroupInverseTable = "groups"
	// GroupColumn is the table column denoting the group relation/edge.
	GroupColumn = "group_id"
	// VideoModelTable is the table that holds the video_model relation/edge.
	VideoModelTable = "video_generation_tasks"
	// VideoModelInverseTable is the table name for the VideoModel entity.
	// It exists in this package in order to avoid circular dependency with the "videomodel" package.
	VideoModelInverseTable = "video_models"
	// VideoModelColumn is the table column denoting the video_model relation/edge.
	VideoModelColumn = "video_model_id"
)

// Columns holds all SQL columns for videogenerationtask fields.
var Columns = []string{
	FieldID,
	FieldPublicID,
	FieldUserID,
	FieldAPIKeyID,
	FieldGroupID,
	FieldAccountID,
	FieldChannelID,
	FieldVideoModelID,
	FieldRequestedModel,
	FieldUpstreamModel,
	FieldUpstreamTaskID,
	FieldStatus,
	FieldProgress,
	FieldBillingState,
	FieldRequestPayload,
	FieldUpstreamRequestPayload,
	FieldUpstreamResponsePayload,
	FieldResultPayload,
	FieldErrorCode,
	FieldErrorMessage,
	FieldContentURL,
	FieldUpstreamContentURL,
	FieldLocalContentURL,
	FieldBillingMode,
	FieldUnitPrice,
	FieldUnitSeconds,
	FieldRequestedSeconds,
	FieldBillableSeconds,
	FieldReservedCost,
	FieldEstimatedCost,
	FieldActualCost,
	FieldIdempotencyKey,
	FieldSubmittedAt,
	FieldStartedAt,
	FieldCompletedAt,
	FieldExpiresAt,
	FieldNextPollAt,
	FieldPollCount,
	FieldLockedUntil,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// PublicIDValidator is a validator for the "public_id" field. It is called by the builders before save.
	PublicIDValidator func(string) error
	// RequestedModelValidator is a validator for the "requested_model" field. It is called by the builders before save.
	RequestedModelValidator func(string) error
	// UpstreamModelValidator is a validator for the "upstream_model" field. It is called by the builders before save.
	UpstreamModelValidator func(string) error
	// UpstreamTaskIDValidator is a validator for the "upstream_task_id" field. It is called by the builders before save.
	UpstreamTaskIDValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultProgress holds the default value on creation for the "progress" field.
	DefaultProgress int
	// DefaultBillingState holds the default value on creation for the "billing_state" field.
	DefaultBillingState string
	// BillingStateValidator is a validator for the "billing_state" field. It is called by the builders before save.
	BillingStateValidator func(string) error
	// DefaultRequestPayload holds the default value on creation for the "request_payload" field.
	DefaultRequestPayload func() map[string]interface{}
	// ErrorCodeValidator is a validator for the "error_code" field. It is called by the builders before save.
	ErrorCodeValidator func(string) error
	// BillingModeValidator is a validator for the "billing_mode" field. It is called by the builders before save.
	BillingModeValidator func(string) error
	// DefaultUnitPrice holds the default value on creation for the "unit_price" field.
	DefaultUnitPrice float64
	// DefaultReservedCost holds the default value on creation for the "reserved_cost" field.
	DefaultReservedCost float64
	// DefaultEstimatedCost holds the default value on creation for the "estimated_cost" field.
	DefaultEstimatedCost float64
	// DefaultActualCost holds the default value on creation for the "actual_cost" field.
	DefaultActualCost float64
	// IdempotencyKeyValidator is a validator for the "idempotency_key" field. It is called by the builders before save.
	IdempotencyKeyValidator func(string) error
	// DefaultPollCount holds the default value on creation for the "poll_count" field.
	DefaultPollCount int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the VideoGenerationTask queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByPublicID orders the results by the public_id field.
func ByPublicID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublicID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByAPIKeyID orders the results by the api_key_id field.
func ByAPIKeyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIKeyID, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByChannelID orders the results by the channel_id field.
func ByChannelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChannelID, opts...).ToFunc()
}

// ByVideoModelID orders the results by the video_model_id field.
func ByVideoModelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVideoModelID, opts...).ToFunc()
}

// ByRequestedModel orders the results by the requested_model field.
func ByRequestedModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestedModel, opts...).ToFunc()
}

// ByUpstreamModel orders the results by the upstream_model field.
func ByUpstreamModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamModel, opts...).ToFunc()
}

// ByUpstreamTaskID orders the results by the upstream_task_id field.
func ByUpstreamTaskID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamTaskID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByProgress orders the results by the progress field.
func ByProgress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProgress, opts...).ToFunc()
}

// ByBillingState orders the results by the billing_state field.
func ByBillingState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBillingState, opts...).ToFunc()
}

// ByErrorCode orders the results by the error_code field.
func ByErrorCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorCode, opts...).ToFunc()
}

// ByErrorMessage orders the results by the error_message field.
func ByErrorMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorMessage, opts...).ToFunc()
}

// ByContentURL orders the results by the content_url field.
func ByContentURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContentURL, opts...).ToFunc()
}

// ByUpstreamContentURL orders the results by the upstream_content_url field.
func ByUpstreamContentURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamContentURL, opts...).ToFunc()
}

// ByLocalContentURL orders the results by the local_content_url field.
func ByLocalContentURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLocalContentURL, opts...).ToFunc()
}

// ByBillingMode orders the results by the billing_mode field.
func ByBillingMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBillingMode, opts...).ToFunc()
}

// ByUnitPrice orders the results by the unit_price field.
func ByUnitPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUnitPrice, opts...).ToFunc()
}

// ByUnitSeconds orders the results by the unit_seconds field.
func ByUnitSeconds(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUnitSeconds, opts...).ToFunc()
}

// ByRequestedSeconds orders the results by the requested_seconds field.
func ByRequestedSeconds(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestedSeconds, opts...).ToFunc()
}

// ByBillableSeconds orders the results by the billable_seconds field.
func ByBillableSeconds(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBillableSeconds, opts...).ToFunc()
}

// ByReservedCost orders the results by the reserved_cost field.
func ByReservedCost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReservedCost, opts...).ToFunc()
}

// ByEstimatedCost orders the results by the estimated_cost field.
func ByEstimatedCost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEstimatedCost, opts...).ToFunc()
}

// ByActualCost orders the results by the actual_cost field.
func ByActualCost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActualCost, opts...).ToFunc()
}

// ByIdempotencyKey orders the results by the idempotency_key field.
func ByIdempotencyKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIdempotencyKey, opts...).ToFunc()
}

// BySubmittedAt orders the results by the submitted_at field.
func BySubmittedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubmittedAt, opts...).ToFunc()
}

// ByStartedAt orders the results by the started_at field.
func ByStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedAt, opts...).ToFunc()
}

// ByCompletedAt orders the results by the completed_at field.
func ByCompletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompletedAt, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByNextPollAt orders the results by the next_poll_at field.
func ByNextPollAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNextPollAt, opts...).ToFunc()
}

// ByPollCount orders the results by the poll_count field.
func ByPollCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPollCount, opts...).ToFunc()
}

// ByLockedUntil orders the results by the locked_until field.
func ByLockedUntil(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLockedUntil, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByAPIKeyField orders the results by api_key field.
func ByAPIKeyField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAPIKeyStep(), sql.OrderByField(field, opts...))
	}
}

// ByAccountField orders the results by account field.
func ByAccountField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAccountStep(), sql.OrderByField(field, opts...))
	}
}

// ByGroupField orders the results by group field.
func ByGroupField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGroupStep(), sql.OrderByField(field, opts...))
	}
}

// ByVideoModelField orders the results by video_model field.
func ByVideoModelField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newVideoModelStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newAPIKeyStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(APIKeyInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, APIKeyTable, APIKeyColumn),
	)
}
func newAccountStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AccountInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, AccountTable, AccountColumn),
	)
}
func newGroupStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GroupInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, GroupTable, GroupColumn),
	)
}
func newVideoModelStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(VideoModelInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, VideoModelTable, VideoModelColumn),
	)
}
