// Code generated by ent, DO NOT EDIT.

package videogenerationtask

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/ccapi/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldLTE(FieldID, id))
}

// PublicID applies equality check predicate on the "public_id" field. It's identical to PublicIDEQ.
func PublicID(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEQ(FieldPublicID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEQ(FieldUserID, v))
}

// APIKeyID applies equality check predicate on the "api_key_id" field. It's identical to APIKeyIDEQ.
func APIKeyID(v int64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEQ(FieldAPIKeyID, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEQ(FieldGroupID, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEQ(FieldAccountID, v))
}

// ChannelID applies equality check predicate on the "channel_id" field. It's identical to ChannelIDEQ.
func ChannelID(v int64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEQ(FieldChannelID, v))
}

// VideoModelID applies equality check predicate on the "video_model_id" field. It's identical to VideoModelIDEQ.
func VideoModelID(v int64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEQ(FieldVideoModelID, v))
}

// RequestedModel applies equality check predicate on the "requested_model" field. It's identical to RequestedModelEQ.
func RequestedModel(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEQ(FieldRequestedModel, v))
}

// UpstreamModel applies equality check predicate on the "upstream_model" field. It's identical to UpstreamModelEQ.
func UpstreamModel(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEQ(FieldUpstreamModel, v))
}

// UpstreamTaskID applies equality check predicate on the "upstream_task_id" field. It's identical to UpstreamTaskIDEQ.
func UpstreamTaskID(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEQ(FieldUpstreamTaskID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEQ(FieldStatus, v))
}

// Progress applies equality check predicate on the "progress" field. It's identical to ProgressEQ.
func Progress(v int) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEQ(FieldProgress, v))
}

// BillingState applies equality check predicate on the "billing_state" field. It's identical to BillingStateEQ.
func BillingState(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEQ(FieldBillingState, v))
}

// ErrorCode applies equality check predicate on the "error_code" field. It's identical to ErrorCodeEQ.
func ErrorCode(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEQ(FieldErrorCode, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEQ(FieldErrorMessage, v))
}

// ContentURL applies equality check predicate on the "content_url" field. It's identical to ContentURLEQ.
func ContentURL(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEQ(FieldContentURL, v))
}

// UpstreamContentURL applies equality check predicate on the "upstream_content_url" field. It's identical to UpstreamContentURLEQ.
func UpstreamContentURL(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEQ(FieldUpstreamContentURL, v))
}

// LocalContentURL applies equality check predicate on the "local_content_url" field. It's identical to LocalContentURLEQ.
func LocalContentURL(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEQ(FieldLocalContentURL, v))
}

// BillingMode applies equality check predicate on the "billing_mode" field. It's identical to BillingModeEQ.
func BillingMode(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEQ(FieldBillingMode, v))
}

// UnitPrice applies equality check predicate on the "unit_price" field. It's identical to UnitPriceEQ.
func UnitPrice(v float64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEQ(FieldUnitPrice, v))
}

// UnitSeconds applies equality check predicate on the "unit_seconds" field. It's identical to UnitSecondsEQ.
func UnitSeconds(v float64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEQ(FieldUnitSeconds, v))
}

// RequestedSeconds applies equality check predicate on the "requested_seconds" field. It's identical to RequestedSecondsEQ.
func RequestedSeconds(v int) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEQ(FieldRequestedSeconds, v))
}

// BillableSeconds applies equality check predicate on the "billable_seconds" field. It's identical to BillableSecondsEQ.
func BillableSeconds(v int) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEQ(FieldBillableSeconds, v))
}

// ReservedCost applies equality check predicate on the "reserved_cost" field. It's identical to ReservedCostEQ.
func ReservedCost(v float64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEQ(FieldReservedCost, v))
}

// EstimatedCost applies equality check predicate on the "estimated_cost" field. It's identical to EstimatedCostEQ.
func EstimatedCost(v float64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEQ(FieldEstimatedCost, v))
}

// ActualCost applies equality check predicate on the "actual_cost" field. It's identical to ActualCostEQ.
func ActualCost(v float64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEQ(FieldActualCost, v))
}

// IdempotencyKey applies equality check predicate on the "idempotency_key" field. It's identical to IdempotencyKeyEQ.
func IdempotencyKey(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEQ(FieldIdempotencyKey, v))
}

// SubmittedAt applies equality check predicate on the "submitted_at" field. It's identical to SubmittedAtEQ.
func SubmittedAt(v time.Time) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEQ(FieldSubmittedAt, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEQ(FieldStartedAt, v))
}

// CompletedAt applies equality check predicate on the "completed_at" field. It's identical to CompletedAtEQ.
func CompletedAt(v time.Time) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEQ(FieldCompletedAt, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEQ(FieldExpiresAt, v))
}

// NextPollAt applies equality check predicate on the "next_poll_at" field. It's identical to NextPollAtEQ.
func NextPollAt(v time.Time) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEQ(FieldNextPollAt, v))
}

// PollCount applies equality check predicate on the "poll_count" field. It's identical to PollCountEQ.
func PollCount(v int) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEQ(FieldPollCount, v))
}

// LockedUntil applies equality check predicate on the "locked_until" field. It's identical to LockedUntilEQ.
func LockedUntil(v time.Time) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEQ(FieldLockedUntil, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEQ(FieldUpdatedAt, v))
}

// PublicIDEQ applies the EQ predicate on the "public_id" field.
func PublicIDEQ(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEQ(FieldPublicID, v))
}

// PublicIDNEQ applies the NEQ predicate on the "public_id" field.
func PublicIDNEQ(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNEQ(FieldPublicID, v))
}

// PublicIDIn applies the In predicate on the "public_id" field.
func PublicIDIn(vs ...string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldIn(FieldPublicID, vs...))
}

// PublicIDNotIn applies the NotIn predicate on the "public_id" field.
func PublicIDNotIn(vs ...string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNotIn(FieldPublicID, vs...))
}

// PublicIDGT applies the GT predicate on the "public_id" field.
func PublicIDGT(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldGT(FieldPublicID, v))
}

// PublicIDGTE applies the GTE predicate on the "public_id" field.
func PublicIDGTE(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldGTE(FieldPublicID, v))
}

// PublicIDLT applies the LT predicate on the "public_id" field.
func PublicIDLT(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldLT(FieldPublicID, v))
}

// PublicIDLTE applies the LTE predicate on the "public_id" field.
func PublicIDLTE(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldLTE(FieldPublicID, v))
}

// PublicIDContains applies the Contains predicate on the "public_id" field.
func PublicIDContains(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldContains(FieldPublicID, v))
}

// PublicIDHasPrefix applies the HasPrefix predicate on the "public_id" field.
func PublicIDHasPrefix(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldHasPrefix(FieldPublicID, v))
}

// PublicIDHasSuffix applies the HasSuffix predicate on the "public_id" field.
func PublicIDHasSuffix(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldHasSuffix(FieldPublicID, v))
}

// PublicIDEqualFold applies the EqualFold predicate on the "public_id" field.
func PublicIDEqualFold(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEqualFold(FieldPublicID, v))
}

// PublicIDContainsFold applies the ContainsFold predicate on the "public_id" field.
func PublicIDContainsFold(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldContainsFold(FieldPublicID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNotIn(FieldUserID, vs...))
}

// APIKeyIDEQ applies the EQ predicate on the "api_key_id" field.
func APIKeyIDEQ(v int64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEQ(FieldAPIKeyID, v))
}

// APIKeyIDNEQ applies the NEQ predicate on the "api_key_id" field.
func APIKeyIDNEQ(v int64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNEQ(FieldAPIKeyID, v))
}

// APIKeyIDIn applies the In predicate on the "api_key_id" field.
func APIKeyIDIn(vs ...int64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldIn(FieldAPIKeyID, vs...))
}

// APIKeyIDNotIn applies the NotIn predicate on the "api_key_id" field.
func APIKeyIDNotIn(vs ...int64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNotIn(FieldAPIKeyID, vs...))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDIsNil applies the IsNil predicate on the "group_id" field.
func GroupIDIsNil() predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldIsNull(FieldGroupID))
}

// GroupIDNotNil applies the NotNil predicate on the "group_id" field.
func GroupIDNotNil() predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNotNull(FieldGroupID))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNotIn(FieldAccountID, vs...))
}

// ChannelIDEQ applies the EQ predicate on the "channel_id" field.
func ChannelIDEQ(v int64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEQ(FieldChannelID, v))
}

// ChannelIDNEQ applies the NEQ predicate on the "channel_id" field.
func ChannelIDNEQ(v int64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNEQ(FieldChannelID, v))
}

// ChannelIDIn applies the In predicate on the "channel_id" field.
func ChannelIDIn(vs ...int64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldIn(FieldChannelID, vs...))
}

// ChannelIDNotIn applies the NotIn predicate on the "channel_id" field.
func ChannelIDNotIn(vs ...int64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNotIn(FieldChannelID, vs...))
}

// ChannelIDGT applies the GT predicate on the "channel_id" field.
func ChannelIDGT(v int64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldGT(FieldChannelID, v))
}

// ChannelIDGTE applies the GTE predicate on the "channel_id" field.
func ChannelIDGTE(v int64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldGTE(FieldChannelID, v))
}

// ChannelIDLT applies the LT predicate on the "channel_id" field.
func ChannelIDLT(v int64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldLT(FieldChannelID, v))
}

// ChannelIDLTE applies the LTE predicate on the "channel_id" field.
func ChannelIDLTE(v int64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldLTE(FieldChannelID, v))
}

// ChannelIDIsNil applies the IsNil predicate on the "channel_id" field.
func ChannelIDIsNil() predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldIsNull(FieldChannelID))
}

// ChannelIDNotNil applies the NotNil predicate on the "channel_id" field.
func ChannelIDNotNil() predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNotNull(FieldChannelID))
}

// VideoModelIDEQ applies the EQ predicate on the "video_model_id" field.
func VideoModelIDEQ(v int64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEQ(FieldVideoModelID, v))
}

// VideoModelIDNEQ applies the NEQ predicate on the "video_model_id" field.
func VideoModelIDNEQ(v int64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNEQ(FieldVideoModelID, v))
}

// VideoModelIDIn applies the In predicate on the "video_model_id" field.
func VideoModelIDIn(vs ...int64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldIn(FieldVideoModelID, vs...))
}

// VideoModelIDNotIn applies the NotIn predicate on the "video_model_id" field.
func VideoModelIDNotIn(vs ...int64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNotIn(FieldVideoModelID, vs...))
}

// RequestedModelEQ applies the EQ predicate on the "requested_model" field.
func RequestedModelEQ(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEQ(FieldRequestedModel, v))
}

// RequestedModelNEQ applies the NEQ predicate on the "requested_model" field.
func RequestedModelNEQ(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNEQ(FieldRequestedModel, v))
}

// RequestedModelIn applies the In predicate on the "requested_model" field.
func RequestedModelIn(vs ...string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldIn(FieldRequestedModel, vs...))
}

// RequestedModelNotIn applies the NotIn predicate on the "requested_model" field.
func RequestedModelNotIn(vs ...string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNotIn(FieldRequestedModel, vs...))
}

// RequestedModelGT applies the GT predicate on the "requested_model" field.
func RequestedModelGT(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldGT(FieldRequestedModel, v))
}

// RequestedModelGTE applies the GTE predicate on the "requested_model" field.
func RequestedModelGTE(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldGTE(FieldRequestedModel, v))
}

// RequestedModelLT applies the LT predicate on the "requested_model" field.
func RequestedModelLT(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldLT(FieldRequestedModel, v))
}

// RequestedModelLTE applies the LTE predicate on the "requested_model" field.
func RequestedModelLTE(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldLTE(FieldRequestedModel, v))
}

// RequestedModelContains applies the Contains predicate on the "requested_model" field.
func RequestedModelContains(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldContains(FieldRequestedModel, v))
}

// RequestedModelHasPrefix applies the HasPrefix predicate on the "requested_model" field.
func RequestedModelHasPrefix(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldHasPrefix(FieldRequestedModel, v))
}

// RequestedModelHasSuffix applies the HasSuffix predicate on the "requested_model" field.
func RequestedModelHasSuffix(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldHasSuffix(FieldRequestedModel, v))
}

// RequestedModelEqualFold applies the EqualFold predicate on the "requested_model" field.
func RequestedModelEqualFold(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEqualFold(FieldRequestedModel, v))
}

// RequestedModelContainsFold applies the ContainsFold predicate on the "requested_model" field.
func RequestedModelContainsFold(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldContainsFold(FieldRequestedModel, v))
}

// UpstreamModelEQ applies the EQ predicate on the "upstream_model" field.
func UpstreamModelEQ(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEQ(FieldUpstreamModel, v))
}

// UpstreamModelNEQ applies the NEQ predicate on the "upstream_model" field.
func UpstreamModelNEQ(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNEQ(FieldUpstreamModel, v))
}

// UpstreamModelIn applies the In predicate on the "upstream_model" field.
func UpstreamModelIn(vs ...string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldIn(FieldUpstreamModel, vs...))
}

// UpstreamModelNotIn applies the NotIn predicate on the "upstream_model" field.
func UpstreamModelNotIn(vs ...string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNotIn(FieldUpstreamModel, vs...))
}

// UpstreamModelGT applies the GT predicate on the "upstream_model" field.
func UpstreamModelGT(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldGT(FieldUpstreamModel, v))
}

// UpstreamModelGTE applies the GTE predicate on the "upstream_model" field.
func UpstreamModelGTE(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldGTE(FieldUpstreamModel, v))
}

// UpstreamModelLT applies the LT predicate on the "upstream_model" field.
func UpstreamModelLT(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldLT(FieldUpstreamModel, v))
}

// UpstreamModelLTE applies the LTE predicate on the "upstream_model" field.
func UpstreamModelLTE(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldLTE(FieldUpstreamModel, v))
}

// UpstreamModelContains applies the Contains predicate on the "upstream_model" field.
func UpstreamModelContains(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldContains(FieldUpstreamModel, v))
}

// UpstreamModelHasPrefix applies the HasPrefix predicate on the "upstream_model" field.
func UpstreamModelHasPrefix(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldHasPrefix(FieldUpstreamModel, v))
}

// UpstreamModelHasSuffix applies the HasSuffix predicate on the "upstream_model" field.
func UpstreamModelHasSuffix(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldHasSuffix(FieldUpstreamModel, v))
}

// UpstreamModelEqualFold applies the EqualFold predicate on the "upstream_model" field.
func UpstreamModelEqualFold(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEqualFold(FieldUpstreamModel, v))
}

// UpstreamModelContainsFold applies the ContainsFold predicate on the "upstream_model" field.
func UpstreamModelContainsFold(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldContainsFold(FieldUpstreamModel, v))
}

// UpstreamTaskIDEQ applies the EQ predicate on the "upstream_task_id" field.
func UpstreamTaskIDEQ(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEQ(FieldUpstreamTaskID, v))
}

// UpstreamTaskIDNEQ applies the NEQ predicate on the "upstream_task_id" field.
func UpstreamTaskIDNEQ(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNEQ(FieldUpstreamTaskID, v))
}

// UpstreamTaskIDIn applies the In predicate on the "upstream_task_id" field.
func UpstreamTaskIDIn(vs ...string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldIn(FieldUpstreamTaskID, vs...))
}

// UpstreamTaskIDNotIn applies the NotIn predicate on the "upstream_task_id" field.
func UpstreamTaskIDNotIn(vs ...string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNotIn(FieldUpstreamTaskID, vs...))
}

// UpstreamTaskIDGT applies the GT predicate on the "upstream_task_id" field.
func UpstreamTaskIDGT(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldGT(FieldUpstreamTaskID, v))
}

// UpstreamTaskIDGTE applies the GTE predicate on the "upstream_task_id" field.
func UpstreamTaskIDGTE(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldGTE(FieldUpstreamTaskID, v))
}

// UpstreamTaskIDLT applies the LT predicate on the "upstream_task_id" field.
func UpstreamTaskIDLT(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldLT(FieldUpstreamTaskID, v))
}

// UpstreamTaskIDLTE applies the LTE predicate on the "upstream_task_id" field.
func UpstreamTaskIDLTE(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldLTE(FieldUpstreamTaskID, v))
}

// UpstreamTaskIDContains applies the Contains predicate on the "upstream_task_id" field.
func UpstreamTaskIDContains(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldContains(FieldUpstreamTaskID, v))
}

// UpstreamTaskIDHasPrefix applies the HasPrefix predicate on the "upstream_task_id" field.
func UpstreamTaskIDHasPrefix(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldHasPrefix(FieldUpstreamTaskID, v))
}

// UpstreamTaskIDHasSuffix applies the HasSuffix predicate on the "upstream_task_id" field.
func UpstreamTaskIDHasSuffix(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldHasSuffix(FieldUpstreamTaskID, v))
}

// UpstreamTaskIDIsNil applies the IsNil predicate on the "upstream_task_id" field.
func UpstreamTaskIDIsNil() predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldIsNull(FieldUpstreamTaskID))
}

// UpstreamTaskIDNotNil applies the NotNil predicate on the "upstream_task_id" field.
func UpstreamTaskIDNotNil() predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNotNull(FieldUpstreamTaskID))
}

// UpstreamTaskIDEqualFold applies the EqualFold predicate on the "upstream_task_id" field.
func UpstreamTaskIDEqualFold(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEqualFold(FieldUpstreamTaskID, v))
}

// UpstreamTaskIDContainsFold applies the ContainsFold predicate on the "upstream_task_id" field.
func UpstreamTaskIDContainsFold(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldContainsFold(FieldUpstreamTaskID, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldContainsFold(FieldStatus, v))
}

// ProgressEQ applies the EQ predicate on the "progress" field.
func ProgressEQ(v int) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEQ(FieldProgress, v))
}

// ProgressNEQ applies the NEQ predicate on the "progress" field.
func ProgressNEQ(v int) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNEQ(FieldProgress, v))
}

// ProgressIn applies the In predicate on the "progress" field.
func ProgressIn(vs ...int) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldIn(FieldProgress, vs...))
}

// ProgressNotIn applies the NotIn predicate on the "progress" field.
func ProgressNotIn(vs ...int) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNotIn(FieldProgress, vs...))
}

// ProgressGT applies the GT predicate on the "progress" field.
func ProgressGT(v int) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldGT(FieldProgress, v))
}

// ProgressGTE applies the GTE predicate on the "progress" field.
func ProgressGTE(v int) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldGTE(FieldProgress, v))
}

// ProgressLT applies the LT predicate on the "progress" field.
func ProgressLT(v int) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldLT(FieldProgress, v))
}

// ProgressLTE applies the LTE predicate on the "progress" field.
func ProgressLTE(v int) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldLTE(FieldProgress, v))
}

// BillingStateEQ applies the EQ predicate on the "billing_state" field.
func BillingStateEQ(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEQ(FieldBillingState, v))
}

// BillingStateNEQ applies the NEQ predicate on the "billing_state" field.
func BillingStateNEQ(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNEQ(FieldBillingState, v))
}

// BillingStateIn applies the In predicate on the "billing_state" field.
func BillingStateIn(vs ...string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldIn(FieldBillingState, vs...))
}

// BillingStateNotIn applies the NotIn predicate on the "billing_state" field.
func BillingStateNotIn(vs ...string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNotIn(FieldBillingState, vs...))
}

// BillingStateGT applies the GT predicate on the "billing_state" field.
func BillingStateGT(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldGT(FieldBillingState, v))
}

// BillingStateGTE applies the GTE predicate on the "billing_state" field.
func BillingStateGTE(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldGTE(FieldBillingState, v))
}

// BillingStateLT applies the LT predicate on the "billing_state" field.
func BillingStateLT(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldLT(FieldBillingState, v))
}

// BillingStateLTE applies the LTE predicate on the "billing_state" field.
func BillingStateLTE(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldLTE(FieldBillingState, v))
}

// BillingStateContains applies the Contains predicate on the "billing_state" field.
func BillingStateContains(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldContains(FieldBillingState, v))
}

// BillingStateHasPrefix applies the HasPrefix predicate on the "billing_state" field.
func BillingStateHasPrefix(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldHasPrefix(FieldBillingState, v))
}

// BillingStateHasSuffix applies the HasSuffix predicate on the "billing_state" field.
func BillingStateHasSuffix(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldHasSuffix(FieldBillingState, v))
}

// BillingStateEqualFold applies the EqualFold predicate on the "billing_state" field.
func BillingStateEqualFold(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEqualFold(FieldBillingState, v))
}

// BillingStateContainsFold applies the ContainsFold predicate on the "billing_state" field.
func BillingStateContainsFold(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldContainsFold(FieldBillingState, v))
}

// UpstreamRequestPayloadIsNil applies the IsNil predicate on the "upstream_request_payload" field.
func UpstreamRequestPayloadIsNil() predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldIsNull(FieldUpstreamRequestPayload))
}

// UpstreamRequestPayloadNotNil applies the NotNil predicate on the "upstream_request_payload" field.
func UpstreamRequestPayloadNotNil() predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNotNull(FieldUpstreamRequestPayload))
}

// UpstreamResponsePayloadIsNil applies the IsNil predicate on the "upstream_response_payload" field.
func UpstreamResponsePayloadIsNil() predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldIsNull(FieldUpstreamResponsePayload))
}

// UpstreamResponsePayloadNotNil applies the NotNil predicate on the "upstream_response_payload" field.
func UpstreamResponsePayloadNotNil() predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNotNull(FieldUpstreamResponsePayload))
}

// ResultPayloadIsNil applies the IsNil predicate on the "result_payload" field.
func ResultPayloadIsNil() predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldIsNull(FieldResultPayload))
}

// ResultPayloadNotNil applies the NotNil predicate on the "result_payload" field.
func ResultPayloadNotNil() predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNotNull(FieldResultPayload))
}

// ErrorCodeEQ applies the EQ predicate on the "error_code" field.
func ErrorCodeEQ(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEQ(FieldErrorCode, v))
}

// ErrorCodeNEQ applies the NEQ predicate on the "error_code" field.
func ErrorCodeNEQ(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNEQ(FieldErrorCode, v))
}

// ErrorCodeIn applies the In predicate on the "error_code" field.
func ErrorCodeIn(vs ...string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldIn(FieldErrorCode, vs...))
}

// ErrorCodeNotIn applies the NotIn predicate on the "error_code" field.
func ErrorCodeNotIn(vs ...string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNotIn(FieldErrorCode, vs...))
}

// ErrorCodeGT applies the GT predicate on the "error_code" field.
func ErrorCodeGT(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldGT(FieldErrorCode, v))
}

// ErrorCodeGTE applies the GTE predicate on the "error_code" field.
func ErrorCodeGTE(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldGTE(FieldErrorCode, v))
}

// ErrorCodeLT applies the LT predicate on the "error_code" field.
func ErrorCodeLT(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldLT(FieldErrorCode, v))
}

// ErrorCodeLTE applies the LTE predicate on the "error_code" field.
func ErrorCodeLTE(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldLTE(FieldErrorCode, v))
}

// ErrorCodeContains applies the Contains predicate on the "error_code" field.
func ErrorCodeContains(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldContains(FieldErrorCode, v))
}

// ErrorCodeHasPrefix applies the HasPrefix predicate on the "error_code" field.
func ErrorCodeHasPrefix(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldHasPrefix(FieldErrorCode, v))
}

// ErrorCodeHasSuffix applies the HasSuffix predicate on the "error_code" field.
func ErrorCodeHasSuffix(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldHasSuffix(FieldErrorCode, v))
}

// ErrorCodeIsNil applies the IsNil predicate on the "error_code" field.
func ErrorCodeIsNil() predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldIsNull(FieldErrorCode))
}

// ErrorCodeNotNil applies the NotNil predicate on the "error_code" field.
func ErrorCodeNotNil() predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNotNull(FieldErrorCode))
}

// ErrorCodeEqualFold applies the EqualFold predicate on the "error_code" field.
func ErrorCodeEqualFold(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEqualFold(FieldErrorCode, v))
}

// ErrorCodeContainsFold applies the ContainsFold predicate on the "error_code" field.
func ErrorCodeContainsFold(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldContainsFold(FieldErrorCode, v))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageIsNil applies the IsNil predicate on the "error_message" field.
func ErrorMessageIsNil() predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldIsNull(FieldErrorMessage))
}

// ErrorMessageNotNil applies the NotNil predicate on the "error_message" field.
func ErrorMessageNotNil() predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNotNull(FieldErrorMessage))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldContainsFold(FieldErrorMessage, v))
}

// ContentURLEQ applies the EQ predicate on the "content_url" field.
func ContentURLEQ(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEQ(FieldContentURL, v))
}

// ContentURLNEQ applies the NEQ predicate on the "content_url" field.
func ContentURLNEQ(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNEQ(FieldContentURL, v))
}

// ContentURLIn applies the In predicate on the "content_url" field.
func ContentURLIn(vs ...string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldIn(FieldContentURL, vs...))
}

// ContentURLNotIn applies the NotIn predicate on the "content_url" field.
func ContentURLNotIn(vs ...string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNotIn(FieldContentURL, vs...))
}

// ContentURLGT applies the GT predicate on the "content_url" field.
func ContentURLGT(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldGT(FieldContentURL, v))
}

// ContentURLGTE applies the GTE predicate on the "content_url" field.
func ContentURLGTE(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldGTE(FieldContentURL, v))
}

// ContentURLLT applies the LT predicate on the "content_url" field.
func ContentURLLT(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldLT(FieldContentURL, v))
}

// ContentURLLTE applies the LTE predicate on the "content_url" field.
func ContentURLLTE(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldLTE(FieldContentURL, v))
}

// ContentURLContains applies the Contains predicate on the "content_url" field.
func ContentURLContains(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldContains(FieldContentURL, v))
}

// ContentURLHasPrefix applies the HasPrefix predicate on the "content_url" field.
func ContentURLHasPrefix(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldHasPrefix(FieldContentURL, v))
}

// ContentURLHasSuffix applies the HasSuffix predicate on the "content_url" field.
func ContentURLHasSuffix(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldHasSuffix(FieldContentURL, v))
}

// ContentURLIsNil applies the IsNil predicate on the "content_url" field.
func ContentURLIsNil() predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldIsNull(FieldContentURL))
}

// ContentURLNotNil applies the NotNil predicate on the "content_url" field.
func ContentURLNotNil() predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNotNull(FieldContentURL))
}

// ContentURLEqualFold applies the EqualFold predicate on the "content_url" field.
func ContentURLEqualFold(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEqualFold(FieldContentURL, v))
}

// ContentURLContainsFold applies the ContainsFold predicate on the "content_url" field.
func ContentURLContainsFold(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldContainsFold(FieldContentURL, v))
}

// UpstreamContentURLEQ applies the EQ predicate on the "upstream_content_url" field.
func UpstreamContentURLEQ(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEQ(FieldUpstreamContentURL, v))
}

// UpstreamContentURLNEQ applies the NEQ predicate on the "upstream_content_url" field.
func UpstreamContentURLNEQ(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNEQ(FieldUpstreamContentURL, v))
}

// UpstreamContentURLIn applies the In predicate on the "upstream_content_url" field.
func UpstreamContentURLIn(vs ...string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldIn(FieldUpstreamContentURL, vs...))
}

// UpstreamContentURLNotIn applies the NotIn predicate on the "upstream_content_url" field.
func UpstreamContentURLNotIn(vs ...string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNotIn(FieldUpstreamContentURL, vs...))
}

// UpstreamContentURLGT applies the GT predicate on the "upstream_content_url" field.
func UpstreamContentURLGT(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldGT(FieldUpstreamContentURL, v))
}

// UpstreamContentURLGTE applies the GTE predicate on the "upstream_content_url" field.
func UpstreamContentURLGTE(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldGTE(FieldUpstreamContentURL, v))
}

// UpstreamContentURLLT applies the LT predicate on the "upstream_content_url" field.
func UpstreamContentURLLT(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldLT(FieldUpstreamContentURL, v))
}

// UpstreamContentURLLTE applies the LTE predicate on the "upstream_content_url" field.
func UpstreamContentURLLTE(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldLTE(FieldUpstreamContentURL, v))
}

// UpstreamContentURLContains applies the Contains predicate on the "upstream_content_url" field.
func UpstreamContentURLContains(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldContains(FieldUpstreamContentURL, v))
}

// UpstreamContentURLHasPrefix applies the HasPrefix predicate on the "upstream_content_url" field.
func UpstreamContentURLHasPrefix(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldHasPrefix(FieldUpstreamContentURL, v))
}

// UpstreamContentURLHasSuffix applies the HasSuffix predicate on the "upstream_content_url" field.
func UpstreamContentURLHasSuffix(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldHasSuffix(FieldUpstreamContentURL, v))
}

// UpstreamContentURLIsNil applies the IsNil predicate on the "upstream_content_url" field.
func UpstreamContentURLIsNil() predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldIsNull(FieldUpstreamContentURL))
}

// UpstreamContentURLNotNil applies the NotNil predicate on the "upstream_content_url" field.
func UpstreamContentURLNotNil() predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNotNull(FieldUpstreamContentURL))
}

// UpstreamContentURLEqualFold applies the EqualFold predicate on the "upstream_content_url" field.
func UpstreamContentURLEqualFold(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEqualFold(FieldUpstreamContentURL, v))
}

// UpstreamContentURLContainsFold applies the ContainsFold predicate on the "upstream_content_url" field.
func UpstreamContentURLContainsFold(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldContainsFold(FieldUpstreamContentURL, v))
}

// LocalContentURLEQ applies the EQ predicate on the "local_content_url" field.
func LocalContentURLEQ(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEQ(FieldLocalContentURL, v))
}

// LocalContentURLNEQ applies the NEQ predicate on the "local_content_url" field.
func LocalContentURLNEQ(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNEQ(FieldLocalContentURL, v))
}

// LocalContentURLIn applies the In predicate on the "local_content_url" field.
func LocalContentURLIn(vs ...string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldIn(FieldLocalContentURL, vs...))
}

// LocalContentURLNotIn applies the NotIn predicate on the "local_content_url" field.
func LocalContentURLNotIn(vs ...string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNotIn(FieldLocalContentURL, vs...))
}

// LocalContentURLGT applies the GT predicate on the "local_content_url" field.
func LocalContentURLGT(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldGT(FieldLocalContentURL, v))
}

// LocalContentURLGTE applies the GTE predicate on the "local_content_url" field.
func LocalContentURLGTE(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldGTE(FieldLocalContentURL, v))
}

// LocalContentURLLT applies the LT predicate on the "local_content_url" field.
func LocalContentURLLT(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldLT(FieldLocalContentURL, v))
}

// LocalContentURLLTE applies the LTE predicate on the "local_content_url" field.
func LocalContentURLLTE(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldLTE(FieldLocalContentURL, v))
}

// LocalContentURLContains applies the Contains predicate on the "local_content_url" field.
func LocalContentURLContains(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldContains(FieldLocalContentURL, v))
}

// LocalContentURLHasPrefix applies the HasPrefix predicate on the "local_content_url" field.
func LocalContentURLHasPrefix(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldHasPrefix(FieldLocalContentURL, v))
}

// LocalContentURLHasSuffix applies the HasSuffix predicate on the "local_content_url" field.
func LocalContentURLHasSuffix(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldHasSuffix(FieldLocalContentURL, v))
}

// LocalContentURLIsNil applies the IsNil predicate on the "local_content_url" field.
func LocalContentURLIsNil() predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldIsNull(FieldLocalContentURL))
}

// LocalContentURLNotNil applies the NotNil predicate on the "local_content_url" field.
func LocalContentURLNotNil() predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNotNull(FieldLocalContentURL))
}

// LocalContentURLEqualFold applies the EqualFold predicate on the "local_content_url" field.
func LocalContentURLEqualFold(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEqualFold(FieldLocalContentURL, v))
}

// LocalContentURLContainsFold applies the ContainsFold predicate on the "local_content_url" field.
func LocalContentURLContainsFold(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldContainsFold(FieldLocalContentURL, v))
}

// BillingModeEQ applies the EQ predicate on the "billing_mode" field.
func BillingModeEQ(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEQ(FieldBillingMode, v))
}

// BillingModeNEQ applies the NEQ predicate on the "billing_mode" field.
func BillingModeNEQ(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNEQ(FieldBillingMode, v))
}

// BillingModeIn applies the In predicate on the "billing_mode" field.
func BillingModeIn(vs ...string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldIn(FieldBillingMode, vs...))
}

// BillingModeNotIn applies the NotIn predicate on the "billing_mode" field.
func BillingModeNotIn(vs ...string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNotIn(FieldBillingMode, vs...))
}

// BillingModeGT applies the GT predicate on the "billing_mode" field.
func BillingModeGT(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldGT(FieldBillingMode, v))
}

// BillingModeGTE applies the GTE predicate on the "billing_mode" field.
func BillingModeGTE(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldGTE(FieldBillingMode, v))
}

// BillingModeLT applies the LT predicate on the "billing_mode" field.
func BillingModeLT(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldLT(FieldBillingMode, v))
}

// BillingModeLTE applies the LTE predicate on the "billing_mode" field.
func BillingModeLTE(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldLTE(FieldBillingMode, v))
}

// BillingModeContains applies the Contains predicate on the "billing_mode" field.
func BillingModeContains(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldContains(FieldBillingMode, v))
}

// BillingModeHasPrefix applies the HasPrefix predicate on the "billing_mode" field.
func BillingModeHasPrefix(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldHasPrefix(FieldBillingMode, v))
}

// BillingModeHasSuffix applies the HasSuffix predicate on the "billing_mode" field.
func BillingModeHasSuffix(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldHasSuffix(FieldBillingMode, v))
}

// BillingModeEqualFold applies the EqualFold predicate on the "billing_mode" field.
func BillingModeEqualFold(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEqualFold(FieldBillingMode, v))
}

// BillingModeContainsFold applies the ContainsFold predicate on the "billing_mode" field.
func BillingModeContainsFold(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldContainsFold(FieldBillingMode, v))
}

// UnitPriceEQ applies the EQ predicate on the "unit_price" field.
func UnitPriceEQ(v float64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEQ(FieldUnitPrice, v))
}

// UnitPriceNEQ applies the NEQ predicate on the "unit_price" field.
func UnitPriceNEQ(v float64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNEQ(FieldUnitPrice, v))
}

// UnitPriceIn applies the In predicate on the "unit_price" field.
func UnitPriceIn(vs ...float64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldIn(FieldUnitPrice, vs...))
}

// UnitPriceNotIn applies the NotIn predicate on the "unit_price" field.
func UnitPriceNotIn(vs ...float64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNotIn(FieldUnitPrice, vs...))
}

// UnitPriceGT applies the GT predicate on the "unit_price" field.
func UnitPriceGT(v float64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldGT(FieldUnitPrice, v))
}

// UnitPriceGTE applies the GTE predicate on the "unit_price" field.
func UnitPriceGTE(v float64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldGTE(FieldUnitPrice, v))
}

// UnitPriceLT applies the LT predicate on the "unit_price" field.
func UnitPriceLT(v float64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldLT(FieldUnitPrice, v))
}

// UnitPriceLTE applies the LTE predicate on the "unit_price" field.
func UnitPriceLTE(v float64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldLTE(FieldUnitPrice, v))
}

// UnitSecondsEQ applies the EQ predicate on the "unit_seconds" field.
func UnitSecondsEQ(v float64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEQ(FieldUnitSeconds, v))
}

// UnitSecondsNEQ applies the NEQ predicate on the "unit_seconds" field.
func UnitSecondsNEQ(v float64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNEQ(FieldUnitSeconds, v))
}

// UnitSecondsIn applies the In predicate on the "unit_seconds" field.
func UnitSecondsIn(vs ...float64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldIn(FieldUnitSeconds, vs...))
}

// UnitSecondsNotIn applies the NotIn predicate on the "unit_seconds" field.
func UnitSecondsNotIn(vs ...float64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNotIn(FieldUnitSeconds, vs...))
}

// UnitSecondsGT applies the GT predicate on the "unit_seconds" field.
func UnitSecondsGT(v float64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldGT(FieldUnitSeconds, v))
}

// UnitSecondsGTE applies the GTE predicate on the "unit_seconds" field.
func UnitSecondsGTE(v float64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldGTE(FieldUnitSeconds, v))
}

// UnitSecondsLT applies the LT predicate on the "unit_seconds" field.
func UnitSecondsLT(v float64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldLT(FieldUnitSeconds, v))
}

// UnitSecondsLTE applies the LTE predicate on the "unit_seconds" field.
func UnitSecondsLTE(v float64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldLTE(FieldUnitSeconds, v))
}

// UnitSecondsIsNil applies the IsNil predicate on the "unit_seconds" field.
func UnitSecondsIsNil() predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldIsNull(FieldUnitSeconds))
}

// UnitSecondsNotNil applies the NotNil predicate on the "unit_seconds" field.
func UnitSecondsNotNil() predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNotNull(FieldUnitSeconds))
}

// RequestedSecondsEQ applies the EQ predicate on the "requested_seconds" field.
func RequestedSecondsEQ(v int) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEQ(FieldRequestedSeconds, v))
}

// RequestedSecondsNEQ applies the NEQ predicate on the "requested_seconds" field.
func RequestedSecondsNEQ(v int) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNEQ(FieldRequestedSeconds, v))
}

// RequestedSecondsIn applies the In predicate on the "requested_seconds" field.
func RequestedSecondsIn(vs ...int) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldIn(FieldRequestedSeconds, vs...))
}

// RequestedSecondsNotIn applies the NotIn predicate on the "requested_seconds" field.
func RequestedSecondsNotIn(vs ...int) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNotIn(FieldRequestedSeconds, vs...))
}

// RequestedSecondsGT applies the GT predicate on the "requested_seconds" field.
func RequestedSecondsGT(v int) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldGT(FieldRequestedSeconds, v))
}

// RequestedSecondsGTE applies the GTE predicate on the "requested_seconds" field.
func RequestedSecondsGTE(v int) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldGTE(FieldRequestedSeconds, v))
}

// RequestedSecondsLT applies the LT predicate on the "requested_seconds" field.
func RequestedSecondsLT(v int) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldLT(FieldRequestedSeconds, v))
}

// RequestedSecondsLTE applies the LTE predicate on the "requested_seconds" field.
func RequestedSecondsLTE(v int) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldLTE(FieldRequestedSeconds, v))
}

// RequestedSecondsIsNil applies the IsNil predicate on the "requested_seconds" field.
func RequestedSecondsIsNil() predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldIsNull(FieldRequestedSeconds))
}

// RequestedSecondsNotNil applies the NotNil predicate on the "requested_seconds" field.
func RequestedSecondsNotNil() predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNotNull(FieldRequestedSeconds))
}

// BillableSecondsEQ applies the EQ predicate on the "billable_seconds" field.
func BillableSecondsEQ(v int) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEQ(FieldBillableSeconds, v))
}

// BillableSecondsNEQ applies the NEQ predicate on the "billable_seconds" field.
func BillableSecondsNEQ(v int) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNEQ(FieldBillableSeconds, v))
}

// BillableSecondsIn applies the In predicate on the "billable_seconds" field.
func BillableSecondsIn(vs ...int) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldIn(FieldBillableSeconds, vs...))
}

// BillableSecondsNotIn applies the NotIn predicate on the "billable_seconds" field.
func BillableSecondsNotIn(vs ...int) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNotIn(FieldBillableSeconds, vs...))
}

// BillableSecondsGT applies the GT predicate on the "billable_seconds" field.
func BillableSecondsGT(v int) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldGT(FieldBillableSeconds, v))
}

// BillableSecondsGTE applies the GTE predicate on the "billable_seconds" field.
func BillableSecondsGTE(v int) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldGTE(FieldBillableSeconds, v))
}

// BillableSecondsLT applies the LT predicate on the "billable_seconds" field.
func BillableSecondsLT(v int) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldLT(FieldBillableSeconds, v))
}

// BillableSecondsLTE applies the LTE predicate on the "billable_seconds" field.
func BillableSecondsLTE(v int) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldLTE(FieldBillableSeconds, v))
}

// BillableSecondsIsNil applies the IsNil predicate on the "billable_seconds" field.
func BillableSecondsIsNil() predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldIsNull(FieldBillableSeconds))
}

// BillableSecondsNotNil applies the NotNil predicate on the "billable_seconds" field.
func BillableSecondsNotNil() predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNotNull(FieldBillableSeconds))
}

// ReservedCostEQ applies the EQ predicate on the "reserved_cost" field.
func ReservedCostEQ(v float64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEQ(FieldReservedCost, v))
}

// ReservedCostNEQ applies the NEQ predicate on the "reserved_cost" field.
func ReservedCostNEQ(v float64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNEQ(FieldReservedCost, v))
}

// ReservedCostIn applies the In predicate on the "reserved_cost" field.
func ReservedCostIn(vs ...float64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldIn(FieldReservedCost, vs...))
}

// ReservedCostNotIn applies the NotIn predicate on the "reserved_cost" field.
func ReservedCostNotIn(vs ...float64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNotIn(FieldReservedCost, vs...))
}

// ReservedCostGT applies the GT predicate on the "reserved_cost" field.
func ReservedCostGT(v float64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldGT(FieldReservedCost, v))
}

// ReservedCostGTE applies the GTE predicate on the "reserved_cost" field.
func ReservedCostGTE(v float64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldGTE(FieldReservedCost, v))
}

// ReservedCostLT applies the LT predicate on the "reserved_cost" field.
func ReservedCostLT(v float64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldLT(FieldReservedCost, v))
}

// ReservedCostLTE applies the LTE predicate on the "reserved_cost" field.
func ReservedCostLTE(v float64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldLTE(FieldReservedCost, v))
}

// EstimatedCostEQ applies the EQ predicate on the "estimated_cost" field.
func EstimatedCostEQ(v float64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEQ(FieldEstimatedCost, v))
}

// EstimatedCostNEQ applies the NEQ predicate on the "estimated_cost" field.
func EstimatedCostNEQ(v float64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNEQ(FieldEstimatedCost, v))
}

// EstimatedCostIn applies the In predicate on the "estimated_cost" field.
func EstimatedCostIn(vs ...float64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldIn(FieldEstimatedCost, vs...))
}

// EstimatedCostNotIn applies the NotIn predicate on the "estimated_cost" field.
func EstimatedCostNotIn(vs ...float64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNotIn(FieldEstimatedCost, vs...))
}

// EstimatedCostGT applies the GT predicate on the "estimated_cost" field.
func EstimatedCostGT(v float64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldGT(FieldEstimatedCost, v))
}

// EstimatedCostGTE applies the GTE predicate on the "estimated_cost" field.
func EstimatedCostGTE(v float64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldGTE(FieldEstimatedCost, v))
}

// EstimatedCostLT applies the LT predicate on the "estimated_cost" field.
func EstimatedCostLT(v float64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldLT(FieldEstimatedCost, v))
}

// EstimatedCostLTE applies the LTE predicate on the "estimated_cost" field.
func EstimatedCostLTE(v float64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldLTE(FieldEstimatedCost, v))
}

// ActualCostEQ applies the EQ predicate on the "actual_cost" field.
func ActualCostEQ(v float64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEQ(FieldActualCost, v))
}

// ActualCostNEQ applies the NEQ predicate on the "actual_cost" field.
func ActualCostNEQ(v float64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNEQ(FieldActualCost, v))
}

// ActualCostIn applies the In predicate on the "actual_cost" field.
func ActualCostIn(vs ...float64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldIn(FieldActualCost, vs...))
}

// ActualCostNotIn applies the NotIn predicate on the "actual_cost" field.
func ActualCostNotIn(vs ...float64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNotIn(FieldActualCost, vs...))
}

// ActualCostGT applies the GT predicate on the "actual_cost" field.
func ActualCostGT(v float64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldGT(FieldActualCost, v))
}

// ActualCostGTE applies the GTE predicate on the "actual_cost" field.
func ActualCostGTE(v float64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldGTE(FieldActualCost, v))
}

// ActualCostLT applies the LT predicate on the "actual_cost" field.
func ActualCostLT(v float64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldLT(FieldActualCost, v))
}

// ActualCostLTE applies the LTE predicate on the "actual_cost" field.
func ActualCostLTE(v float64) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldLTE(FieldActualCost, v))
}

// IdempotencyKeyEQ applies the EQ predicate on the "idempotency_key" field.
func IdempotencyKeyEQ(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEQ(FieldIdempotencyKey, v))
}

// IdempotencyKeyNEQ applies the NEQ predicate on the "idempotency_key" field.
func IdempotencyKeyNEQ(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNEQ(FieldIdempotencyKey, v))
}

// IdempotencyKeyIn applies the In predicate on the "idempotency_key" field.
func IdempotencyKeyIn(vs ...string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldIn(FieldIdempotencyKey, vs...))
}

// IdempotencyKeyNotIn applies the NotIn predicate on the "idempotency_key" field.
func IdempotencyKeyNotIn(vs ...string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNotIn(FieldIdempotencyKey, vs...))
}

// IdempotencyKeyGT applies the GT predicate on the "idempotency_key" field.
func IdempotencyKeyGT(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldGT(FieldIdempotencyKey, v))
}

// IdempotencyKeyGTE applies the GTE predicate on the "idempotency_key" field.
func IdempotencyKeyGTE(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldGTE(FieldIdempotencyKey, v))
}

// IdempotencyKeyLT applies the LT predicate on the "idempotency_key" field.
func IdempotencyKeyLT(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldLT(FieldIdempotencyKey, v))
}

// IdempotencyKeyLTE applies the LTE predicate on the "idempotency_key" field.
func IdempotencyKeyLTE(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldLTE(FieldIdempotencyKey, v))
}

// IdempotencyKeyContains applies the Contains predicate on the "idempotency_key" field.
func IdempotencyKeyContains(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldContains(FieldIdempotencyKey, v))
}

// IdempotencyKeyHasPrefix applies the HasPrefix predicate on the "idempotency_key" field.
func IdempotencyKeyHasPrefix(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldHasPrefix(FieldIdempotencyKey, v))
}

// IdempotencyKeyHasSuffix applies the HasSuffix predicate on the "idempotency_key" field.
func IdempotencyKeyHasSuffix(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldHasSuffix(FieldIdempotencyKey, v))
}

// IdempotencyKeyIsNil applies the IsNil predicate on the "idempotency_key" field.
func IdempotencyKeyIsNil() predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldIsNull(FieldIdempotencyKey))
}

// IdempotencyKeyNotNil applies the NotNil predicate on the "idempotency_key" field.
func IdempotencyKeyNotNil() predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNotNull(FieldIdempotencyKey))
}

// IdempotencyKeyEqualFold applies the EqualFold predicate on the "idempotency_key" field.
func IdempotencyKeyEqualFold(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEqualFold(FieldIdempotencyKey, v))
}

// IdempotencyKeyContainsFold applies the ContainsFold predicate on the "idempotency_key" field.
func IdempotencyKeyContainsFold(v string) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldContainsFold(FieldIdempotencyKey, v))
}

// SubmittedAtEQ applies the EQ predicate on the "submitted_at" field.
func SubmittedAtEQ(v time.Time) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEQ(FieldSubmittedAt, v))
}

// SubmittedAtNEQ applies the NEQ predicate on the "submitted_at" field.
func SubmittedAtNEQ(v time.Time) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNEQ(FieldSubmittedAt, v))
}

// SubmittedAtIn applies the In predicate on the "submitted_at" field.
func SubmittedAtIn(vs ...time.Time) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldIn(FieldSubmittedAt, vs...))
}

// SubmittedAtNotIn applies the NotIn predicate on the "submitted_at" field.
func SubmittedAtNotIn(vs ...time.Time) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNotIn(FieldSubmittedAt, vs...))
}

// SubmittedAtGT applies the GT predicate on the "submitted_at" field.
func SubmittedAtGT(v time.Time) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldGT(FieldSubmittedAt, v))
}

// SubmittedAtGTE applies the GTE predicate on the "submitted_at" field.
func SubmittedAtGTE(v time.Time) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldGTE(FieldSubmittedAt, v))
}

// SubmittedAtLT applies the LT predicate on the "submitted_at" field.
func SubmittedAtLT(v time.Time) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldLT(FieldSubmittedAt, v))
}

// SubmittedAtLTE applies the LTE predicate on the "submitted_at" field.
func SubmittedAtLTE(v time.Time) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldLTE(FieldSubmittedAt, v))
}

// SubmittedAtIsNil applies the IsNil predicate on the "submitted_at" field.
func SubmittedAtIsNil() predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldIsNull(FieldSubmittedAt))
}

// SubmittedAtNotNil applies the NotNil predicate on the "submitted_at" field.
func SubmittedAtNotNil() predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNotNull(FieldSubmittedAt))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldLTE(FieldStartedAt, v))
}

// StartedAtIsNil applies the IsNil predicate on the "started_at" field.
func StartedAtIsNil() predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldIsNull(FieldStartedAt))
}

// StartedAtNotNil applies the NotNil predicate on the "started_at" field.
func StartedAtNotNil() predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNotNull(FieldStartedAt))
}

// CompletedAtEQ applies the EQ predicate on the "completed_at" field.
func CompletedAtEQ(v time.Time) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEQ(FieldCompletedAt, v))
}

// CompletedAtNEQ applies the NEQ predicate on the "completed_at" field.
func CompletedAtNEQ(v time.Time) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNEQ(FieldCompletedAt, v))
}

// CompletedAtIn applies the In predicate on the "completed_at" field.
func CompletedAtIn(vs ...time.Time) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldIn(FieldCompletedAt, vs...))
}

// CompletedAtNotIn applies the NotIn predicate on the "completed_at" field.
func CompletedAtNotIn(vs ...time.Time) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNotIn(FieldCompletedAt, vs...))
}

// CompletedAtGT applies the GT predicate on the "completed_at" field.
func CompletedAtGT(v time.Time) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldGT(FieldCompletedAt, v))
}

// CompletedAtGTE applies the GTE predicate on the "completed_at" field.
func CompletedAtGTE(v time.Time) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldGTE(FieldCompletedAt, v))
}

// CompletedAtLT applies the LT predicate on the "completed_at" field.
func CompletedAtLT(v time.Time) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldLT(FieldCompletedAt, v))
}

// CompletedAtLTE applies the LTE predicate on the "completed_at" field.
func CompletedAtLTE(v time.Time) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldLTE(FieldCompletedAt, v))
}

// CompletedAtIsNil applies the IsNil predicate on the "completed_at" field.
func CompletedAtIsNil() predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldIsNull(FieldCompletedAt))
}

// CompletedAtNotNil applies the NotNil predicate on the "completed_at" field.
func CompletedAtNotNil() predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNotNull(FieldCompletedAt))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNotNull(FieldExpiresAt))
}

// NextPollAtEQ applies the EQ predicate on the "next_poll_at" field.
func NextPollAtEQ(v time.Time) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEQ(FieldNextPollAt, v))
}

// NextPollAtNEQ applies the NEQ predicate on the "next_poll_at" field.
func NextPollAtNEQ(v time.Time) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNEQ(FieldNextPollAt, v))
}

// NextPollAtIn applies the In predicate on the "next_poll_at" field.
func NextPollAtIn(vs ...time.Time) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldIn(FieldNextPollAt, vs...))
}

// NextPollAtNotIn applies the NotIn predicate on the "next_poll_at" field.
func NextPollAtNotIn(vs ...time.Time) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNotIn(FieldNextPollAt, vs...))
}

// NextPollAtGT applies the GT predicate on the "next_poll_at" field.
func NextPollAtGT(v time.Time) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldGT(FieldNextPollAt, v))
}

// NextPollAtGTE applies the GTE predicate on the "next_poll_at" field.
func NextPollAtGTE(v time.Time) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldGTE(FieldNextPollAt, v))
}

// NextPollAtLT applies the LT predicate on the "next_poll_at" field.
func NextPollAtLT(v time.Time) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldLT(FieldNextPollAt, v))
}

// NextPollAtLTE applies the LTE predicate on the "next_poll_at" field.
func NextPollAtLTE(v time.Time) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldLTE(FieldNextPollAt, v))
}

// NextPollAtIsNil applies the IsNil predicate on the "next_poll_at" field.
func NextPollAtIsNil() predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldIsNull(FieldNextPollAt))
}

// NextPollAtNotNil applies the NotNil predicate on the "next_poll_at" field.
func NextPollAtNotNil() predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNotNull(FieldNextPollAt))
}

// PollCountEQ applies the EQ predicate on the "poll_count" field.
func PollCountEQ(v int) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEQ(FieldPollCount, v))
}

// PollCountNEQ applies the NEQ predicate on the "poll_count" field.
func PollCountNEQ(v int) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNEQ(FieldPollCount, v))
}

// PollCountIn applies the In predicate on the "poll_count" field.
func PollCountIn(vs ...int) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldIn(FieldPollCount, vs...))
}

// PollCountNotIn applies the NotIn predicate on the "poll_count" field.
func PollCountNotIn(vs ...int) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNotIn(FieldPollCount, vs...))
}

// PollCountGT applies the GT predicate on the "poll_count" field.
func PollCountGT(v int) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldGT(FieldPollCount, v))
}

// PollCountGTE applies the GTE predicate on the "poll_count" field.
func PollCountGTE(v int) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldGTE(FieldPollCount, v))
}

// PollCountLT applies the LT predicate on the "poll_count" field.
func PollCountLT(v int) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldLT(FieldPollCount, v))
}

// PollCountLTE applies the LTE predicate on the "poll_count" field.
func PollCountLTE(v int) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldLTE(FieldPollCount, v))
}

// LockedUntilEQ applies the EQ predicate on the "locked_until" field.
func LockedUntilEQ(v time.Time) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEQ(FieldLockedUntil, v))
}

// LockedUntilNEQ applies the NEQ predicate on the "locked_until" field.
func LockedUntilNEQ(v time.Time) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNEQ(FieldLockedUntil, v))
}

// LockedUntilIn applies the In predicate on the "locked_until" field.
func LockedUntilIn(vs ...time.Time) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldIn(FieldLockedUntil, vs...))
}

// LockedUntilNotIn applies the NotIn predicate on the "locked_until" field.
func LockedUntilNotIn(vs ...time.Time) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNotIn(FieldLockedUntil, vs...))
}

// LockedUntilGT applies the GT predicate on the "locked_until" field.
func LockedUntilGT(v time.Time) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldGT(FieldLockedUntil, v))
}

// LockedUntilGTE applies the GTE predicate on the "locked_until" field.
func LockedUntilGTE(v time.Time) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldGTE(FieldLockedUntil, v))
}

// LockedUntilLT applies the LT predicate on the "locked_until" field.
func LockedUntilLT(v time.Time) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldLT(FieldLockedUntil, v))
}

// LockedUntilLTE applies the LTE predicate on the "locked_until" field.
func LockedUntilLTE(v time.Time) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldLTE(FieldLockedUntil, v))
}

// LockedUntilIsNil applies the IsNil predicate on the "locked_until" field.
func LockedUntilIsNil() predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldIsNull(FieldLockedUntil))
}

// LockedUntilNotNil applies the NotNil predicate on the "locked_until" field.
func LockedUntilNotNil() predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNotNull(FieldLockedUntil))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAPIKey applies the HasEdge predicate on the "api_key" edge.
func HasAPIKey() predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, APIKeyTable, APIKeyColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAPIKeyWith applies the HasEdge predicate on the "api_key" edge with a given conditions (other predicates).
func HasAPIKeyWith(preds ...predicate.APIKey) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(func(s *sql.Selector) {
		step := newAPIKeyStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAccount applies the HasEdge predicate on the "account" edge.
func HasAccount() predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AccountTable, AccountColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccountWith applies the HasEdge predicate on the "account" edge with a given conditions (other predicates).
func HasAccountWith(preds ...predicate.Account) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(func(s *sql.Selector) {
		step := newAccountStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasGroup applies the HasEdge predicate on the "group" edge.
func HasGroup() predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, GroupTable, GroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupWith applies the HasEdge predicate on the "group" edge with a given conditions (other predicates).
func HasGroupWith(preds ...predicate.Group) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(func(s *sql.Selector) {
		step := newGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasVideoModel applies the HasEdge predicate on the "video_model" edge.
func HasVideoModel() predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, VideoModelTable, VideoModelColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasVideoModelWith applies the HasEdge predicate on the "video_model" edge with a given conditions (other predicates).
func HasVideoModelWith(preds ...predicate.VideoModel) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(func(s *sql.Selector) {
		step := newVideoModelStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.VideoGenerationTask) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.VideoGenerationTask) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.VideoGenerationTask) predicate.VideoGenerationTask {
	return predicate.VideoGenerationTask(sql.NotPredicates(p))
}
