// Code generated by ent, DO NOT EDIT.

package videocalltemplate

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the videocalltemplate type in the database.
	Label = "video_call_template"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldCreateMethod holds the string denoting the create_method field in the database.
	FieldCreateMethod = "create_method"
	// FieldCreatePath holds the string denoting the create_path field in the database.
	FieldCreatePath = "create_path"
	// FieldQueryMethod holds the string denoting the query_method field in the database.
	FieldQueryMethod = "query_method"
	// FieldQueryPath holds the string denoting the query_path field in the database.
	FieldQueryPath = "query_path"
	// FieldContentMethod holds the string denoting the content_method field in the database.
	FieldContentMethod = "content_method"
	// FieldContentPath holds the string denoting the content_path field in the database.
	FieldContentPath = "content_path"
	// FieldCancelMethod holds the string denoting the cancel_method field in the database.
	FieldCancelMethod = "cancel_method"
	// FieldCancelPath holds the string denoting the cancel_path field in the database.
	FieldCancelPath = "cancel_path"
	// FieldStatusMapping holds the string denoting the status_mapping field in the database.
	FieldStatusMapping = "status_mapping"
	// FieldResultMapping holds the string denoting the result_mapping field in the database.
	FieldResultMapping = "result_mapping"
	// FieldErrorMapping holds the string denoting the error_mapping field in the database.
	FieldErrorMapping = "error_mapping"
	// FieldPollConfig holds the string denoting the poll_config field in the database.
	FieldPollConfig = "poll_config"
	// FieldTimeoutConfig holds the string denoting the timeout_config field in the database.
	FieldTimeoutConfig = "timeout_config"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// EdgeVideoModels holds the string denoting the video_models edge name in mutations.
	EdgeVideoModels = "video_models"
	// Table holds the table name of the videocalltemplate in the database.
	Table = "video_call_templates"
	// VideoModelsTable is the table that holds the video_models relation/edge.
	VideoModelsTable = "video_models"
	// VideoModelsInverseTable is the table name for the VideoModel entity.
	// It exists in this package in order to avoid circular dependency with the "videomodel" package.
	VideoModelsInverseTable = "video_models"
	// VideoModelsColumn is the table column denoting the video_models relation/edge.
	VideoModelsColumn = "template_id"
)

// Columns holds all SQL columns for videocalltemplate fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldName,
	FieldCreateMethod,
	FieldCreatePath,
	FieldQueryMethod,
	FieldQueryPath,
	FieldContentMethod,
	FieldContentPath,
	FieldCancelMethod,
	FieldCancelPath,
	FieldStatusMapping,
	FieldResultMapping,
	FieldErrorMapping,
	FieldPollConfig,
	FieldTimeoutConfig,
	FieldStatus,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultCreateMethod holds the default value on creation for the "create_method" field.
	DefaultCreateMethod string
	// CreateMethodValidator is a validator for the "create_method" field. It is called by the builders before save.
	CreateMethodValidator func(string) error
	// CreatePathValidator is a validator for the "create_path" field. It is called by the builders before save.
	CreatePathValidator func(string) error
	// DefaultQueryMethod holds the default value on creation for the "query_method" field.
	DefaultQueryMethod string
	// QueryMethodValidator is a validator for the "query_method" field. It is called by the builders before save.
	QueryMethodValidator func(string) error
	// QueryPathValidator is a validator for the "query_path" field. It is called by the builders before save.
	QueryPathValidator func(string) error
	// ContentMethodValidator is a validator for the "content_method" field. It is called by the builders before save.
	ContentMethodValidator func(string) error
	// ContentPathValidator is a validator for the "content_path" field. It is called by the builders before save.
	ContentPathValidator func(string) error
	// CancelMethodValidator is a validator for the "cancel_method" field. It is called by the builders before save.
	CancelMethodValidator func(string) error
	// CancelPathValidator is a validator for the "cancel_path" field. It is called by the builders before save.
	CancelPathValidator func(string) error
	// DefaultStatusMapping holds the default value on creation for the "status_mapping" field.
	DefaultStatusMapping map[string]string
	// DefaultResultMapping holds the default value on creation for the "result_mapping" field.
	DefaultResultMapping map[string]string
	// DefaultErrorMapping holds the default value on creation for the "error_mapping" field.
	DefaultErrorMapping map[string]string
	// DefaultPollConfig holds the default value on creation for the "poll_config" field.
	DefaultPollConfig func() map[string]interface{}
	// DefaultTimeoutConfig holds the default value on creation for the "timeout_config" field.
	DefaultTimeoutConfig func() map[string]interface{}
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
)

// OrderOption defines the ordering options for the VideoCallTemplate queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByCreateMethod orders the results by the create_method field.
func ByCreateMethod(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateMethod, opts...).ToFunc()
}

// ByCreatePath orders the results by the create_path field.
func ByCreatePath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatePath, opts...).ToFunc()
}

// ByQueryMethod orders the results by the query_method field.
func ByQueryMethod(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQueryMethod, opts...).ToFunc()
}

// ByQueryPath orders the results by the query_path field.
func ByQueryPath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQueryPath, opts...).ToFunc()
}

// ByContentMethod orders the results by the content_method field.
func ByContentMethod(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContentMethod, opts...).ToFunc()
}

// ByContentPath orders the results by the content_path field.
func ByContentPath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContentPath, opts...).ToFunc()
}

// ByCancelMethod orders the results by the cancel_method field.
func ByCancelMethod(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCancelMethod, opts...).ToFunc()
}

// ByCancelPath orders the results by the cancel_path field.
func ByCancelPath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCancelPath, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByVideoModelsCount orders the results by video_models count.
func ByVideoModelsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newVideoModelsStep(), opts...)
	}
}

// ByVideoModels orders the results by video_models terms.
func ByVideoModels(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newVideoModelsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newVideoModelsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(VideoModelsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, VideoModelsTable, VideoModelsColumn),
	)
}
